### ISSUE TITLE
[Other]: Need help with script extracting

### ISSUE THREAD

**Issue by Darklaser38** [AssetRipper/AssetRipper#1005]
### Describe the issue

Hello i got a problem. So i can't extract the script from the assetbundle that i want to. The game is an android game based on IL2Cpp. Here the log.
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12440704/AssetRipper.log)

**Comment by ds5678** [comment]
I assume it crashes?

**Comment by Darklaser38** [comment]
No its just that the script are dummy script

**Comment by Darklaser38** [comment]
[script.txt](https://github.com/AssetRipper/AssetRipper/files/12440769/script.txt)

**Comment by ds5678** [comment]
Duplicate of #655
