### ISSUE TITLE
[Bug]: Certain exported meshes crash Unity

### ISSUE THREAD

**Issue by Lionmeow** [AssetRipper/AssetRipper#1010]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

[Slime Rancher](https://steamdb.info/app/433340/)

### Which Unity version did this occur on?

2019.4.29f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Certain YAML mesh assets, upon import, completely crash the Unity editor. Upon reopening the editor, the project is left in an unusable state, as even if you remove the broken mesh file, it immediately crashes.

The most recent one that it's happened for in this particular game was housePotPlant, though it has happened for other assets too in the past. 

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12465952/AssetRipper.log)

**Comment by ds5678** [comment]
Can you be specific about which ones cause the crash and how you know they're responsible?

**Comment by Lionmeow** [comment]
Upon looking closer at the error logs, this is actually another case of #811.

**Comment by ds5678** [comment]
So the latest commit doesn't exhibit this problem for you?

**Comment by Lionmeow** [comment]
Seems so, yes. It doesn't export lighting data, which does fix the issue.
