### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SoldierOfHeroin** [AssetRipper/AssetRipper#1011]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://steamdb.info/app/700330/

### Which Unity version did this occur on?

2021.3.17f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I couldn't uncompile any scipts files

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12468295/AssetRipper.log)

**Comment by ds5678** [comment]
Problem with https://github.com/SamboyCoding/Cpp2IL
