### ISSUE TITLE
[Other]: After change the language, the dropdown selection on the page cannot be refreshed correctly.

### ISSUE THREAD

**Issue by Super12138** [AssetRipper/AssetRipper#1014]
### Describe the issue

Look at these screenshots
Before change the language:
![image](https://github.com/AssetRipper/AssetRipper/assets/70494801/375d43c2-c613-4567-a1b1-4c20e7f13e90)
After change the language:
![image](https://github.com/AssetRipper/AssetRipper/assets/70494801/d6616483-227a-4a66-bbca-6a96e78c75b5)

Like `Direct Export`, in changing the language, it is not translated into `直接导出`.

**Comment by Super12138** [comment]
Thank you for the reminder! This is the log file: 
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12484158/AssetRipper.log)

**Comment by ds5678** [comment]
#919 is nearing completion. When it's done, this won't be an issue anymore.
