### ISSUE TITLE
[Bug]: Issue loading apk and obb files together

### ISSUE THREAD

**Issue by TheInfinityUser** [AssetRipper/AssetRipper#1022]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Pixel Gun 3D ([Google Play](https://play.google.com/store/apps/details?id=com.pixel.gun3d&hl=en&gl=US))

### Which Unity version did this occur on?

2021.3.14f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Get the apk and obb files for the game, extract each, and paste the assets folder (inside the extracted obb directory) in the extracted apk directory such that the assets folder in both are merged together. Then open the extracted apk directory in AssetRipper. The program is unable to load the folder and crashes.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12525364/AssetRipper.log)

**Comment by ds5678** [comment]
I don't think the error has anything to do with you loading them together. I think the error would still occur if you loaded them separately.

**Comment by TheInfinityUser** [comment]
The error doesn't occur when they are loaded separately (as I have already successfully extracted the obb and apk)

**Comment by TheInfinityUser** [comment]
I have tested with the apk separately and it loads and exports without issue.

**Comment by ds5678** [comment]
If the apk loads by itself, then the obb is the problem.

**Comment by TheInfinityUser** [comment]
Well, any solution? Because I've had no problem loading them separately.

**Comment by ds5678** [comment]
> I've had no problem loading any of them separately.

Given the location of the error, it will not be affected by the presence or absence of any dependencies. If the error doesn't occur, then the responsible asset wasn't loaded.

**Comment by ds5678** [comment]
Closing in favor of #1025
