### ISSUE TITLE
[Bug]: Unknown attributes for ParticleSystem in CustomCurveResolver

### ISSUE THREAD

**Issue by a1991221** [AssetRipper/AssetRipper#1025]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://steamdb.info/app/1206610/

Rubber.Bandits.Build.10729446  

### Which Unity version did this occur on?

Unity version: 2021.3.3a0

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Unity version: 2021.3.3a0 System.ArgumentException: Unknown attribute 1211796145 for ParticleSystem

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12566084/AssetRipper.log)

**Comment by ds5678** [comment]
#1022 had a very similar issue:
```
[Error] : System.ArgumentException: Unknown attribute 1173142787 for ParticleSystem
```
