### ISSUE TITLE
[BUG]:System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.    at AsmResolver.PE.File.Headers.DosHeader.FromReader(BinaryStreamReader& reader)

### ISSUE THREAD

**Issue by CodeEngieer** [AssetRipper/AssetRipper#1026]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

When opening AssetRipper to read files, it works fine, but when exporting all files, it gives this error.

### Which Unity version did this occur on?

Unable to export project files, not even a single file can be exported.

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

See more details On AssetRipper.log：
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12569431/AssetRipper.log)

**Comment by CodeEngieer** [comment]
![image](https://github.com/AssetRipper/AssetRipper/assets/75971727/bb058c10-179d-4d8a-bbd5-d38265e911b5)

**Comment by ds5678** [comment]
Not my fault. Either AsmResolver or the game developer is to blame, but I have nothing to do with this.
