### ISSUE TITLE
[Bug]:  issue

### ISSUE THREAD

**Issue by GuyThatMakesFNFMods** [AssetRipper/AssetRipper#1041]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

cube runners

### Which Unity version did this occur on?

2021.3.12f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

i opened the project and got over 1000 errors, when i clicked ignore, unity crashed

**Comment by ds5678** [comment]
That sounds more-or-less normal. Script compilation errors are common.

**Comment by ds5678** [comment]
I'm closing this because it sounds like there's no measure for resolution. You want script decompilation to be better, and that is a continuous goal for AssetRipper. It doesn't have an end.
