### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Kronkly** [AssetRipper/AssetRipper#1046]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

GTFO, app ID:	493520

### Which Unity version did this occur on?

Can't find

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

The asset ripper seems to miss a few meshes, with the file being created but not containing any mesh. Notable with the "Headgear010" file. It also doesn't create an AssetPrefab folder.
It is possible I don't have prefab dumping enabled, but I can't seem to enable it from the settings.

**Comment by ds5678** [comment]
AssetRipper doesn't miss anything on PC games.
