### ISSUE TITLE
[Bug]: Asset Ripper does not extract skeletons from models that were not prefab marked in the editor

### ISSUE THREAD

**Issue by Infinity-Loops** [AssetRipper/AssetRipper#105]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2021.1.19f1

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

When decompiling a game that has asset bundles or normal format, if it references models without prefabs, the skeleton may be missing, I prepared a project in which there is a humanoid model, in this project in the test scene, a ragdoll is created in realtime, everything goes perfectly in the original project, but in the decompiled project, the ragdoll creation is not possible due to the lack of the skeleton, even the mesh is invisible
![image](https://user-images.githubusercontent.com/13188882/134918796-161eb60f-4613-4d42-8a89-a3502ca757fb.png)
project image generated by the asset ripper above
![image](https://user-images.githubusercontent.com/13188882/134918943-012def37-c489-4685-8d4d-63b8f15cdd7d.png)
image of the original project above
![image](https://user-images.githubusercontent.com/13188882/134919023-196fd2fb-d804-4455-9d1e-513dd01a4d0f.png)
original code above
![image](https://user-images.githubusercontent.com/13188882/134919105-629e08ed-bbc9-4dd0-8a6f-a5e63e405892.png)
code generated by the asset ripper above
![image](https://user-images.githubusercontent.com/13188882/134919171-7c4963ef-e55b-4a15-ab90-6aac44f434fd.png)
"model" extract by the asset ripper above
![image](https://user-images.githubusercontent.com/13188882/134919247-d830e2ed-026c-4b45-bc5f-fe87f7a8a3a6.png)
original model above

https://user-images.githubusercontent.com/13188882/134919333-cb1894ef-74e4-4bda-8e44-cb457f5675ff.mp4 
video of the project generated by asset ripper running above

https://user-images.githubusercontent.com/13188882/134919716-3c9b378f-7b65-4d4d-8747-5c23ff65c725.mp4
video of the original project running above

### Relevant log output

[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7236646/AssetRipper.log)

**Comment by ds5678** [comment]
Although I can't be certain without test files, I am fairly sure this isn't AssetRipper's fault. If this issue is still troubling you, feel free to reopen it and upload test files for further investigation.
