### ISSUE TITLE
[Question]: Could you make an AUR package please

### ISSUE THREAD

**Issue by awsdert** [AssetRipper/AssetRipper#1053]
### Question

Wanted to install this on my system but I don't want to deal with dependencies and whatnot. Would be nice to be able to just load the AUR package and let the package manager build/install whatever it needs to automatically.

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by ds5678** [comment]
That is very niche, and I have no idea how I would even do that.

**Comment by awsdert** [comment]
Well it's better than trying to support all the arch distros manually, I can just try building it and see what happens, also AUR is not exactly niche, I'm pretty sure all the arch distros like manjaro (of which I'm running) make it accessible from the package manager. I think all you need to do is open an account then write a set of instructions for the package manager to understand how to build and install assetripper, then upload it, I'm not expecting anything more than that

**Comment by ds5678** [comment]
What's this part about opening an account? Unless there is a substantial demand for these packages, I'm not interested in increasing the workload of posting releases.

**Comment by aldelaro5** [comment]
I am trying to understand what stops someone from maintaining an AUR without involving upstream.

Most AUR packages I see are maintained by arch users and they take upstream, do the build locally and then do scripts to install them. So I am not sure why upstream needs to be involved to make one.

**Comment by awsdert** [comment]
It makes the package more trustworthy if it comes from the author of the software themself. I'd add another point if I could think of one but for now I'd be satisfied with a package that links to the git repo, won't complain if you do binary packages though :)

**Comment by ds5678** [comment]
Do AUR packages have to be uniquely named? Could an abandoned user package prevent the upstream team from later releasing their own?

**Comment by ds5678** [comment]
> As far as I know the AUR packages are a set and forget if it's linked to a git repo

So I will only have to ever mess with this once? And nothing I do in the repo can break the package?

**Comment by ds5678** [comment]
What is the bare minimum required for this?

**Comment by awsdert** [comment]
Sorry, didn't expect a barrage of responses, been modifying a mod for a game, but yes, I expect it's only once you'll need to mess with this, if it doesn't turn out to be then just let me know and I'll give up on the request

**Comment by awsdert** [comment]
As far as bare minimum I would expect the package script to just download the latest git code and compile it locally, then finally install it, as for release based, maybe there's some way to filter the git input to determine what is and is not a release and compile just those. I'm certain there's some way for telling the package manager what you want it to do when checking for updates, possibly in the same script. I've never made an AUR package yet (plan to for the aforementioned solution I'm working on since it's a launcher & library pair using `PATH` variable) so I don't know the specifics, if it's do-able to "set and forget" then please do so, that's the most I'm asking, if it's not then too bad, I'll just have to download and manually deal with the details.

**Comment by ds5678** [comment]
I think you should do it first, so you can tell me how to do it.

**Comment by awsdert** [comment]
That'll be a while given my project's complexity, I have to make a library that behaves the same on any operating system and is happy to run under whatever ABI the launcher launches with. I have to trial various `PATH` layouts to see what works best for targeting just the CPU with any app that happens to be compiled for just the CPU and my library's API. I also need to design a way for interacting with graphics & sound libraries on the native system that hides the differences between them. I need to do likewise for input peripherals. I also need to ensure text encoding is easy to manage. It's a big project and still in alpha stage. It's unlikely I will be ready to do a beta test until 3-4 years later.

Plus once my project is complete it will render the request null and void since I'd instead ask you could to just compile for all CPUs with my API and just make it a single set of binaries to install in either my user directory `~/.paw/...` or an OTG directory `usb://otg/.paw/...`. The request is just for until the library and launcher are made then there's no more debian, flatpak, snaps, windows etc to worry about, just the library, not even a need to distinguish between debug and release libraries, the launcher will take take of that with the `PATH` variable, something like `~/.paw/linux-x86/debug/...:~/.paw/all-x86/debug/...:~/.paw/linux-x86/release/...:~/.paw/all-x86/release/...:$PATH` would be generated if `paw --debug assetripper ...` were put in the command line while `~/.paw/linux-x86/release/...:~/.paw/all-x86/release/...:$PATH` would be used instead if `paw --start assetripper ...` were launched instead. Naturally that method of launching would render it pointless to specifically target all systems for assetripper, instead you'd make a one time package for each distro that just passes it's arguments along to the real version under paw and does it's updates likewise with something like `paw --update assetripper-updater ...` which would just print what it downloaded with indicators for what should go to which set of paths. So for now could you please at least take a look at the AUR package script docs and see if this short term request is do-able as a one-time thing for assetripper until my project is ready.

**Comment by ds5678** [comment]
I am unlikely to do anything with this at this time. Only about 5% of my users use Linux, and you are the first person to even mention Arch. As an unpaid developer, I will likely always have higher priorities.

**Comment by awsdert** [comment]
That's fine, at least you didn't refuse to do it, I can live with a wait since the modifications I needed to make were do-able with what the peops using the windows variant were able to provide me with of the extracted assets

**Comment by ds5678** [comment]
>  I can live with a wait

I'm saying it might never come from me.

**Comment by awsdert** [comment]
That's also the same as you might still do it

**Comment by ds5678** [comment]
I am closing this as not planned. It may be reopened if a significant number of users request it.

**Comment by claymorwan** [comment]
Here u go, should be working 
https://aur.archlinux.org/packages/asset-ripper-bin
