### ISSUE TITLE
[Bug]: bug

### ISSUE THREAD

**Issue by Varisss31** [AssetRipper/AssetRipper#1055]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Party Animals
https://steamdb.info/app/1260320/

### Which Unity version did this occur on?

2021.3.5.4254522

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

When you click "Open Folder" an error occurs

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12772634/AssetRipper.log)

**Comment by ds5678** [comment]
> [Error] : AssetRipper.IO.Files.Exceptions.EncryptedFileException: File 'cab-16bb55f95ae780bce9d138d0c3bfa493' is likely encrypted or using custom compression.
