### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Zarq0** [AssetRipper/AssetRipper#1064]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Madness Melee
https://orsonik.itch.io/madness-melee

### Which Unity version did this occur on?

2021.1.23f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Unity throws you into safe mode with assembly references missing, crash on attempting to continue.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12890168/AssetRipper.log)

**Comment by Zarq0** [comment]
![image](https://github.com/AssetRipper/AssetRipper/assets/75623951/c8da6b01-5865-4909-b0eb-ae5fc1d95696)

**Comment by ds5678** [comment]
Script compilation errors are extremely common.
