### ISSUE TITLE
[Bug]: AnimCurves are not exported correctly for properties

### ISSUE THREAD

**Issue by misternebula** [AssetRipper/AssetRipper#1066]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Outer Wilds https://steamdb.info/app/753640

### Which Unity version did this occur on?

2019.4.39f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Animation curves that affect animator properties are exported, but not tied to the actual property. 
![image](https://github.com/AssetRipper/AssetRipper/assets/41904486/fe431ce7-60b9-4ddd-9d34-6f8c640e4651)
This should be affecting `GrabWindow` in the animation controller.

**Comment by ds5678** [comment]
This sounds like a duplicate of #1009

**Comment by misternebula** [comment]
Ah yup. I'll close this one, thanks.
