### ISSUE TITLE
[Other]: EXE not opening

### ISSUE THREAD

**Issue by JumbleJamJam** [AssetRipper/AssetRipper#1076]
### Describe the issue

Whenever I try to open it, it just wont open I tried everything.

**Comment by JumbleJamJam** [comment]
there is no log file

**Comment by ds5678** [comment]
You probably downloaded the wrong cpu architecture.

**Comment by JumbleJamJam** [comment]
what do you mean what is that?

**Comment by ds5678** [comment]
https://github.com/AssetRipper/AssetRipper/releases/download/0.3.4.0/AssetRipper_win_x64.zip
https://github.com/AssetRipper/AssetRipper/releases/download/0.3.4.0/AssetRipper_win_arm64.zip

**Comment by JumbleJamJam** [comment]
same thing for both of those

**Comment by ds5678** [comment]
I'm going to take a wild guess that you're on an old version of Windows, like XP, Vista, or maybe 7.

**Comment by JumbleJamJam** [comment]
No I am using a acer nitro 5 windows 11

**Comment by JumbleJamJam** [comment]
this is the model I use AN515-57

**Comment by ds5678** [comment]
> No I am using a acer nitro 5 windows 11

It's possible that Windows Defender (or another antivirus) is preventing AssetRipper from launching.

**Comment by JumbleJamJam** [comment]
Turned that off still nothing

**Comment by ds5678** [comment]
Run it from a command prompt.

**Comment by JumbleJamJam** [comment]
How will I do that?

**Comment by JumbleJamJam** [comment]
I did start and this is what it did 
![image](https://github.com/AssetRipper/AssetRipper/assets/68656820/1df5502a-8494-457e-9dd8-44391f4ae073)

**Comment by ds5678** [comment]
Google it

**Comment by JumbleJamJam** [comment]
I did it but it just pops up another cmd
![image](https://github.com/AssetRipper/AssetRipper/assets/68656820/3ed512f9-e754-4749-969d-9742b9165239)

**Comment by ds5678** [comment]
It is not my job to teach you how to run a program in the command prompt.

**Comment by JumbleJamJam** [comment]
Sorry I am just stupid but I figured it out and it worked so thank you so much

**Comment by ds5678** [comment]
You're welcome

**Comment by IsuckAtcomputering** [comment]
boi

**Comment by ds5678** [comment]
What?
