### ISSUE TITLE
[Question]: Is mobile supported?

### ISSUE THREAD

**Issue by caleb14472** [AssetRipper/AssetRipper#1080]
### Question

can we decompile unity mobile games?

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by gabzin1222** [comment]
yes, u can, just drop all content of folder (game).apk\assets\bin\Data in the assetripper and the asset ripper read the files (sorry if my text is bad bc i am learning english , i am from brazil)

**Comment by ds5678** [comment]
Mobile is supported. Unless you present evidence to the contrary, this issue will be closed.

**Comment by ds5678** [comment]
Feel free to reopen the issue if you find said evidence.
