### ISSUE TITLE
[Question]: can I use the latest version of unity to open the decompile file?

### ISSUE THREAD

**Issue by HanungFX** [AssetRipper/AssetRipper#1081]
### Question

like,i decompile a unity game,but the dev use 2018 unity version
and i use 2023 unity version

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by ds5678** [comment]
You pinged a random contributor in Discord, and when they didn't respond immediately, you decided to clutter my issues section in demand of an answer. I'm not sure you deserve one.

The short answer to your question is "maybe."

**Comment by HanungFX** [comment]
thanks :))
