### ISSUE TITLE
[Bug]: Import : System.BadImageFormatException

### ISSUE THREAD

**Issue by afonsinha** [AssetRipper/AssetRipper#1086]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Just Dance Vitality School Mobile Version / 舞力全开：活力派

### Which Unity version did this occur on?

Unity 5.3.4p4

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

AssetRipper does not extract

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/13256851/AssetRipper.log)

**Comment by ds5678** [comment]
> [Error] : System.BadImageFormatException: Could not read C:\Users\01\Desktop\jdvs\jdchinarecentrelease\assets\bin\Data\Managed\Assembly-CSharp.dll ---> System.BadImageFormatException: Invalid metadata header (050C1606).

It says your assembly is malformed.
