### ISSUE TITLE
[Bug]: Object's type AudioClip_4_3_0 isn't assignable from IPhysicMaterial

### ISSUE THREAD

**Issue by Virjoinga** [AssetRipper/AssetRipper#1095]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Cordy - https://cordy.en.uptodown.com/android (original google play store link is dead)

### Which Unity version did this occur on?

Game files have these Unity versions: 4.5.5p4 4.5.0f1 3.5.7f3

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

When exporting the game files, AssetRipper will throw an error about AudioClip:
System.Exception: Object's type AudioClip_4_3_0 isn't assignable from IPhysicMaterial

There are also a bunch of instances of audioclips not exporting properly, most likely due to this (maybe that is related):
https://github.com/AssetRipper/AssetRipper/issues/353

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/13330312/AssetRipper.log)

**Comment by ds5678** [comment]
> Game files have these Unity versions: 4.5.5p4 4.5.0f1 3.5.7f3

This is almost certainly the cause of your issue. You have some outdated files that don't belong.

**Comment by Virjoinga** [comment]
> > Game files have these Unity versions: 4.5.5p4 4.5.0f1 3.5.7f3
> 
> This is almost certainly the cause of your issue. You have some outdated files that don't belong.

This is how the game is shipped. Is this solvable in AssetRipper? If not, I can re-download the game and try again.

**Comment by ds5678** [comment]
There are occasional instances where developers forget to delete files when they update the game.

**Comment by Virjoinga** [comment]
> There are occasional instances where developers forget to delete files when they update the game.

Hmm well there is a folder called "cordy_asset_data" that contains; "Bootstrap.assetBundle", "data0.unity3d", "data1.unity3d", and "resources.csv". Could that be the old files?

**Comment by ds5678** [comment]
I can only speculate.

**Comment by Virjoinga** [comment]
> I can only speculate.

Yeah it worked. Guess that folder did contain the old files>
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/13333983/AssetRipper.log)
