### ISSUE TITLE
[Bug]: Export doesn't create .cs files (files are there but they are dummy files)

### ISSUE THREAD

**Issue by andyrozman** [AssetRipper/AssetRipper#1099]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Harry Potter Wizards Unite

### Which Unity version did this occur on?

2018.4.24f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Export doesn't create .cs files (files are there but they are dummy files). I am new to this app and to Unity, so I might be missing something... Game is no longer available and I am trying to extract downloaded assets (I still have them on my old phone with which I played the game). 
I am not sure if game is Mono or Il2Cpp, but I think its IL2Cpp. 
I tried to export data on 2 different platforms with same results: Windows_x64 and Linux

### Relevant log output
System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 6.1.7601 Service Pack 1
System : Operating System: Windows 64 bit
System : AssetRipper Version: 0.3.4.0
System : AssetRipper Build Type: Release Published
System : UTC Current Time: Tue Nov 14 19:22:48 UTC 2023
System : UTC Compile Time: Tue Sep  5 05:23:26 UTC 2023
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : DefaultVersion: 0.0.0a0
General : ExportRootPath: C:\HPWU\_AAA\AssetRipper\Ripped
General : ExportDependencies: False
General : BundledAssetsExportMode: DirectExport
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Hybrid
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Decompile
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
General : EnablePrefabOutlining: False
General : EnableStaticMeshSeparation: False
General : IgnoreEngineAssets: False
General : Attempting to read files from C:\HPWU\map_avatar\30a8efee8b032c21e521ac0961ad587e\__data
Import : Game file '__data' has been found
Import : Mixed game structure has been found at C:\HPWU\map_avatar\30a8efee8b032c21e521ac0961ad587e\__data
Import : Files use the 'Unknown' scripting backend.
General : Finished reading files
General : Processing loaded assets...
Processing : Creating Scene Definitions
Processing : Main Asset Pairing
Processing : Lighting Data Assets
Processing : Reconstruct AnimatorController Assets
Processing : Reconstruct AudioMixer Assets
Processing : Editor Format Conversion
General : Finished processing assets
General : About to begin export to C:\HPWU\_Unpacked3\__data
General : Removing any files from a previous export...
Export : Attempting to export assets to C:\HPWU\_Unpacked3\__data...
Export : Starting export
Export : Game files have these Unity versions: 2018.4.24f1
Export : Exporting to Unity version 2018.4.24f1
Export : Preparing for export...
Export : Preparation complete. Starting to export now...
ExportProgress : Exporting 'map_avatar_interact_tl'
ExportProgress : Exporting 'ScriptExportCollection'
Export : Exporting scripts...
ExportProgress : Exporting 'map_avatar_flying_tl'
ExportProgress : Exporting 'AnimationPlayableAsset of map_player_walk_1mps_lfp'
ExportProgress : Exporting 'AnimationPlayableAsset of map_player_ride_broom'
ExportProgress : Exporting 'PlayerAvatar'
ExportProgress : Exporting 'PlayerAvatar'
ExportProgress : Exporting 'map_player_idle_wave'
ExportProgress : Exporting 'Timeline SFX Track'
ExportProgress : Exporting 'map_player_ride_broom'
ExportProgress : Exporting 'TimelineEventClip'
ExportProgress : Exporting 'AnimationPlayableAsset of map_player_idle_default'
ExportProgress : Exporting 'map_avatar_interact_done_event'
ExportProgress : Exporting 'map_avatar_walk_tl'
ExportProgress : Exporting 'map_avatar_idle_tl'
ExportProgress : Exporting 'PlayerAvatar'
ExportProgress : Exporting 'map_player_idle_default'
ExportProgress : Exporting 'TimelineSFXClip'
ExportProgress : Exporting 'PlayerAvatar'
ExportProgress : Exporting 'AnimationPlayableAsset of map_player_idle_wave'
ExportProgress : Exporting 'map_player_walk_1mps_lfp'
Export : Finished exporting assets
Export : Saving game assemblies...
Export : Finished post-export
General : Export Complete!

**Comment by ds5678** [comment]
So you want AssetRipper to export scripts even though none of files you provided contain code?

**Comment by andyrozman** [comment]
Sorry, I am very new to Unity and everything... I assumed that files would be part of asset itself (dll (or whatever binary) packed inside). But your reply makes me think that I need to look for separate file... Would that file be *.dll or could it be something else, but containing the .dll data? I have assets that I downloaded while playing the game (from Android/data/game/files/UnityCache/Shared folder) and I have last apk of the game (before it was shutdown).
Which location would contain the unity binary file?

**Comment by ds5678** [comment]
Go back to Discord.
