### ISSUE TITLE
[Bug]: Project keeps crashing

### ISSUE THREAD

**Issue by hedcreb** [AssetRipper/AssetRipper#1102]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Submission (part of the Dread X Collection 3) 
https://steamdb.info/app/1437500/

### Which Unity version did this occur on?

Unity 2019.4.0f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Unity project keeps crashing
![image](https://github.com/AssetRipper/AssetRipper/assets/118313518/bd871e23-de8a-45ca-b17b-ea2644e15c63)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/13363024/AssetRipper.log)

**Comment by ds5678** [comment]
That doesn't tell me anything.

**Comment by ds5678** [comment]
I am going to close this unless you can identify the source of the crash. I suspect it might be lighting data.
