### ISSUE TITLE
[Enhancement]: Download Detected Unity Version from Unity Hub URI

### ISSUE THREAD

**Issue by prandleman** [AssetRipper/AssetRipper#1110]
### Describe the new feature or enhancement

For the detected unity version the website had the URI pointing to [unityhub://2019.4.39f1/78d14dfa024b](unityhub://2019.4.39f1/78d14dfa024b) but [unityhub://2019.4.39f1](unityhub://2019.4.39f1) also seems to work. I tried this one on that I already had installed, so not sure in the case of no install.

**Comment by ds5678** [comment]
Approved!

This seems simple enough. Thank you for the suggestion.
