### ISSUE TITLE
[Bug]:  is likely encrypted or using custom compression

### ISSUE THREAD

**Issue by hliu00** [AssetRipper/AssetRipper#1115]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://apkcombo.com/zh/%E7%A5%9E%E5%AF%B5%E5%A5%87%E7%B7%A3-%E6%B8%85%E6%96%B0%E5%8F%A4%E9%A2%A8%E4%BF%AE%E4%BB%99%E5%9B%9E%E5%90%88%E5%88%B6%E6%89%8B%E9%81%8A/com.xfhxtw.gp/

### Which Unity version did this occur on?

2020.3.18f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

When you click "Open Folder" an error occurs

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/13454875/AssetRipper.log)

**Comment by hliu00** [comment]
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/13454871/AssetRipper.log)

**Comment by ds5678** [comment]
And why exactly do you think this is a bug?
