### ISSUE TITLE
[Other]: Misleading build instruction

### ISSUE THREAD

**Issue by rndtrash** [AssetRipper/AssetRipper#1123]
### Describe the issue

The [Compiling](https://github.com/AssetRipper/AssetRipper/blob/2b9db3e89a44eb719aa92fb5542d8bbc9a77cebf/.github/CONTRIBUTING.md#compiling) section of CONTRIBUTING.md says that I need to change my working directory to `Source/AssetRipper.GUI.Electron`, but the `start.bat` file is actually located in `Source/AssetRipper.GUI.Free`.

Needless to say, running `electronize start /PublishSingleFile false /PublishReadyToRun false` in `Source/AssetRipper.GUI.Electron` does not work (unable to find electron.manifest.json), but it works in the `Source/AssetRipper.GUI.Free` folder.

![image](https://github.com/AssetRipper/AssetRipper/assets/6745157/62725a50-e157-4b45-8928-95875bfe9132)

OS: Ubuntu 23.10
.NET SDK: 8.0

**Comment by ds5678** [comment]
I'm sorry about that. The user interface has gone through a lot of changes recently, so the directions accidentally got outdated.
