### ISSUE TITLE
[Bug]: Decompilation error (Read ... but expected ... for asset type Sprite/VFXManager. V: 2023.1.2f1 P: Switch N:) (Error during reading of asset type Physics2DSettings)

### ISSUE THREAD

**Issue by GdGohan** [AssetRipper/AssetRipper#1139]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Koumajou Remilia 2: Strangers Requiem

### Which Unity version did this occur on?

2023.1.2f1

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

Sprite corruption,distortion

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/13746015/AssetRipper.log)

**Comment by ds5678** [comment]
This won't happen on newer versions of AssetRipper.

**Comment by GdGohan** [comment]
> Yes, I'm on the latest release of AssetRipper.
i´m using (0.3.0.4)

**Comment by ds5678** [comment]
0.3.4.0 is the latest stable release, but there are some prereleases which include newer versions of Unity.

**Comment by ds5678** [comment]
https://github.com/AssetRipper/AssetRipper/releases
