### ISSUE TITLE
[Bug]: Dummy class.

### ISSUE THREAD

**Issue by GdGohan** [AssetRipper/AssetRipper#1140]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Koumajou Remilia 2: Strangers Requiem

### Which Unity version did this occur on?

2023.1.2f1

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

all scripts:Dummy class.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/13747155/AssetRipper.log)

**Comment by ds5678** [comment]
> Import : Mixed game structure has been found at
> Import : Files use the 'Unknown' scripting backend.

Your files were not recognized as a PC game

**Comment by GdGohan** [comment]
> > Import : Mixed game structure has been found at
> > Import : Files use the 'Unknown' scripting backend.
> 
> Your files were not recognized as a PC game

switch files:(

**Comment by ds5678** [comment]
Then, you gave AssetRipper the wrong folder. You need the one that contains exefs and romfs.
