### ISSUE TITLE
[Bug]: Vertex color loss of color attributes on the Mesh

### ISSUE THREAD

**Issue by promiselonely** [AssetRipper/AssetRipper#1145]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

2021.3.23f1c1

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

When I export with Mesh GLB and then import it into Blender, the vertex colors(color attributes) are lost
![20231227201124](https://github.com/AssetRipper/AssetRipper/assets/3787092/031c90a1-9945-4740-ac64-6d85f9cae4bb)
Please tell me how to fix it，thanks

**Comment by promiselonely** [comment]
static mesh separation is disabled,It looks like#887

**Comment by ds5678** [comment]
Have you tried version 1.0.0?

**Comment by promiselonely** [comment]
I tried again with 1.0.0 and the result was still the same. Everything without color attributes (vertex colors) is correct, including texture materials

Here are my test results and content:

![20231227215521](https://github.com/AssetRipper/AssetRipper/assets/3787092/8c9204f8-afa8-4683-850c-06bffcb2d0df)
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/13779045/AssetRipper.log)
[f0b1199b3b335a595bbb472e7dcc4028.zip](https://github.com/AssetRipper/AssetRipper/files/13779046/f0b1199b3b335a595bbb472e7dcc4028.zip)

**Comment by ds5678** [comment]
I encourage you to investigate this on your own.

https://github.com/AssetRipper/AssetRipper/tree/7a9f5982044a2faa91113e22fa1c097a14da6d5d/Source/AssetRipper.Export.UnityProjects/Meshes
https://github.com/AssetRipper/AssetRipper/tree/7a9f5982044a2faa91113e22fa1c097a14da6d5d/Source/AssetRipper.Export.UnityProjects/Models

**Comment by promiselonely** [comment]
ok,i'm try it...T.T

**Comment by ds5678** [comment]
What did you discover?
