### ISSUE TITLE
[Bug]: Weird texture issue

### ISSUE THREAD

**Issue by Apache-Act1** [AssetRipper/AssetRipper#1166]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://www.meta.com/experiences/6704410679667175/

### Which Unity version did this occur on?

2022.3.3f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Super weird issue, textures are doing whatever this is. (Im using static mesh seperation) (I even tried exporting to a fbx then putting into another project then this still happens) 

![image](https://github.com/AssetRipper/AssetRipper/assets/157150260/328d575f-7156-4a93-85eb-f52f3874005b)

### Relevant log output

No log. Visual issue in project output

**Comment by ds5678** [comment]
I assume, since you mentioned static mesh separation, that this mesh was part of a static mesh?

**Comment by Apache-Act1** [comment]
Yea. I found a way to fix it though. You must change the mesh filter to the mesh on the mesh-collider

**Comment by ds5678** [comment]
Static mesh separation has since been improved in the premium edition of AssetRipper, which will be released soon. This issue is likely not relevant beyond the outdated code in the free edition.
