### ISSUE TITLE
[Other]: 

### ISSUE THREAD

**Issue by GhostIceBunny** [AssetRipper/AssetRipper#1167]
### Describe the issue

When I try to use it it shows that my windows security stopped me from dragging the file into the asset ripper saying it was a internet security issue

**Comment by GhostIceBunny** [comment]
there isnt a log

**Comment by GhostIceBunny** [comment]
it only shows this 
![image_2024-01-22_092652956](https://github.com/AssetRipper/AssetRipper/assets/100446887/e5698095-d435-4f34-817c-d1e7dcd102be)

**Comment by ds5678** [comment]
I don't understand what you want. Just press OK.
