### ISSUE TITLE
[Enhancement]: Unknown files or custom type files that can't be decrypted and loaded, is it possible to skip these error files and let the program continue to execute?

### ISSUE THREAD

**Issue by byshiyi** [AssetRipper/AssetRipper#1168]
### Describe the new feature or enhancement

Unknown files or custom type files that can't be decrypted and loaded, is it possible to skip these error files and let the program continue to execute?
99.9% of the resources can be decrypted, but it's the 0.01% that makes the whole decryption unworkable.
![QQ截图20240123144218](https://github.com/AssetRipper/AssetRipper/assets/10216522/93ab5759-2b33-48d9-a1ab-c665179f0510)

**Comment by byshiyi** [comment]
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/14019504/AssetRipper.log)
Okay, it's uploaded.

**Comment by ds5678** [comment]
> 99.9% of the resources can be decrypted, but it's the 0.01% that makes the whole decryption unworkable.

What makes you so sure about this?

**Comment by byshiyi** [comment]
Since I'm using AssetStudio, DexUnity has also opened these files and they are openable. But it also prompts an error report, but not all files are not displayed.

**Comment by byshiyi** [comment]
Being a game developer myself, I write similar functions, and since they are not part of Unity itself, they are read with errors.

**Comment by ds5678** [comment]
Please use a newer version of AssetRipper and submit a new log.

**Comment by byshiyi** [comment]
The log has been uploaded above, and the version used is 0.3.4

**Comment by byshiyi** [comment]
I use 1.0.4 and the same log is saved.
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/14093665/AssetRipper.log)

**Comment by ds5678** [comment]
What game is this?
