### ISSUE TITLE
[Question]: What about containers? Unable to export to png when files are in a container

### ISSUE THREAD

**Issue by niquedegraaff** [AssetRipper/AssetRipper#1170]
### Question

I'm trying to export all textures from a game, but when loading all the resources and asset files, I noticed that when expanding the tree, and selecting 'containers', there are no containers. Yet the files are stating they are in container and cannot be exported (they get error` "Error exporting an asset (File ID 41, Path ID 379): Unable to deserialize the asset."`
![image](https://github.com/AssetRipper/AssetRipper/assets/116283/ca3ba130-6580-4f46-90f8-3c942c492597)
![image](https://github.com/AssetRipper/AssetRipper/assets/116283/3c476548-6db9-4554-9729-db48e649ec27)

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by ds5678** [comment]
I think you posted on the wrong repository.
