### ISSUE TITLE
[Bug]: all my files are gone

### ISSUE THREAD

**Issue by DestinyAwaits23** [AssetRipper/AssetRipper#1172]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Doesn't matter

### Which Unity version did this occur on?

Doesn't matter

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

All of my files are gone and my system restore is no longer working.

**Comment by ds5678** [comment]
Duplicate of #1163
