### ISSUE TITLE
[Enhancement]: Save Settings Locally

### ISSUE THREAD

**Issue by TridleGamesSV** [AssetRipper/AssetRipper#1181]
## Issue Description
 Currently, every time the program is closed, all the user's settings are reset, and they must be manually inputted upon reopening.

## Proposed Feature
To enhance the user experience, a feature should be implemented that saves the selected settings locally.

**Comment by ds5678** [comment]
Implemented in f52342bd1dcca638716546fdb1d2725ba9607632
