### ISSUE TITLE
[Bug]: Case Sensitivity breaks on Linux

### ISSUE THREAD

**Issue by Martmists-GH** [AssetRipper/AssetRipper#1182]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Linux x64

### Which game did this occur on?

Pokemon Brilliant Diamond

### Which Unity version did this occur on?

2019.4.27f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Unity expects certain files in `sharedassets/games/...` but AssetRipper places them in `SharedAssets/Games/...`, and on Linux these are different folders since it's case-sensitive.

![image](https://github.com/AssetRipper/AssetRipper/assets/16361449/ab4c63ea-dfe1-4472-8654-142dcd399770)

**Comment by ds5678** [comment]
> Unity expects certain files in sharedassets/games/... but AssetRipper places them in SharedAssets/Games/..., and on Linux these are different folders since it's case-sensitive.

That's the path used in the game files.

**Comment by ds5678** [comment]
So what exactly do you want AssetRipper to do?

**Comment by Martmists-GH** [comment]
ideally it'd convert everything to lowercase or the first type of capitalization it finds, the latter being how windows would handle it

**Comment by ds5678** [comment]
The latter is computationally expensive for case sensitive file systems. Both are cumbersome to implement due the large of places that AssetRipper writes to the disk.

I want to close this. I think a better solution would be for you to write a simple script that converts the project to your desired capitalization. It would be cleaner, more efficient, and more stable than me attempting a solution in AssetRipper.
