### ISSUE TITLE
[Bug]: Can't extract files from a game with AssetRipper

### ISSUE THREAD

**Issue by Forcica** [AssetRipper/AssetRipper#1189]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

One Punch Man World (PC Version)

### Which Unity version did this occur on?

2019.4.40f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I'm trying to extract the files for a Unity game from the AssetBundles folder, but they're encrypted and have no extension at the end. Is there any way to decrypt them easily so that AssetRipper can be used with this game?

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/14154298/AssetRipper.log)

**Comment by DavidLeBonk** [comment]
If the game is encrypted you would need to find, wait for or develop a tool specifically to extract from this game. Asset ripper doesn't have circumventions for encrypted games or custom unity builds.

**Comment by ds5678** [comment]
I just took a look at your log. It's likely either encryption or custom bundle compression.
