### ISSUE TITLE
Lightmaps corrupt as yaml.

### ISSUE THREAD

**Issue by CanyonsEcho** [AssetRipper/AssetRipper#1192]
I have used AssetRipper since about april, and ever since the lightmaps went to exporting as yaml, they are extremely bright and very easially corrupt. Please add an option to switch between the old PNG lightmap exports and yaml exports.

**Comment by ds5678** [comment]
Do you have a before and after file diff for a corrupted file?

**Comment by CanyonsEcho** [comment]
heres before the corruption
![image](https://github.com/AssetRipper/AssetRipper/assets/130379038/26e4ec6c-66eb-4e94-a9d5-a9ec73c88a0c)
and heres after
![image](https://github.com/AssetRipper/AssetRipper/assets/130379038/ea8b589c-0823-442d-886f-96738921c605)
changing something as small as the lightmap quality can completely corrupt them, so can you please bring back png lightmaps, they may be a bit less quality but its better than having something that would burn your eyes out

**Comment by ds5678** [comment]
I want a file diff, eg with [WinMerge](https://winmerge.org/).

**Comment by ds5678** [comment]
I am confused about your experience because other users have reported yaml to be a superior format for storing the lighting data. Are you bumping the Unity version? That would explain your file corruption.

**Comment by ds5678** [comment]
Closed because of insufficient information from the user
