### ISSUE TITLE
[Question]: Why???

### ISSUE THREAD

**Issue by officialtoofoo** [AssetRipper/AssetRipper#1196]
### Question

It Says It's A Virus
![image](https://github.com/AssetRipper/AssetRipper/assets/145826070/db806ee7-5429-42d7-8da8-cd4cffd58670)

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by ds5678** [comment]
It's a false positive.
