### ISSUE TITLE
[Enhancement]: Recover Mirror and TimeScale properties for BlendTrees

### ISSUE THREAD

**Issue by FACS01-01** [AssetRipper/AssetRipper#1198]
### Describe the new feature or enhancement

When this properties are ripped they are always set to their default value (m_Mirror to false, m_TimeScale to 1).
This properties are allocated inside the BlendTree's ChildMotions (m_Childs field).
I've experienced this with Unity 2019 bundles and 2022 bundles.
With those properties fixed, BlendTree recovery will be complete and ripped AnimatorControllers will be more useful.

An AnimatorController I made with 3 BlendTrees:
![original blendtrees](https://github.com/AssetRipper/AssetRipper/assets/75183551/9479eb18-99c6-425f-8715-02bc9895bfb9)

After ripping:
![ripped blendtrees](https://github.com/AssetRipper/AssetRipper/assets/75183551/20c51847-5531-43b3-9e79-b1898a7279be)

[blendtree test.zip](https://github.com/AssetRipper/AssetRipper/files/14234139/blendtree.test.zip)

**Comment by ds5678** [comment]
Mirror should already be recovered.

https://github.com/AssetRipper/AssetRipper/blob/12c267581b287755c7ff78e76ceaa134a52cfe3c/Source/AssetRipper.Processing/AnimatorControllers/VirtualAnimationFactory.cs#L143

**Comment by FACS01-01** [comment]
> Mirror should already be recovered.
> 
> https://github.com/AssetRipper/AssetRipper/blob/12c267581b287755c7ff78e76ceaa134a52cfe3c/Source/AssetRipper.Processing/AnimatorControllers/VirtualAnimationFactory.cs#L143

Cloned the repo today for testing. Seems at that point, `node.Mirror` is always `False`.

**Comment by FACS01-01** [comment]
Opened a pull request to implement/fix this issue: https://github.com/AssetRipper/AssetRipper/pull/1201
