### ISSUE TITLE
[Bug]: i cant click on open file or open folder when i do nothing happens

### ISSUE THREAD

**Issue by sophienix** [AssetRipper/AssetRipper#1211]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

None

### Which Unity version did this occur on?

None

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

All i did was extracted the file then open it. I dont see a .log but I do see a .txt file

### Relevant log output

System : AssetRipper
System : System Version: Microsoft Windows NT 10.0.19045.0
System : Operating System: Windows x64
System : AssetRipper Version: 1.0.6.0
System : AssetRipper Build Type: Release Published
System : UTC Current Time: Wed Feb 21 20:00:51 UTC 2024
System : UTC Compile Time: Sun Feb  4 20:15:35 UTC 2024

**Comment by sophienix** [comment]
There is no .log file it dosent show I know I am talking to a bot but just top show / clarify 
![image](https://github.com/AssetRipper/AssetRipper/assets/74495871/48f5efc5-4d42-41a6-8622-ce03b1860085)

**Comment by ds5678** [comment]
Can you take a video? For example, sharex allows you to record your screen.

**Comment by sophienix** [comment]
> Can you take a video? For example, sharex allows you to record your screen.

i use obs but sure

**Comment by sophienix** [comment]
Never mind it opens with the software I thought my browser opens file explorer my mistake
