### ISSUE TITLE
[export]: missing files 

### ISSUE THREAD

**Issue by ankumc** [AssetRipper/AssetRipper#1225]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

granny 2

### Which Unity version did this occur on?

2019.2.11f

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

missing files

**Comment by ds5678** [comment]
And what exactly is missing?

**Comment by ankumc** [comment]
> And what exactly is missing?

some game files like textures scripts and audio are missing

**Comment by ds5678** [comment]
Can you be more specific and explain how you know they're missing.

**Comment by ankumc** [comment]
> Can you be more specific and explain how you know they're missing.

I tried to export granny with different ripper

**Comment by ds5678** [comment]
Can you name a specific asset that is missing?

**Comment by ds5678** [comment]
Closed because of inactivity
