### ISSUE TITLE
[Enhancement]: Hybrid Script Exporter

### ISSUE THREAD

**Issue by ds5678** [AssetRipper/AssetRipper#123]
### Describe the new feature or enhancement

In 2a043e7fb7091caa526566029cb5b876a44e1fe9, I added an experimental dll script exporter. Rather than decompiling scripts with the ILSpy decompiler, this exporter writes the AssemblyDefinitions into dll assemblies. This:
* Is much faster than decompiling
* Exports without compile errors

However, I discovered a limitation. Assemblies with special names, such as `Assembly-CSharp.dll`, get overruled when Unity builds its scripts. This will need to be handled:
* Non-special assemblies can be saved as dll files. The experimental exporter applies perfectly here.
* Special assemblies have to be decompiled. The original exporter should apply. Unfortunately, this means that script export will still take up a significant portion of export time.
* Guid's must be carefully dealt with since the experimental exporter changes MonoScript guid's. This needs to be disabled for MonoScripts from special assemblies.

Other issues you may encounter:
* There may be additional reference assemblies that need excluded. Unity can crash when trying to load a reference assembly. You can just add them to the list. Be careful not to falsely identify a reference assembly.
* Any solution to this must work for both Mono and IL2Cpp games. Copying Mono assemblies from the Managed folder is not a viable solution because that can't work on IL2Cpp games.

**Comment by CyberAndrii** [comment]
I had this issue too. From what I figured out it seems that Unity doesn't support the `-` symbol in the assembly name. I was renaming it to `_Assembly_CSharp` (using Mono.Cecil) and it was importing fine, but at runtime, you will get assembly not found exceptions and missing components. You will need to use `TypeForwardedFromAttribute` or assembly resolver, but I haven't tried them.

**Comment by ds5678** [comment]
@CyberAndrii Thank you for your interest in this issue. It's nice to see you active again. If this is something you feel strongly about, I would be more than happy to let you handle this while I focus on other areas of development.

**Comment by Raicuparta** [comment]
How do I actually selet these script export modes? I see there are currently three of them: https://assetripper.github.io/AssetRipper/api/AssetRipper.Library.Configuration.ScriptExportMode.html

But I see no way to actually pick between them?

**Comment by ds5678** [comment]
> How do I actually select these script export modes? I see there are currently three of them: https://assetripper.github.io/AssetRipper/api/AssetRipper.Library.Configuration.ScriptExportMode.html
> 
> But I see no way to actually pick between them?

Only decompiled export is stable enough to give users. Hybrid is not implemented and TotalDllExport just doesn't work.

**Comment by Raicuparta** [comment]
@ds5678 thanks for the clarification. I noticed that I can just copy and paste the DLLs to a Unity project and i can use them as scripts, at least in the editor. Is there no current way to export the scene hierarchy with DLLs only, while keeping the script references in the scene objects? I only need it to look right in the editor, don't really care about it actually running.

**Comment by ds5678** [comment]
I haven't had much time to focus on this section of the project, but I imagine I'm going to do 4 levels when I get around to it:
1. Full decompilation, like now
2. Hybrid
3. All dll's, but with assembly renaming
4. All dll's, no renaming (For Thunderkit)

**Comment by arcomsians** [comment]
![issue](https://user-images.githubusercontent.com/116951660/198834043-ce6e74c4-c223-4036-8859-b4ed379a75a0.PNG)
why script function is empty use AssetRipper

**Comment by Mustafa-Agha** [comment]
I'm facing the same problem

```
using UnityEngine;
using UnityEngine.UI;

public class logo : MonoBehaviour
{
	private bool loading;

	private Transform loadingRoundObjTransform;

	private Image loadingProgressImageComponenet;

	private AsyncOperation asyncLoading;

	private float loadingSmoothVel;

	private float loadingSmoothValue;

	private RectTransform logoRectTransform;

	private CanvasGroup blackFadeCanvasGroupComp;

	private float logoAnimValue;

	private float logoAnimVel;

	private float logoAnimTarget;

	private float logoAnimTime;

	private bool logoAnimScale;

	private float logoScaleExtraVal;

	private void Start()
	{
	}

	private void Update()
	{
	}

	private void startLoading()
	{
	}

	private void loadLevelActivate()
	{
	}

	private void loadLevelInvoke()
	{
	}

	private void activateLoadedScene()
	{
	}
}

```

Have you managed to solve this problem, or should I change some settings to make this work?

**Comment by ds5678** [comment]
@arcomsians @Mustafa-Agha your empty script experiences are unrelated to this issue.
