### ISSUE TITLE
[Bug]: most textures dont rip on 2022.3.2

### ISSUE THREAD

**Issue by hgamingyt** [AssetRipper/AssetRipper#1230]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Gorilla Tag - [SteamDB](https://steamdb.info/app/1533390/)

### Which Unity version did this occur on?

2022.3.2f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

whenever i rip the game almost all materials are blank and the textures dont export (some do though)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/14470451/AssetRipper.log)

**Comment by hgamingyt** [comment]
![image](https://github.com/AssetRipper/AssetRipper/assets/81877937/332e75d9-0c03-4f7c-a846-df20d74a3afb)
this is what it looks like btw

**Comment by ds5678** [comment]
I am unable to investigate this in depth for the near future, but I suspect it may be related to an unsupported texture type. My intuition tells me that this is probably ASTC HDR. You might be able to check in the AssetRipper UI.

**Comment by hgamingyt** [comment]
> I am unable to investigate this in depth for the near future, but I suspect it may be related to an unsupported texture type. My intuition tells me that this is probably ASTC HDR. You might be able to check in the AssetRipper UI.

all good, thanks!

**Comment by XymbX** [comment]
hgamingyt. Saying you ripped gorilla tag its all just one texture. so it might just be that one texture that is broken

**Comment by AppCenterGames** [comment]
i know this was a while ago but it turns out its the shader, for some reason the shader is just broken.

**Comment by ds5678** [comment]
How big is this texture?

**Comment by hgamingyt** [comment]
> How big is this texture?

so i found out that it's not the texture, it's the shader. almost all shaders that are being ripped are pretty much dummy shaders.

**Comment by ds5678** [comment]
That's not a bug. That's how they are supposed to be. You can try using the decompilation option, but it's not maintained.
