### ISSUE TITLE
[Bug]: Missing references to primitive meshes

### ISSUE THREAD

**Issue by FACS01-01** [AssetRipper/AssetRipper#1233]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

2022.3.6f1

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

When ripping a standalone assetbundle, object references to the primitive meshes (Sphere, Capsule, Cylinder, Cube, Plane, Quad) are missing (and replaced by GUID=0000000deadbeef15deadf00d0000000, FileID=4300000). I think those are allocated in Unity built-in resources.

test bundle: [default meshes.zip](https://github.com/AssetRipper/AssetRipper/files/14486605/default.meshes.zip)

**Comment by FACS01-01** [comment]
For reference, the PPtr for this meshes inside the bundle are:
Cube: `{m_FileID: 1, m_PathID: 10202}`
Cylinder: `{m_FileID: 1, m_PathID: 10206}`
Sphere: `{m_FileID: 1, m_PathID: 10207}`
Capsule: `{m_FileID: 1, m_PathID: 10208}`
Plane: `{m_FileID: 1, m_PathID: 10209}`
Quad: `{m_FileID: 1, m_PathID: 10210}`

The PPtrs in Editor follow the pattern `{fileID: m_PathID, guid: 0000000000000000e000000000000000, type: 0}`

**Comment by ds5678** [comment]
Can this be closed in favor of #1271? This issue sounds like a subset of that one.

**Comment by FACS01-01** [comment]
Yeah, issues https://github.com/AssetRipper/AssetRipper/issues/1233 and https://github.com/AssetRipper/AssetRipper/issues/1253 can be closed in favor of the Enhancement.
