### ISSUE TITLE
[Bug]: Throw Exception When Export in Fmod

### ISSUE THREAD

**Issue by chinhlv321** [AssetRipper/AssetRipper#1234]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Hexa Sort

### Which Unity version did this occur on?

2021.3.30f

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

![image](https://github.com/AssetRipper/AssetRipper/assets/31094907/94586336-e076-49d6-a803-4f41378ee843)

**Comment by ds5678** [comment]
Make a bug report at Fmod5Sharp
