### ISSUE TITLE
[Bug]: Albion online

### ISSUE THREAD

**Issue by KOT9652** [AssetRipper/AssetRipper#1243]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Albion online (on Steam) 
https://steamdb.info/app/761890/

### Which Unity version did this occur on?

2021.3.23f1 
![image](https://github.com/AssetRipper/AssetRipper/assets/163320227/5fa80a05-fcf8-479d-8ac2-97c01eabb3df)

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

I get the error shown in "AssetRipper.log" tried to copy game and remove files that the error was about but got warnings shown in "assetripper2.log"

game is Mono according to "assetripper2.log"
but there is folder "il2cpp_data" in game files

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/14590062/AssetRipper.log)
[AssetRipper2.log](https://github.com/AssetRipper/AssetRipper/files/14590194/AssetRipper2.log)

**Comment by ds5678** [comment]
Choose either `game` or `staging`. They're separate Unity games.
