### ISSUE TITLE
[Bug]: Standoff 2 Animation Error

### ISSUE THREAD

**Issue by Wanja01YT** [AssetRipper/AssetRipper#1246]
### Are you on the latest version of AssetRipper?

No, I need to download a newer version and try again.

### Which release are you using?

Unselected

### Which game did this occur on?

Standoff 2 (0.28.0)
https://play.google.com/store/apps/details?id=com.axlebolt.standoff2

### Which Unity version did this occur on?

2022.3.19f1

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

When reaching level51 and level52, AssetRipper outputs this error and closes. (Ignore the missing assetbundles, they are downloaded separately and not needed for decompilation)

### Relevant log output

System : AssetRipper
System : System Version: Microsoft Windows NT 10.0.19045.0
System : Operating System: Windows x64
System : AssetRipper Version: 1.0.9.0
System : AssetRipper Build Type: Release Published
System : UTC Current Time: Fri Mar 15 11:23:33 UTC 2024
System : UTC Compile Time: Sat Mar  2 19:06:13 UTC 2024
General : Configuration Settings:
General : ExportRootPath: I:\AssetRipper_win_x64 (1.0.9)\Ripped
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : DefaultVersion: 0.0.0a0
General : BundledAssetsExportMode: GroupByAssetType
General : EnablePrefabOutlining: False
General : EnableStaticMeshSeparation: True
General : EnableAssetDeduplication: True
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Hybrid
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
Import : Attempting to read files from J:\New folder (5)\New folder (2)
Import : Asset bundle 'data' has been found

[many assetbundles found, had to remove this part since it was longer than the max character limit for github]

Import : Mixed game structure has been found at J:\New folder (5)\New folder (2)
Import : Files use the 'Unknown' scripting backend.
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'globalgamemanagers.assets' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'sharedassets0.assets' wasn't found
Import : Finished reading files
Processing : Processing loaded assets...
Processing : Creating Scene Definitions
Processing : Main Asset Pairing
Processing : Reconstruct AnimatorController Assets
Processing : Reconstruct AudioMixer Assets
Processing : Editor Format Conversion
[Error] : System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Internal.Runtime.CompilerHelpers.ThrowHelpers.ThrowIndexOutOfRangeException() + 0x24
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.AddTransformCurve(Single, TransformType, ReadOnlySpan`1, ReadOnlySpan`1, ReadOnlySpan`1, Int32, String) + 0xbad
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessConstant(IConstantClip, Int32, Single) + 0x258
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessInner() + 0x12b
   at AssetRipper.Processing.Editor.EditorFormatProcessor.Convert(IUnityObjectBase) + 0x1a3
   at AssetRipper.Processing.Editor.EditorFormatProcessor.Process(GameData) + 0x17b
   at AssetRipper.Export.UnityProjects.ExportHandler.Process(GameData) + 0xa2
   at AssetRipper.GUI.Web.GameFileLoader.LoadAndProcess(IReadOnlyList`1) + 0x4f
   at AssetRipper.GUI.Web.Pages.Commands.LoadFolder.<AssetRipper-GUI-Web-Pages-ICommand-Execute>d__0.MoveNext() + 0x175
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb2
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4b
   at AssetRipper.GUI.Web.Pages.Commands.<HandleCommand>d__6`1.MoveNext() + 0xaf
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb2
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4b
   at AssetRipper.GUI.Web.ErrorHandlingMiddleware.<InvokeAsync>d__0.MoveNext() + 0x9f

**Comment by ds5678** [comment]
cc: @FACS01-01

**Comment by FACS01-01** [comment]
The bug happens on `sharedassets51.assets > LabGlitch (AnimationClip)`, and its due to: 
https://github.com/AssetRipper/AssetRipper/blob/ef00ea8494ac685b27f18b648b6387084f08b9ae/Source/AssetRipper.SourceGenerated.Extensions/StreamedClipExtensions.cs#L9-L12
The correct output for this method should have been 1 in this case, but currently is returning 0.
Bundle is Unity version 2022.3.19f1, so its returning `clip.CurveCount_UInt16`, but both Uints are returning 0 anyways.
Inspecting that AnimationClip with UABEA, I see the value in `m_MuscleClip.m_Clip.data.m_StreamedClip.data.curveCount` is 65536 (of Type `uint`).

**Comment by Wanja01YT** [comment]
> The bug happens on `com.axlebolt.standoff2.obb\assets\bin\Data\data.unity3d > sharedassets51.assets > LabGlitch`, and its due to: 
> 
> https://github.com/AssetRipper/AssetRipper/blob/ef00ea8494ac685b27f18b648b6387084f08b9ae/Source/AssetRipper.SourceGenerated.Extensions/StreamedClipExtensions.cs#L9-L12
> 
> The correct output for this method should have been 1 in this case, but currently is returning 0.
> 
> Bundle is Unity version 2022.3.19f1, so its returning `clip.CurveCount_UInt16`, but both Uints are returning 0 anyways.
> 
> Inspecting that AnimationClip with UABEA, I see the value in `m_MuscleClip.m_Clip.data.m_StreamedClip.data.curveCount` is 65536 (of Type `uint`). 

So does this mean an issue on the developer side, an issue with the game engine or a new bug in Assetripper?

**Comment by FACS01-01** [comment]
> So does this mean an issue on the developer side, an issue with the game engine or a new bug in Assetripper?

Not sure wich really

**Comment by DatTaiwanGuy** [comment]
both i guess....

**Comment by unbhopper** [comment]
I also encountered this error when unpacking the archive of this game.
Referring to @FACS01-01 answer, I decided to replace it
https://github.com/AssetRipper/AssetRipper/blob/ef00ea8494ac685b27f18b648b6387084f08b9ae/Source/AssetRipper.SourceGenerated.Extensions/StreamedClipExtensions.cs#L11
with `return 0` thinking that this would work.
It didn't work and then I downloaded the source code and found an error on `line 269` of the `AnimationClipConverter.cs` file. The program was trying to get the z-axis by getting an element from the array by index but it can't and throws `Index was outside the bounds of the array`, I think. I just set `float z =` on `line 269` to `0` and it worked, no more errors. This will have a impact for exported animations may be, but in my case they were unimportant and I got all that I need with this solution.

**Comment by FACS01-01** [comment]
> I also encountered this error when unpacking the archive of this game. Referring to @FACS01-01 answer, I decided to replace it

The code I quoted wasn't a solution to implement, I just highlighted the problem.

Because `CurveCount(this IStreamedClip clip)` is returning 0 instead of 1, when analizing `Constant Curves` it starts iterating from curve binding 0 instead of 1. The Constant data array has only 3 elements. Binding 0 being not a Transform type advances the Constant data array by 1, then when analizing Binding 1, that is a Transform type (Translation) will try to get 3 more elements from the Constant data array, leading to a crash.

**Comment by ds5678** [comment]
@thegu5 if that's not this game, make a new issue.

**Comment by Wanja01YT** [comment]
Issue still persists with the game on versions 0.29.0 - 0.29.3

**Comment by FACS01-01** [comment]
Just tested Standoff 2 v0.29.3 with latest AssetRipper and didn't get any errors

**Comment by Wanja01YT** [comment]
> Just tested Standoff 2 v0.29.3 with latest AssetRipper and didn't get any errors

Great news! I'd test with the latest version (0.31.1) just to make sure before closing this issue

**Comment by ds5678** [comment]
@Wanja01YT did you test?

**Comment by Wanja01YT** [comment]
@ds5678 Tested AssetRipper Free v1.1.8 with Standoff 2 v0.31.1, no AnimationClip issues during import. The issue seems to be fixed.

**Comment by ds5678** [comment]
Thank you for testing
