### ISSUE TITLE
[Bug]: Game Preview Black on EVERY EXPORT

### ISSUE THREAD

**Issue by Zekeakers1Gaming** [AssetRipper/AssetRipper#1260]
### Are you on the latest version of AssetRipper?

No, I need to download a newer version and try again.

### Which release are you using?

Unselected

### Which game did this occur on?

RETRY 1.5.0 apk

### Which Unity version did this occur on?

Any

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

The game preview is just black but the editor preview is fine and so is the game-ish

**Comment by ds5678** [comment]
Maybe a rendering pipeline issue?

**Comment by ds5678** [comment]
This is unlikely to be an AssetRipper issue. If you discover otherwise, feel free to reopen it.
