### ISSUE TITLE
The world is dark and the scripts don't work (Update: Granny Source Code Here).

### ISSUE THREAD

**Issue by Vexxus1** [AssetRipper/AssetRipper#1261]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Granny

### Which Unity version did this occur on?

2022.3.22f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Basically I decompiled the game and extracted it into unity, Then I fixed all 1057 Errors and I went to run it and I don't think the scripts work and uTinyRipper (Does not work anymore) in videos looked like it fixed the lighting and animations and not much errors in the scripts. While this one is the opposite, Idc about the lighting and the animations (Kinda Do) I just care about the functionally and me not having a plain black screen every time. 

### Relevant log output

Is not needed.

**Comment by Vexxus1** [comment]
I'll just try with an apk and see if the works

**Comment by Vexxus1** [comment]
> I'll just try with an apk and see if the works

Nvm Its the same

**Comment by ds5678** [comment]
AssetRipper was originally a fork of uTinyRipper, so any functionality there still likely exists in AssetRipper.

**Comment by ds5678** [comment]
Script errors are normal.

**Comment by ds5678** [comment]
Black screen might be caused by shaders or your rendering pipeline.

**Comment by ds5678** [comment]
Lighting and animations should be better than uTinyRipper.

**Comment by Vexxus1** [comment]
Interesting

**Comment by Vexxus1** [comment]
I noticed that people might have been playing a older version that weren't complex

**Comment by Vexxus1** [comment]
> Lighting and animations should be better than uTinyRipper.

Tysm

**Comment by Vexxus1** [comment]
But is the pipeline the decompiler's fault or unity's?

**Comment by Vexxus1** [comment]
Now this information I regret not saving while undoing 1000 errors

But when I did the play buttons didn't work, Why?

I mean there were a heap of warnings when I pressed play, So if you want me to show you one of them then I will.

**Comment by Vexxus1** [comment]
Well here is the video I got interested in:
https://www.youtube.com/watch?v=EJdAcOqHcws

**Comment by Vexxus1** [comment]
Wait... He was using granny 1.7, Probably at the time it weren't in iL2CPP, I have hope now.

**Comment by Vexxus1** [comment]
Yes!

I managed to decompile the Source Code 100% by downloading Granny 1.7 apk then decompiling it and got its source code with 0 iL2CPP encoding, Issue Closed

**Comment by Vexxus1** [comment]
I'll leave this open for people
