### ISSUE TITLE
[Bug]: TextMeshPro

### ISSUE THREAD

**Issue by Vexxus1** [AssetRipper/AssetRipper#1263]
### Are you on the latest version of AssetRipper?

Yes

### Which release are you using?

Windows x64

### Which game did this occur on?

All the games that are Mono

### Which Unity version did this occur on?

Happens on Every Editor 

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Ahm, So last time I could not get the source code and that was solved, But when I put the asset folders into unity it didn't complain about the scripts.. It complained about the TextMeshPro Scripts, and I have no idea how to fix it.  

### Relevant log output

Not Needed.

**Comment by Vexxus1** [comment]
Do you want a example of one of the errors?

**Comment by ds5678** [comment]
Sure, more information generally doesn't hurt.

**Comment by Vexxus1** [comment]
Here are one of them

Library\PackageCache\com.unity.textmeshpro@3.0.8\Scripts\Runtime\TMP_Text.cs(5445,44): error CS0121: The call is ambiguous between the following methods or properties: 'TMPro.TMPro_ExtensionMethods.Multiply(UnityEngine.Color32, UnityEngine.Color32)' and 'TMPro.TMPro_ExtensionMethods.Multiply(UnityEngine.Color32, UnityEngine.Color32)'

Code:

c3 = m_tintSprite ? c3.Multiply(m_fontColorGradient.bottomRight) : c3;

**Comment by ds5678** [comment]
It sounds like you deleted the decompiled scripts for TextMeshPro and replaced them with the package.

**Comment by Vexxus1** [comment]
> It sounds like you deleted the decompiled scripts for TextMeshPro and replaced them with the package.

Interesting because I didn't do that.

**Comment by ds5678** [comment]
The package is in your project. Remove it

**Comment by Vexxus1** [comment]
> The package is in your project. Remove it

Will this remove the text from the game?

**Comment by ds5678** [comment]
No

**Comment by ds5678** [comment]
Probably not

**Comment by ds5678** [comment]
Are you using the premium edition?

**Comment by Vexxus1** [comment]
> Are you using the premium edition?

Of what?

**Comment by Vexxus1** [comment]
> > Are you using the premium edition?
> 
> Of what?

Oh no, I'm not using AssetRipper Pro

**Comment by ds5678** [comment]
It is safe to remove the package reference.

**Comment by Vexxus1** [comment]
> It is safe to remove the package reference.

Alright i'll do that now

**Comment by Vexxus1** [comment]
Just gotta load my project

**Comment by ds5678** [comment]
From here on out, you're on your own. Get help from another user if you need it, perhaps on Discord.
