### ISSUE TITLE
[Bug]: Stuck at file loading

### ISSUE THREAD

**Issue by epstomai** [AssetRipper/AssetRipper#1268]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

VRChat
[with this world](https://vrchat.com/home/launch?worldId=wrld_fd60c1cc-bbdb-4497-8c47-a73a86c6c9ed)

### Which Unity version did this occur on?

2022.3.6f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I used an older version of 0.3.4.0 for exporting at first, and it did work well. Soon i found a problem the same as [#1009](https://github.com/AssetRipper/AssetRipper/issues/1009), so i checked the latest release and downloaded 1.0.9.0
Once after i choose the file, i can see AssetRipper working by monitoring windows task manager, taking about 10% CPU usage and 2000~3000MB memory usage, console stuck at "Processing : Editor Format Conversion". Beyond that, nothing happens.
Waited for more than 5 hours, still not loaded.
Tried some other world cache files, only take a few seconds to load successfully. Also tried delete cache and re-download the world, can't get a chance.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/14733754/AssetRipper.log)

**Comment by ds5678** [comment]
Sounds like #1235

**Comment by ds5678** [comment]
My intuition says that this is animation related.

**Comment by Fyrmite** [comment]
Any update on this issue, I seem to run into the same problem, I waited for 2 hours and nothing happened, I checked task manager from start to now and the ram usage lowered from 20GB to around 2000MB within that time span gradually, the cpu utilization was 10% the whole time, I restarted the process, the files I am working with are rounded up 16GB in size and are stored in a fast NVME drive, but the majority of the time no disk is utilized and only the ram and cpu are at work.

**Comment by ds5678** [comment]
I plan to investigate the issue during this update cycle.

**Comment by gloriouslyawkward** [comment]
Same issue with Disney Dreamlight Valley using the latest version; terminal stalls on `Processing : Editor Format Conversion`.
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/14793869/AssetRipper.log)
