### ISSUE TITLE
[Bug]: Incorrect filename of shaders in Resources

### ISSUE THREAD

**Issue by GZHYBFHHJ** [AssetRipper/AssetRipper#1269]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Linux x64

### Which Unity version did this occur on?

5.5.1p4

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Exported shaders in Resources use the shader name in file content(?), not resource name.
It happens in Unity 5.5.0+ games.

**Comment by ds5678** [comment]
That's because of this:

https://github.com/AssetRipper/AssetRipper/blob/49e9b98a1b1c1b994c26fc4ff431d4bbf017f8f4/Source/AssetRipper.Assets/UnityObjectBase.cs#L40-L51
