### ISSUE TITLE
[Enhancement]: PPtrs from Unity default resources

### ISSUE THREAD

**Issue by FACS01-01** [AssetRipper/AssetRipper#1271]
### Describe the new feature or enhancement

Currently when ripping single Asset Bundles (and Asset Files too I imagine), and not having access or reference to the Unity default resource files (`[Library|Resources]/unity_builtin_extra` , `[Library|Resources]/unity default resources`), some PPtrs from default resources can end up missing and not be correctly ripped (https://github.com/AssetRipper/AssetRipper/issues/1253 , https://github.com/AssetRipper/AssetRipper/issues/1233).

Investigating with AssetsTools and UABEA, I found the following hints:
- when a PPtr (`{m_FileID, m_PathID}`) has `m_FileID != 0` it means the referenced asset is located outside the current `AssetsFile`. The `AssetsFileExternal` object related to the PPtr would be located in `AssetsFile.Metadata.Externals[m_FileID-1]`
- The `AssetsFileExternal` object has the properties `Guid` and `PathName`, among others.
- In `PathName`, when the External is in fact a Unity default resource, we can expect to find (case insensitive on "resources/" and "library/"?):
  - `"resources/unity_builtin_extra"`
  - `"library/unity default resources"`
  - `"library/unity editor resources"`
- In `Guid`, when the External is in fact a Unity default resource, we can get the `GUID` for the Editor version of the PPtr (`GUID=Guid`).
- Checking on different asset bundles from different games, for the same `PathName` I have found the same `Guid` too, meaning that maybe only looking at `PathName`, the resulting Editor `GUID` could be hardcoded even.
  - PathName: "library/unity default resources" , Guid: 0000000000000000e000000000000000
  - PathName: "resources/unity_builtin_extra" , Guid: 0000000000000000f000000000000000
- On the Editor version of the PPtr (`{GUID, FileID}`), for Unity default resources, `FileID=m_PathID`.

With all this info, it seems possible to obtain the correct Editor PPtrs for Unity default resources without having the resource files present.

Also, if this is implemented in some way, this warnings could be removed or rephrased:
```
Import : Dependency 'Library/unity default resources' wasn't found
Import : Dependency 'Resources/unity_builtin_extra' wasn't found
```

**Comment by ds5678** [comment]
I have a general idea of how I would want this implemented. There's three parts.

# Infrastructure

https://github.com/AssetRipper/AssetRipper/blob/49e9b98a1b1c1b994c26fc4ff431d4bbf017f8f4/Source/AssetRipper.Assets/Bundles/GameBundle.FromPaths.cs#L21C2-L21C211

could be changed to

```cs
public static GameBundle FromPaths(IEnumerable<string> paths, AssetFactoryBase assetFactory, IFileLoader? fileLoader = null)
```

with the following implementations:

```cs
public interface IFileLoader
{
    IDependencyProvider? DependencyProvider => null;
    IResourceProvider? ResourceProvider => null;
    UnityVersion DefaultVersion => default;
    void OnCreated(GameBundle gameBundle, AssetFactoryBase assetFactory) { }
    void OnPathsLoaded(GameBundle gameBundle, AssetFactoryBase assetFactory) { }
    void OnDependenciesInitialized(GameBundle gameBundle, AssetFactoryBase assetFactory) { }
}
public record class DefaultFileLoader(IDependencyProvider? DependencyProvider = null, IResourceProvider? ResourceProvider = null, UnityVersion DefaultVersion = default)
{
    public virtual void OnCreated(GameBundle gameBundle, AssetFactoryBase assetFactory) { }
    public virtual void OnPathsLoaded(GameBundle gameBundle, AssetFactoryBase assetFactory) { }
    public virtual void OnDependenciesInitialized(GameBundle gameBundle, AssetFactoryBase assetFactory) { }
}
```

However, I'm not fond of the `IFileLoader` name and am very open to alternative naming suggestions.

# Injection

```cs
//Create an internal or private nested class that inherits from DefaultFileLoader in the AssetRipper.Import project
private sealed record class MyCustomFileLoader : DefaultFileLoader
{
    private sealed class InjectedEngineCollection : VirtualAssetCollection
    {
        //Flags should be TransferInstructionFlags.SerializeGameRelease | TransferInstructionFlags.IsBuiltinResourcesFile

        //AssetCollection.AddAsset needs to be changed private protected -> protected

        //[AssetCollection.AddAsset needs to be changed private protected -> protected](https://github.com/AssetRipper/AssetRipper/blob/3fa347a3deef9d8ea1c6f7a46daf4fab2e818d2a/Source/AssetRipper.Assets/Collections/VirtualAssetCollection.cs#L23-L56)
        //That can all be moved to ProcessedAssetCollection
    }

    private sealed class InjectedEngineBundle : VirtualBundle<InjectedEngineCollection>
    {
        public InjectedEngineBundle() => Name = "Generated Engine Collections";
    }

    public override void OnPathsLoaded(GameBundle gameBundle, AssetFactoryBase assetFactory)
    {
        //Check if "unity default resources" or "unity_default_resources" exists in the project. The same for "unity_builtin_extra" / "unity builtin extra"
        //If not exist, add a new InjectedEngineBundle
        //Inject missing engine collections to that bundle. Use the maximum Unity version of the project
        //Load the appropriate engine resource data from the source generation assembly
        //Foreach entry in the resource data, create a new asset with the correct type id, path id, and ideally name
    }
}
```

# Export

The engine asset exporter should be modified to recognize the engine files by name when an asset is assessed. If recognized, it will export the asset without checking any properties.
