### ISSUE TITLE
[Bug]: `libunwind: malformed DW_CFA_expression DWARF unwind, reg too big`

### ISSUE THREAD

**Issue by valentinegb** [AssetRipper/AssetRipper#1272]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

MacOS x64

### Which game did this occur on?

[ULTRAKILL](https://steamdb.info/app/1229490/)

### Which Unity version did this occur on?

2019.4.40f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

AssetRipper crashed whilst exporting all assets from ULTRAKILL with default settings.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/14784420/AssetRipper.log)

It looks like the very last line that appeared in Terminal, the title of this issue, is not included in the log file.

**Comment by ds5678** [comment]
Is your Mac Arm64?

**Comment by valentinegb** [comment]
Yes it is, latest release doesn't have an arm64 binary as far as I could see

**Comment by ds5678** [comment]
Unless proven otherwise, I'm going to assume that's the cause.

**Comment by valentinegb** [comment]
Do I need to build an arm64 binary myself then?

**Comment by ds5678** [comment]
You could do that.

#1154 is about NativeAOT publishing.

**Comment by valentinegb** [comment]
Oh I didn't realize arm64 isn't supported anymore, sorry
I would do what I could to help but unfortunately I don't think I'm familiar with much of the stack of this project

**Comment by ds5678** [comment]
It's primarily a size issue. The compiled binaries are too big, and NativeAOT doesn't support branch islands, so it fails if a jump is larger than 128 MB.

**Comment by valentinegb** [comment]
This issue still exists. Shouldn't this at least be closed as not planned instead of as completed?

**Comment by ds5678** [comment]
It's just the default for when I hit the button.

**Comment by valentinegb** [comment]
I'm aware but you can still change it
