### ISSUE TITLE
[Bug]: SerializedFile writing alignment issues + missing data

### ISSUE THREAD

**Issue by DaXcess** [AssetRipper/AssetRipper#1276]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

2022.3.9f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

I've been using AssetRipper as a library to read/write certain assets (mostly configuration) within a game, and I noticed that the resulting files came out corrupt/invalid.

### Misalignment issues

To be specific: there are alignment issues within the SerializedFile class that misaligns data when writing. One place it fails is at `GetNewObjectInfoArray`: 
https://github.com/AssetRipper/AssetRipper/blob/608e3ab28e7cc54912ee50607b3fe288c49bf392/Source/AssetRipper.IO.Files/SerializedFiles/SerializedFile.cs#L187-L209

where the following code:

```cs
byteStart += 3 - (byteStart % 4);
```

should actually be

```cs
byteStart = (byteStart + 7) & ~7;
```

since object data must be aligned on an 8 byte boundary.

Another thing that is now misaligned is the object data written by `WriteObjectData`:
https://github.com/AssetRipper/AssetRipper/blob/608e3ab28e7cc54912ee50607b3fe288c49bf392/Source/AssetRipper.IO.Files/SerializedFiles/SerializedFile.cs#L174-L185

Since `AlignStream` only aligns on 4 byte boundaries, even though object data should be aligned at 8 byte boundaries.

Lastly, the last misalignment happens right before writing the object data. After inspecting numerous SerializedFiles it appears that the first object must be aligned on a 16 byte boundary, making the following code not aligned properly:
https://github.com/AssetRipper/AssetRipper/blob/608e3ab28e7cc54912ee50607b3fe288c49bf392/Source/AssetRipper.IO.Files/SerializedFiles/SerializedFile.cs#L159

### Missing ScriptTypes

When reading a SerializedFile, one of the types of data that is being read are the `ScriptTypes`. The reading is going through normally, however when writing a SerializedFile, this property is forgotten and not written to the resulting output, causing it to emit corrupt files.

When fixing this on my end it all seems to work fine, however they have only been tested on my specific Unity version, as that was the one I was using AssetRipper for.

**Comment by ds5678** [comment]
I'm honestly surprised that it worked at all for you. Writing these files was a work in progress feature that got deprioritized. 😅

In regards to the 8-byte alignment, make a pull request. I also want details about how you know that 8 is required instead of 4.

The missing (unimplemented) script types should be a separate issue.
