### ISSUE TITLE
[Bug]: i importet a game but everthing is gray

### ISSUE THREAD

**Issue by blitzi01** [AssetRipper/AssetRipper#1282]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

content warning

### Which Unity version did this occur on?

2021.3.5f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

![image](https://github.com/AssetRipper/AssetRipper/assets/166235695/6602c50f-2501-4f61-889a-7af7ac090f21)

everthing is gray and the materials have data but have no textures

### Relevant log output

found it
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/14893993/AssetRipper.log)

**Comment by blitzi01** [comment]
i real need help whit this,,,

**Comment by ds5678** [comment]
Dummy shaders are often grey.

**Comment by ds5678** [comment]
Closed because of inactivity
