### ISSUE TITLE
[Enhancement]: Deterministic GUIDs

### ISSUE THREAD

**Issue by AdalynBlack** [AssetRipper/AssetRipper#1288]
### Describe the new feature or enhancement

It would be great if AssetRipper would deterministically generate GUIDs for decompiles based on data directly in the game files such as the asset name. This would make it super easy to check for version to version differences with a simple diff, and would also be helpful in many other scenarios I imagine

**Comment by ds5678** [comment]
What you're asking for is not at all feasible.
