### ISSUE TITLE
[Enhancement]: Export raw data

### ISSUE THREAD

**Issue by aintnodawn** [AssetRipper/AssetRipper#1298]
### Describe the new feature or enhancement

I was looking for a tool capable of exporting raw data from font texture so as to edit it then import it. I had used UABEA and AssetStudio and they had problems with that. Perhaps they're too old to process assets on newer Unity build. AssetRipper works perfectly when exporting assets. Regrettably, I can only choose certain formats like PNG.

**Comment by ds5678** [comment]
I have a tool specifically for that, but it would be nice to have the functionality in the main program.
