### ISSUE TITLE
How can I export the game?

### ISSUE THREAD

**Issue by AgroTazer** [AssetRipper/AssetRipper#1300]
### Question

I want to export everything from the game so that all its source code and all unit code
By the way, the game was created on Unity and scripts on Unity

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by ds5678** [comment]
This is an extremely vague question, and the issues section is for non-questions.

**Comment by AgroTazer** [comment]
> Это в некоторой степени расплывчатый вопрос, и раздел «Проблемы» предназначен не для вопросов.

please help me

**Comment by AgroTazer** [comment]
> Это в некоторой степени расплывчатый вопрос, и раздел «Проблемы» предназначен не для вопросов.

I don’t know how to use this program, how can I decompile all the game files?
