### ISSUE TITLE
[Bug]: The latest Asset Ripper builds crashes the Unity project.

### ISSUE THREAD

**Issue by R5-3600** [AssetRipper/AssetRipper#1317]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Club Penguin Island
Windows version 1.13.0

### Which Unity version did this occur on?

Unity 2017.4.12f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

When I import the project to the Unity Hub, the project crashes.
I am using the following Asset Ripper settings:
![image](https://github.com/AssetRipper/AssetRipper/assets/21669120/a3488d0d-37ed-40e8-b349-4d84921bf4d6)
![image](https://github.com/AssetRipper/AssetRipper/assets/21669120/13abe0c2-911f-47bb-8abd-122640faa9b9)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/15119383/AssetRipper.log)

**Comment by GZHYBFHHJ** [comment]
Can you send the Unity Editor log file after editor crashes?

**Comment by R5-3600** [comment]
> Can you send the Unity Editor log file after editor crashes?

[Editor.log](https://github.com/AssetRipper/AssetRipper/files/15180259/Editor.log)

**Comment by R5-3600** [comment]
This issue also affects the latest v1.0.13 free and premium build of Asset Ripper.

**Comment by GZHYBFHHJ** [comment]
seems that AssetRipper messed something after a big changes commit
If I use Unity 2017.4 to open an exported project of a Unity 5.5.1 game, the out of memory popup shows when processing meshes (the editor tries to allocate 3GB VertexData memory. If I delete the mesh files, then it shows string oom popup when processing prefabs)
and in Unity 2021.3 games, the value of field `m_DataSize` in exported sprites is stored as hex data, not int32. It causes the Editor to keep allocating big memory (not only because it?)

**Comment by ds5678** [comment]
> seems that AssetRipper messed something after a big changes commit
> If I use Unity 2017.4 to open an exported project of a Unity 5.5.1 game, the out of memory popup shows when processing meshes (the editor tries to allocate 3GB VertexData memory. If I delete the mesh files, then it shows string oom popup when processing prefabs)
> and in Unity 2021.3 games, the value of field `m_DataSize` in exported sprites is stored as hex data, not int32. It causes the Editor to keep allocating big memory (not only because it?)

Thank you for reporting, I see what you're talking about, and I am working on a fix.

**Comment by ds5678** [comment]
https://github.com/AssetRipper/AssemblyDumper/commit/106b0910e64c359677ea2e2a14e34fc14d16171c should fix the mesh issue you're experiencing.

**Comment by R5-3600** [comment]
> seems that AssetRipper messed something after a big changes commit If I use Unity 2017.4 to open an exported project of a Unity 5.5.1 game, the out of memory popup shows when processing meshes (the editor tries to allocate 3GB VertexData memory. If I delete the mesh files, then it shows string oom popup when processing prefabs) and in Unity 2021.3 games, the value of field `m_DataSize` in exported sprites is stored as hex data, not int32. It causes the Editor to keep allocating big memory (not only because it?)

Ah. Thank you for testing that.

**Comment by ds5678** [comment]
I just pushed a commit which should resolve the _typelessdata issue you were experiencing.

**Comment by ds5678** [comment]
Are you still experiencing the problem? Can this issue be closed?

**Comment by ds5678** [comment]
Closed because of inactivity
