### ISSUE TITLE
[Bug]: Crash on Processing.AnimationClips.AnimationClipConverter

### ISSUE THREAD

**Issue by nervous-inhuman** [AssetRipper/AssetRipper#1319]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

[Vivat Slovakia](https://steamdb.info/app/2132690/)

### Which Unity version did this occur on?

2023.2.17f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

AssetRipper apparently crashes on ```AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessStreams(IReadOnlyList`1)``` with ```System.IndexOutOfRangeException: Index was outside the bounds of the array```

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/15146409/AssetRipper.log)

**Comment by ds5678** [comment]
cc: @FACS01-01

**Comment by FACS01-01** [comment]
can you send the specific file that crashes AssetRipper? so I don't have to buy the game hahah

**Comment by ds5678** [comment]
Just use trial and error to find the file.

**Comment by ds5678** [comment]
@nervous-inhuman unless you provide the file or buy one of us the game, we're going to have to close your issue. We can't reproduce your error without the relevant game file.

**Comment by ds5678** [comment]
Closed because of inactivity
