### ISSUE TITLE
[Enhancement]: Plugins

### ISSUE THREAD

**Issue by portal2707070** [AssetRipper/AssetRipper#1320]
### Describe the new feature or enhancement

Add plugins.

**Comment by ds5678** [comment]
And what would you want these plugins to be able to do?

**Comment by portal2707070** [comment]
For example:
Deobfuscate obfuscated code ( BeeByte )
To import scripts not only with variables

**Comment by ds5678** [comment]
That wouldn't be feasible with a plugin. Is there anything else?
