### ISSUE TITLE
[Bug]:Devil May Cry: Peak of Combat (Bundle compression '5' is not supported.)

### ISSUE THREAD

**Issue by LeoFeroz** [AssetRipper/AssetRipper#1322]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

[https://play.google.com/store/apps/details?id=com.nebulajoy.act.dmcpoc&hl=en_US](url)

### Which Unity version did this occur on?

2018.4.34f1

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

error when loading files

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/15176329/AssetRipper.log)

**Comment by ds5678** [comment]
Custom Unity engine
