### ISSUE TITLE
[Bug]: Segmentation Fault when running Cpp2IL

### ISSUE THREAD

**Issue by nphuracm** [AssetRipper/AssetRipper#1323]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

MacOS x64

### Which game did this occur on?

Puyo Puyo Puzzle Pop (macOS Universal)
https://apps.apple.com/us/app/puyo-puyo-puzzle-pop/id6446146451

### Which Unity version did this occur on?

2021.3.32f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

After loading assets bundles, Cpp2IL is called and AssetRipper immediately crashes with a Segmentation Fault.
**Expected Behavior:** The program should continue analyzing the game's files.
**Steps for Reproduction:**
1. Obtain game; run AssetRipper GUI.
2. Choose 'File' -> 'Open Folder' and point to the game's bundle path, `/Applications/Pine.app`.
3. AssetRipper will analyze all assets and crash when attempting to decompile the game with Cpp2IL.
```
Import : Files use the 'IL2Cpp' scripting backend.
DetermineUnityVersion: Have game data path /Applications/Pine.app/Contents/Resources/Data, trying to pull version from globalgamemanagers or data.unity3d
DetermineUnityVersion: globalgamemanagers exists, pulling version from it
Import : During Il2Cpp initialization, found Unity version: 2021.3.32f1
Cpp2IL : Initializing Metadata...
Cpp2IL : Using actual IL2CPP Metadata version 29
zsh: segmentation fault  ./AssetRipper.GUI.Free
```

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/15176354/AssetRipper.log)

**Comment by ds5678** [comment]
Is your computer Arm64?

**Comment by ds5678** [comment]
Closed because of inactivity
