### ISSUE TITLE
[Question]: how do i get from exported files back the normal files?

### ISSUE THREAD

**Issue by StudioTeamTV** [AssetRipper/AssetRipper#1326]
### Question

When i export all the files it works, but how do i get from exported files back the normal files (like sharedassets0.assets)

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by StudioTeamTV** [comment]
And **without** using Unity

**Comment by ds5678** [comment]
You can't
