### ISSUE TITLE
[Bug]: Engine Assets Before Unity 5

### ISSUE THREAD

**Issue by SNBeast** [AssetRipper/AssetRipper#1327]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Project Exonaut

### Which Unity version did this occur on?

3.5.4f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Many of the shaders in material files, and a material in a prefab, fail to resolve, leaving `0000000deadbeef15deadf00d0000000` GUIDs. Investigating in other explorers reveals that those files are commonly not found, but the shaders linked to are definitely present somewhere and used in the original game because there are pink shader errors in the rebuilt game not present in the original. Unity 3.5.4f1 is installed and the only installed version.

(Spun off unrelated note into separate issues.)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/15192755/AssetRipper.log)

**Comment by ds5678** [comment]
It sounds like you have multiple problems. I would prefer you separate them into individual issues.

**Comment by SNBeast** [comment]
The unrelated note is something I didn't want to bother with making a separate issue for, since it's easy enough to fix

**Comment by ds5678** [comment]
Are the missing materials and shaders provided by Unity?

**Comment by SNBeast** [comment]
> Are the missing materials and shaders provided by Unity?
It's pretty hard to tell, espsecially with me being so novice. Unless I'm interpreting wrong or haven't looked at enough, the properties passed from the materials I've looked at don't match any of the built-in shaders provided on Unity's download page for any of the versions in the file structure (ex: `Assets/Material/armorUpEffect.mat` using a deadbeef shader and passing the properties `_MainTex`, `_InvFade`, `_Color`, `_TintColor`). That being said, some built-in shaders _do_ resolve correctly, like `Assets/Material/Font Material.mat` correctly linking to `GUI/Text Shader`. The one failed material link, which is in the `Renderer` in `Assets/Resources/projectiles/plane.prefab`, I have no idea how to investigate, since other tools I've tried so far go nowhere.

**Comment by ds5678** [comment]
It's probably a safe assumption that these are engine assets. I'm currently only able to datamine Unity 5 and later for those.

**Comment by SNBeast** [comment]
Managed to find these assets: they're in `unity_builtin_extra`, which is built-in.

**Comment by ds5678** [comment]
> Managed to find these assets: they're in `unity_builtin_extra`, which is built-in.

My assumption was correct 👍

**Comment by ds5678** [comment]
Implemented in 479f77cc0f6694ccd0ce7993fdca34ca8c275f1d
