### ISSUE TITLE
[Bug]: Use of Array in Type Tree MonoBehaviour.Structure

### ISSUE THREAD

**Issue by SNBeast** [AssetRipper/AssetRipper#1328]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Project Exonaut

### Which Unity version did this occur on?

3.5.4f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Within MonoBehaviour blocks specifically, `Array` labels are inserted to demarcate arrays. These labels cause issues in the 3.5.4f1 editor because they are unexpected: arrays use no label, being indicated just by the dashes before each element. Deleting these erroneous labels in the exported project fixes the caused issues.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/15200807/AssetRipper.log)

**Comment by ds5678** [comment]
I assume those MonoBehaviours are exclusively from asset bundles. Is that accurate?

**Comment by SNBeast** [comment]
> I assume those MonoBehaviours are exclusively from asset bundles. Is that accurate?

They are within the main .unity3d file, if that's what you mean.

**Comment by ds5678** [comment]
I discovered the cause of your issue. Your game has weird type trees. For example, here's a field from a type tree in your game:
```
ExonautAsset mAssetQueue // ByteSize{ffffffff}, Index{85}, Version{1}, IsArray{0}, MetaFlag{8800}
	Array Array // ByteSize{ffffffff}, Index{86}, Version{1}, IsArray{1}, MetaFlag{8800}
		SInt32 size // ByteSize{4}, Index{87}, Version{1}, IsArray{0}, MetaFlag{800}
		Generic Mono data // ByteSize{ffffffff}, Index{88}, Version{1}, IsArray{0}, MetaFlag{8800}
			int mPriority // ByteSize{4}, Index{89}, Version{1}, IsArray{0}, MetaFlag{800}
			string myFilename // ByteSize{ffffffff}, Index{8a}, Version{1}, IsArray{0}, MetaFlag{8800}
				Array Array // ByteSize{ffffffff}, Index{8b}, Version{1}, IsArray{1}, MetaFlag{4801}
					SInt32 size // ByteSize{4}, Index{8c}, Version{1}, IsArray{0}, MetaFlag{801}
					char data // ByteSize{1}, Index{8d}, Version{1}, IsArray{0}, MetaFlag{801}
```
However, here are some other fields which exhibit normal behavior:
```
vector AtlasButtons // ByteSize{ffffffff}, Index{ed}, Version{1}, IsArray{0}, MetaFlag{800}
	Array Array // ByteSize{ffffffff}, Index{ee}, Version{1}, IsArray{1}, MetaFlag{800}
		SInt32 size // ByteSize{4}, Index{ef}, Version{1}, IsArray{0}, MetaFlag{800}
		Rectf data // ByteSize{10}, Index{f0}, Version{2}, IsArray{0}, MetaFlag{800}
			float x // ByteSize{4}, Index{f1}, Version{1}, IsArray{0}, MetaFlag{800}
			float y // ByteSize{4}, Index{f2}, Version{1}, IsArray{0}, MetaFlag{800}
			float width // ByteSize{4}, Index{f3}, Version{1}, IsArray{0}, MetaFlag{800}
			float height // ByteSize{4}, Index{f4}, Version{1}, IsArray{0}, MetaFlag{800}
vector mNameTimer // ByteSize{ffffffff}, Index{f5}, Version{1}, IsArray{0}, MetaFlag{800}
	Array Array // ByteSize{ffffffff}, Index{f6}, Version{1}, IsArray{1}, MetaFlag{800}
		SInt32 size // ByteSize{4}, Index{f7}, Version{1}, IsArray{0}, MetaFlag{800}
		float data // ByteSize{4}, Index{f8}, Version{1}, IsArray{0}, MetaFlag{800}
```
`vector` indicates that the child `Array` node is not a field named `Array`.

**Comment by ds5678** [comment]
Type trees can be extracted with the `TypeTreeExtractor` tool in this repository.
