### ISSUE TITLE
[Bug]: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by postredaction** [AssetRipper/AssetRipper#1332]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Gorebox https://steamdb.info/app/2027330/info/ OR https://play.google.com/store/apps/details?id=com.F2Games.GBDE&hl=en_US

### Which Unity version did this occur on?

2021.3.36.1605
![image](https://github.com/AssetRipper/AssetRipper/assets/87862680/ca0adb53-9c63-4d24-805b-fc383ae5b6d5)

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I attempted to load game files with the following settings:
![image](https://github.com/AssetRipper/AssetRipper/assets/87862680/16430e4f-a9dc-41a7-9c47-f5f54916675b)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/15221011/AssetRipper.log)

**Comment by postredaction** [comment]
Update: I managed to successfully open the files and export using version 0.3.4.0

**Comment by ds5678** [comment]
cc: @FACS01-01
