### ISSUE TITLE
[Enhancement]: Add Command Line Interface (CLI)

### ISSUE THREAD

**Issue by art0007i** [AssetRipper/AssetRipper#1343]
### Describe the new feature or enhancement

Sometimes I want to quickly export all files of a certain type from a game. A cli would be perfect for this. I personally would need it to allow setting all the configuration options using command line parameters as well as having some parameters to select what asset type(s) should be exported.

**Comment by ds5678** [comment]
Not planned, except to expand the exposed GET and POST api offerings
