### ISSUE TITLE
[Bug]: Very high RAM usage

### ISSUE THREAD

**Issue by wednesday2024** [AssetRipper/AssetRipper#1344]
### Are you on the latest version of AssetRipper?

Yes, 1.0.13.1 Premium.

### Which release are you using?

Windows x64

### Which game did this occur on?

Disney Dreamlight Valley

### Which Unity version did this occur on?

2023.2.11f1

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

The game is 12.3GB and Asset Ripper is using 44GB+ of RAM. I have 64GB of physical RAM and 32GB of a page file. Windows ran out of RAM and crashed. 
![image](https://github.com/AssetRipper/AssetRipper/assets/21669120/0803303e-9ee6-4717-bd58-87e799bc4635)
![image](https://github.com/AssetRipper/AssetRipper/assets/21669120/3f6356cf-c939-4fd2-aaa0-bcbe8c939506)

**Comment by ds5678** [comment]
I think this was resolved in 13edc04cd1994df19e10e1d107622a008790beec, similar to #1409.
