### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ThatFunModder** [AssetRipper/AssetRipper#1346]
### Question

how do we make it not a website? but in a tab

https://github.com/AssetRipper/AssetRipper/assets/165534495/8eea4cd3-7ac6-447e-be91-16776b6b62ea

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by ThatFunModder** [comment]
Ok! Here!
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/15367213/AssetRipper.log)

**Comment by GZHYBFHHJ** [comment]
#1280

**Comment by ds5678** [comment]
File dropping doesn't work in a web browser.

**Comment by ThatFunModder** [comment]
> File dropping doesn't work in a web browser.

Then how do i do it in a app?
