### ISSUE TITLE
[Bug]: Specified argument was out of the range of valid values

### ISSUE THREAD

**Issue by CBacchus** [AssetRipper/AssetRipper#1352]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Little Alchemist: Remastered 
https://play.google.com/store/apps/details?id=io.monumental.littlealchemist.google&hl=en_US&gl=US

### Which Unity version did this occur on?

2022.3.22f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

This game used to work in Asset Ripper until some of the more recent versions. The last working version of the game I have been able to use is 2.12.1 (Which still puts errors in the logs for Asset Ripper 0.3.4.0 but not for 1.0.14). The last working version of the game that I have found without any errors in the logs on Asset Ripper 0.3.4.0 is 2.11.0. When you try the game version 2.12.2 or newer, Asset Ripper fails to work at all with errors being printed in both versions of Asset Ripper. I included the logs from 0.3.4.0 in addition to 1.0.14 because they look like they are more descriptive. 

### Relevant log output

Latest version (1.0.14): [AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/15371335/AssetRipper.log)
0.3.4.0: [AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/15371351/AssetRipper.log)

**Comment by ds5678** [comment]
> System : AssetRipper Version: 1.0.13.1

This is not 1.0.14

**Comment by CBacchus** [comment]
Oh, interesting. I used the latest windows download from [here](https://assetripper.github.io/AssetRipper/articles/Downloads.html) and I assumed it was 1.0.14 because that said it was the latest. But you are right it is .13.1. Looks like it works again on 1.0.14. Thanks.
