### ISSUE TITLE
[Bug]: System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by ksspsmoo** [AssetRipper/AssetRipper#1353]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Kour.io (web version)

### Which Unity version did this occur on?

6000.0.0f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I tried opening the dump folder in AssetRipper after following a tutorial. It just didn't work and showed this error.

I just followed this tutorial: [https://youtu.be/d5xlS7s0m_s?t=285](https://youtu.be/d5xlS7s0m_s?t=285)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/15378851/AssetRipper.log)

**Comment by ds5678** [comment]
cc: @FACS01-01
