### ISSUE TITLE
[Bug]: Problem with the Unity version 2022.1.16f1

### ISSUE THREAD

**Issue by Maxandkon** [AssetRipper/AssetRipper#1360]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

tes:Castles

### Which Unity version did this occur on?

2022.1.16f1

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

Greetings,
I'm getting a bunch of errors and almost everything is sent to .unreadable, or not fit for review

I can assume that this is some kind of general problem with the game, since other data-mine soft either crash or freeze (as I get on the textures), but I'm not sure if this is not just a particular issue with the version

### Relevant log output

![image](https://github.com/AssetRipper/AssetRipper/assets/36767477/cdaf5a51-bac6-4098-9b6e-5a3c4abe07e0)
![image](https://github.com/AssetRipper/AssetRipper/assets/36767477/7468aa3f-908d-4b8a-81cf-653de70a5cdd)

**Comment by ds5678** [comment]
> I can assume that this is some kind of general problem with the game, since other data-mine soft either crash or freeze (as I get on the textures)

Probably correct

> I'm not sure if this is not just a particular issue with the version

With the exception of a small few, I've dumped type trees for all the Unity versions.

**Comment by ds5678** [comment]
If you discover otherwise, feel free to reopen the issue.
