### ISSUE TITLE
[Bug]: Unable to open any files from Arena of Valor game

### ISSUE THREAD

**Issue by Glopease** [AssetRipper/AssetRipper#1364]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Arena of Valor

### Which Unity version did this occur on?

2019.4.15f1

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

Unable to load any file from this game due to System.ArgumentOutOfRangeException

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/15431264/AssetRipper.log)

**Comment by Glopease** [comment]
here is one of the game assetbundle file: [
[1239_lvbu_battle.zip](https://github.com/AssetRipper/AssetRipper/files/15432856/1239_lvbu_battle.zip)
](url)

**Comment by Glopease** [comment]
Anyone help?

**Comment by ds5678** [comment]
This seems like the files are encrypted in some way. There's nothing I can do to help you.
