### ISSUE TITLE
[Possible Bug]: When the asset name conflicts, exported `png` and `asset` doesn't match

### ISSUE THREAD

**Issue by RaenonX** [AssetRipper/AssetRipper#1367]
## Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

## Which release are you using?

Windows x64

## Which game did this occur on?

[Pokemon Sleep](https://play.google.com/store/apps/details?id=jp.pokemon.pokemonsleep&hl=en_US)

## Which Unity version did this occur on?

2021.3.16f1

## Is the game Mono or IL2Cpp?

IL2Cpp

### Problematic Bundle File

[ebd951d715b83736dd2b361cd7d510a7.zip](https://github.com/AssetRipper/AssetRipper/files/15441293/ebd951d715b83736dd2b361cd7d510a7.zip)

### Reproduction

1. Load and export the problematic bundle file, grouped by bundle name.
2. Use this hash `a13dd613cc0094077b4e9cacc8af5eba` to search the whole exported folder. It should be in `stand_0.asset`.
3. The corresponding image, if I understand it correctly, is `stand_0.png`. However, it doesn't match. Instead, `stand.png` should is the image I am looking for.

> See `How do I know it mismatches` below about why it's that hash.

### Ultimate Goal

My ultimate goal is given the hash of `a13dd613cc0094077b4e9cacc8af5eba`, I can locate the following image in any way. 

![image](https://github.com/AssetRipper/AssetRipper/assets/18443743/2f127a07-7a31-430b-9019-e3af93bc0d37)

I have a Python script that checks different file to create a mapping and pinpoint the file I want. So it works for me as long as there's some information in either `*.asset` or `*.meta` file to help linking `a13dd613cc0094077b4e9cacc8af5eba` to `stand.png` above.

### How did I know it mismatches

From the parsing result of `catalog_36.json` using my own parser, I see that the asset name of `Spine/Pokemon/155/stand/shiny/stand.png` corresponds to the hash `a13dd613cc0094077b4e9cacc8af5eba`, which matches the key of `Sprite.m_RenderDataKey` in `stand_0.asset`. The asset name indicates that the `png` should be the shiny version (brown colored) of the image. However, `stand_0.png` is green colored instead with `stand.png` being shiny colored.

### Relevant log output

AR log: [AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/15441403/AssetRipper.log)

Exported data: [PKS-Data-14.zip](https://github.com/AssetRipper/AssetRipper/files/15441404/PKS-Data-14.zip)

**Comment by ds5678** [comment]
I had to read it several times, but I think I understand what you're saying:
* You exported the project with AssetRipper.
* You analyzed an addressable catalog with separate tooling and found a hash paired with a path.
* You looked at yaml sprites in the ripped project and noticed that the render data key matched your hash.
* You looked for a texture at the path cooresponding to the hash.
* Apparently, there were two textures with that path, so only one of them had that exact path when exported.
* Finding the wrong texture caused problems for your use case.

**Comment by RaenonX** [comment]
> I had to read it several times, but I think I understand what you're saying:
> 
> * You exported the project with AssetRipper.
> * You analyzed an addressable catalog with separate tooling and found a hash paired with a path.
> * You looked at yaml sprites in the ripped project and noticed that the render data key matched your hash.
> * You looked for a texture at the path cooresponding to the hash.
> * Apparently, there were two textures with that path, so only one of them had that exact path when exported.
> * Finding the wrong texture caused problems for your use case.

Sorry if this seems complicated, I tried my best to simplify it 😆 

Changed some texts and annotated them using `[]` to ensure clarity.

- You looked at yaml sprites in the ripped project and noticed that [there is a] render data key match[ing my] hash.
- You looked for a texture at the path cooresponding to the hash. [The texture I am looking for could be either `stand.png` or `stand_0.png`, which, I can only try to locate them using the sprite file name that contains my hash.]

Since my current way of locating the image might be either bugged or just unreliable, the texture I located is the incorrect one.
This is the current logic:
- Hash found in render data key in `stand_0.asset`
- Find `stand_0.png` and export it (`stand.png` is actually the one I am looking for)

**Comment by ds5678** [comment]
What's the purpose of all this?

**Comment by RaenonX** [comment]
> What's the purpose of all this?

On top of the ultimate goal listed in the first comment, I am grabbing all spine-related files, precisely files of `*.atlas` `*.png` `*.skel` to render the animation of them on my website.

![image](https://github.com/AssetRipper/AssetRipper/assets/18443743/bd15002a-40c6-43b2-977a-1c385344a60f)

The live example is here https://pks.raenonx.cc/en/pokedex/155. You'll see that when clicking on "Moving" and "Standing," the color of the Pokemon changes while it should not, unless "shiny" changes.

![image](https://github.com/AssetRipper/AssetRipper/assets/18443743/3b53c994-088d-4042-94f0-10a44831081a)

**Comment by ds5678** [comment]
> My ultimate goal is given the hash of a13dd613cc0094077b4e9cacc8af5eba, I can locate the following image in any way.

This is not a goal. https://en.wikipedia.org/wiki/XY_problem

**Comment by ds5678** [comment]
Why didn't you just use the guid?

**Comment by RaenonX** [comment]
> > My ultimate goal is given the hash of a13dd613cc0094077b4e9cacc8af5eba, I can locate the following image in any way.
> 
> This is not a goal. https://en.wikipedia.org/wiki/XY_problem

If you mean what exactly I am looking for is unclear, because I don't have enough knowledge about how it works under the hood, anyway you think it's feasible to help linking the hash to the image works. The reason why I mark it as "possible bug" is also because that I am not sure if the linking of `stand_0.asset` <> `stand.png` is expected or not.

> Why didn't you just use the guid?

I actually missed this part. Just checked as you commented. If you mean `m_RD.texture.<HASH>` to link them, I think it actually does the trick. Thanks for bringing this up!

----------

I'll try using `guid` to locate the image and see if it works. If it works, then I'll just close this issue. Does it work for you? Thanks for bringing it up in advance.

**Comment by ds5678** [comment]
> I am not sure if the linking of stand_0.asset <> stand.png is expected or not.

The fact that your method worked is mostly due to the popularity of `png` textures. If the developer had decided to use a different image format, the catalog path would have used that extension whereas AssetRipper would have still used `png`.

> If it works, then I'll just close this issue. Does it work for you?

Sounds good. Nothing here sounds like an actual bug.

**Comment by RaenonX** [comment]
Using `guid` seems to be working, agree that nothing is a bug here. Thanks for pointing out `guid` usage!

Couldn't believe that I knew #1294 improved GUID behavior and I used that for `*.skel` and `*.atlas` without realizing that `png` could go with the same route.
