### ISSUE TITLE
[Bug]: Brilliant Diamond Error

### ISSUE THREAD

**Issue by ProfBlack** [AssetRipper/AssetRipper#1368]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Pokémon Brilliant Diamond

### Which Unity version did this occur on?

2019.4.27f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Upon exporting I am greeted with this error and nothing more happens.
![image](https://github.com/AssetRipper/AssetRipper/assets/55605783/baa35adf-a0fb-4942-8b36-8189b65dbf8e)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/15446030/AssetRipper.log)

**Comment by ds5678** [comment]
I was unable to reproduce the issue on my version of the game and could not download a newer version.

**Comment by ProfBlack** [comment]
The issue seems to be dependant on ripping certain files but I haven’t yet ascertained which. I can try to verify later this week which bundles are causing problems.

**Comment by lululuuuuuuu** [comment]
be likely to Sprite Export Format selected Texture

**Comment by ProfBlack** [comment]
This bug still exists in the latest Premium 1.0.17 when using the Unity sprite export format. Using YAML as the user in https://github.com/AssetRipper/AssetRipper/issues/1386 did allows me to export.
