### ISSUE TITLE
[Bug]: The path is too long, or a component of the specified path is too long.

### ISSUE THREAD

**Issue by mayagibuyuk** [AssetRipper/AssetRipper#1372]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

MacOS Arm64

### Which game did this occur on?

https://steamdb.info/app/2008510/

### Which Unity version did this occur on?

2021.3.25f1

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

I got this error when trying to export .bundle file :
[Error] : System.IO.PathTooLongException: The path `/Users/meenoi/Downloads/pls/ExportedProject/Assets/Texture2D/z__Gradient_ColorTex{"mode"_0_"colorKeys"__{"color"_{"r"_0.6037735939025879_"g"_0.6037735939025879_"b"_0.6037735939025879_"a"_1.0}_"time"_0.0}_{"color"_{"r"_0.8301886916160584_"g"_0.8301886916160584_"b"_0.8301886916160584_"a"_1.0}_"time"_0.440_100.png.meta` is too long, or a component of the specified path is too long.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/15497615/AssetRipper.log)

**Comment by ds5678** [comment]
I think the file name needs truncated. Even though most operating systems support very long paths, the individual parts must be less than 256 characters.

https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits

**Comment by ds5678** [comment]
However I'm also interested in knowing what this asset is because it's clearly been generated.

**Comment by mayagibuyuk** [comment]
Similar asset:
![z__Gradient_Color_1Tex{ mode _0_ colorKeys __{ color _{ r _1 0_ g _0 0_ b _0 07841873168945313_ a _1 0}_ time _0 0}_{ color _{ r _0 00702186394482851_ g _0 0_ b _2 670156955718994_ a _1 0}_ time _0 9970855116844177}__ alphaKeys __{ alpha _1 0_](https://github.com/AssetRipper/AssetRipper/assets/10811446/f4ae36b2-7c6f-4fc5-a99b-8b0be499cfdb)
I think it's a LUT texture.

**Comment by mayagibuyuk** [comment]
I think its for something like this but in Unity:
https://tobiasnoller.com/articles/ue4-gradient-mapping-vfx/

**Comment by ds5678** [comment]
I was hoping for a link to the exact thing used in this project.

**Comment by mayagibuyuk** [comment]
Sorry I don't know, the link above is just my guess.

**Comment by ds5678** [comment]
The problem is likely here or in FileUtils.

https://github.com/AssetRipper/AssetRipper/blob/a7b02781e961b9a31350a8ed0d6ae8fa0d3780a5/Source/AssetRipper.Export.UnityProjects/ExportCollection.cs#L74-L101
