### ISSUE TITLE
[Enhancement]: YooAsset Support

### ISSUE THREAD

**Issue by XFSZYB** [AssetRipper/AssetRipper#1375]
### Describe the new feature or enhancement

i have a android game apks, it is use yooasset [[https://github.com/tuyoogame/YooAsset](https://links.jianshu.com/go?to=https%3A%2F%2Fgithub.com%2Ftuyoogame%2FYooAsset)](url) , AssetRipper is not work,can not extract asset inner yooasset

**Comment by ds5678** [comment]
I do not support third party file formats. However, you may be able to develop software that preprocesses those custom files into ones that AssetRipper can read.
