### ISSUE TITLE
[Question]: Editor crashes after going into playmode

### ISSUE THREAD

**Issue by M4LivesAgain** [AssetRipper/AssetRipper#1379]
### Question

does anyone know why my editor crashes after i enter playmode? even if i build it crashes the actual game. the logs dont show a whole lot just "CRASH!!!" then dll things and boom its no log after that.

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by ds5678** [comment]
No idea
