### ISSUE TITLE
[Bug]: AssetRipper took nearly all of my storage space

### ISSUE THREAD

**Issue by Jajoo2** [AssetRipper/AssetRipper#1399]
### Are you on the latest version of AssetRipper?

~~No, I need to download a newer version and try again.~~ I do not need to download a newer version. This is not a version issue, I don't think.

### Which release are you using?

Linux x64

### Which game did this occur on?

It's not a game specific issue, but it was ULTRAKILL.

### Which Unity version did this occur on?

I have no idea.

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

I tried to take 1 single texture file from ULTRAKILL but it nearly crashed my PC and filled my SDD before it could even show the files. All I need to know is what it did and how I can fix it. Please help.

### Relevant log output

The log has no use; it is not helpful here

**Comment by Jajoo2** [comment]
did i just type "sdd"

**Comment by ds5678** [comment]
> The log has no use; it is not helpful here

Among other things, it would have told me what version you're using.

**Comment by Jajoo2** [comment]
> > The log has no use; it is not helpful here
> 
> Among other things, it would have told me what version you're using.

I did not know that.

**Comment by Jajoo2** [comment]
I have deleted some unnecessary files but there's still the issue that AssetRipper has caused a bunch of gigabytes to just vanish. I cannot find a reason why they're gone. I've rebooted and cleared /tmp on my own, nothing has caused any slight difference
(infact, i think rebooting it made it slightly worse)

**Comment by ds5678** [comment]
Clear your user (not system) temporary folder

**Comment by Jajoo2** [comment]
> Clear your user (not system) temporary folder

there's 2 temporary folders?!

**Comment by Jajoo2** [comment]
my issue is solved
