### ISSUE TITLE
MPEG not supported by Fmod5Sharp

### ISSUE THREAD

**Issue by FuryBaM** [AssetRipper/AssetRipper#1412]
### Describe the new feature or enhancement

Find a way to solve such a problem. I am sure that it will occur in other Unity projects as well.
Example:
`Export : Can't decode audio clip 'Menu_Loop_Final' with default decoder because it's 'MPEG' encoded.
Export : Can't decode audio clip 'Quest_Loop_Final' with default decoder because it's 'MPEG' encoded.
Export : Can't decode audio clip 'Ready_Fight_Final' with default decoder because it's 'MPEG' encoded.
Export : Can't decode audio clip 'PreBattle_Loop4_Final' with default decoder because it's 'MPEG' encoded.
Export : Can't decode audio clip 'Battle_Loop_Final' with default decoder because it's 'MPEG' encoded.`

**Comment by ds5678** [comment]
What game?

**Comment by FuryBaM** [comment]
> What game?

Marvel Contest of Champions

**Comment by ds5678** [comment]
Upstream issue: https://github.com/SamboyCoding/Fmod5Sharp
