### ISSUE TITLE
[Enhancement]: Default log location

### ISSUE THREAD

**Issue by diadatp** [AssetRipper/AssetRipper#1414]
### Describe the new feature or enhancement

I am currently packaging Asset Ripper for NixOS/nixpkgs and have come across a roadblock. The program stores the log file to the path `AppContext.BaseDirectory` (via defaults for `FileLogger` and `ExecutingDirectory`). Due to the way nix manages things, his path is within its read only nix store (`/nix/store/...`). The current workaround is to point the log to `System.Environment.CurrentDirectory` via a build time patch.

The feature request is to change this path to something that will allow me to proceed with the packaging without the patch as I do not want to confuse users about the log's location. Perhaps a user specified path or default to the current working directory.

**Comment by ds5678** [comment]
I am open to a command line argument that specifies the log location.

**Comment by ds5678** [comment]
`--log-path`

**Comment by ds5678** [comment]
I assume that me moving the temporary folder to the executing directory (which is planned) would also be an issue for your operating system. You can add a `--temp-path` for that too. Just mark it as currently unused. I'll hook it up when I do the switch.

**Comment by diadatp** [comment]
That sounds like a good solution. Yes, the temp folder plans would cause issues.

A helpful error message would also be nice as the current message is an Unhandled System.IO.IOException exception on the line below: https://github.com/AssetRipper/AssetRipper/blob/2dd84a059e26bc1e4d3bb79ffdb9a38e9614acc4/Source/AssetRipper.Import/Logging/FileLoggerBase.cs#L21

Something along the lines of "The default location for logs is read only, please specify an alternative location using the command line switch ..." Not sure how to get the exact reason of the exception from the `System.IO.IOException` so that the message is gated for the read only violation.
