### ISSUE TITLE
[Question]: What is the difference between the premium version and the standard version?

### ISSUE THREAD

**Issue by dxdx123** [AssetRipper/AssetRipper#1415]
### Question

What is the difference between the premium version and the standard version?

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by ds5678** [comment]
https://www.patreon.com/posts/premium-launch-97523831

More exclusive features are planned, but this is the current set of premium features.

**Comment by leetus** [comment]
Sorry for bumping this but do you ever plan to implement any of the premium features into the free version in the near future?
