### ISSUE TITLE
[Other]: Timberborn sprite assets are being treated as unreadable now

### ISSUE THREAD

**Issue by awsdert** [AssetRipper/AssetRipper#1417]
### Describe the issue

I don't remember which version had supported the Timberborn sprites (will give each version a try tomorrow if I remember) but they were once displayed and exported correctly (or at least mostly correct, never spotted an issue in them)

**Comment by ds5678** [comment]
Logs would be helpful

**Comment by awsdert** [comment]
Took me a moment to find this but here you go:

[AssetRipper.log](https://github.com/user-attachments/files/16274102/AssetRipper.log)

**Comment by ds5678** [comment]
It's just a Unity version support issue. The game uses a really new version of Unity. When I rerun the AssetRipper source generation, everything will be fine.

**Comment by awsdert** [comment]
g2n :)

**Comment by awsdert** [comment]
I assume 0.19 is on the way then? :)

**Comment by ds5678** [comment]
I am planning to release `1.1.0` in the next couple hours. However, you can download an alpha build before then.

**Comment by awsdert** [comment]
Just tried the alpha build and sprites are still treated as unreadable, used the download link from here: https://nightly.link/AssetRipper/AssetRipper/workflows/publish/master

**Comment by ds5678** [comment]
That is likely not an AssetRipper bug then.

**Comment by awsdert** [comment]
Judging by the log I think it might be AssetRipper missing a few bytes when reading:
```
Read 516 but expected 520 for asset type Sprite. V: 6000.0.7f1 P: StandaloneWin64Player N: resources.assets Path: 
[Error] : Read 1076 but expected 1080 for asset type Sprite. V: 6000.0.7f1 P: StandaloneWin64Player N: resources.assets Path: 
[Error] : Read 480 but expected 484 for asset type Sprite. V: 6000.0.7f1 P: Standalone
```
[AssetRipper.log](https://github.com/user-attachments/files/16336937/AssetRipper.log)

**Comment by ds5678** [comment]
(or the developers paid for source access and added a field)

**Comment by awsdert** [comment]
How about adding an option to try ignoring the extra fields?

**Comment by awsdert** [comment]
Nope, definitely assetripper is the issue. The `AssetRipper.GUI.Free` of the 1.0.17 release loaded the sprites of the current TB release without issue:
![Screenshot_2024-07-22_18-34-53](https://github.com/user-attachments/assets/f0c07f44-b1e7-420e-96d6-e6d879dd8dea)

**Comment by awsdert** [comment]
Likewise the `AssetRipper.GUI.Free` of 1.1.0 outputed the sprites correctly (and seemingly a lot faster than the 1.0.17 release). The binary `AssetRipper` however does not produce the sprites at all. That 4 byte difference clearly indicates an error in the binary's handling of sprites.

**Comment by ds5678** [comment]
I could not reproduce this.

[AssetRipper.log](https://github.com/user-attachments/files/16423102/AssetRipper.log)

**Comment by awsdert** [comment]
Maybe it's because you're using windows? Open up virtual box or something and load up an arch based distro, I'm using manjaro stable XFCE x64. Maybe the issue is how you've used some function that is linux/unix specific?

**Comment by awsdert** [comment]
Then maybe how you've interpreted a value it gave you when using mono?

**Comment by ds5678** [comment]
Mono isn't really a thing anymore. It got killed by .NET Core.

**Comment by awsdert** [comment]
AH, maybe it's the path case issue. Linux uses only case sensitive paths so maybe you're getting a different path to what windows gives due to it using case insensitivity.

**Comment by ds5678** [comment]
I fail to see how pathing could any effect on this.

**Comment by ds5678** [comment]
My version of Timberborn is from 7/25/2024.

**Comment by awsdert** [comment]
Let's say you open x/... but there's 2 different directories of x, x/ & X/. In this scenario you've specified you want the lower case variant but perhaps what was actually wanted was the uppercase variant.

**Comment by awsdert** [comment]
> My version of Timberborn is from 7/25/2024.

Is that MM/DD/YYYY? That's a confusing way to write it, simpler to go from smallest to biggest like we do in the UK but anyways. Mine is experimental edition, just booting steam to get the version

**Comment by awsdert** [comment]
23/7/2024

**Comment by ds5678** [comment]
> Let's say you open x/... but there's 2 different directories of x, x/ & X/. In this scenario you've specified you want the lower case variant but perhaps what was actually wanted was the uppercase variant.

The reason why pathing doesn't matter is that even if it was loading "the wrong file" (which it's not because all the Timberborn paths are case insensitive unique), reading assets is a file-local operation. It doesn't depend on anything external to the file.

**Comment by awsdert** [comment]
hmm, well there's definitely something happening simply because it's on linux. My only suggestion is to debug in linux and catch the moment before it reads any sprite to compare against how it reads in windows. At some point you'll catch a value being different and then you'll know where to look for the subtle bug.

**Comment by ds5678** [comment]
It has nothing to do with Linux specifically. That's mostly a coincidence. If I repeated my process in a Linux vm, I would get the same result I have been.

The difference is that our game files are different, either by version or platform or both.

**Comment by awsdert** [comment]
If that were the case then why does the `.GUI.Free` variant succeed where the other fails?

**Comment by ds5678** [comment]
[AssetRipper.log](https://github.com/user-attachments/files/16423511/AssetRipper.log)

**Comment by ds5678** [comment]
Since it's not clear from the log, that was with the latest build of the premium edition.

**Comment by awsdert** [comment]
I can't afford premium, stuck on benefits so I gotta go with free only

**Comment by ds5678** [comment]
> If that were the case then why does the .GUI.Free variant succeed where the other fails?

I interpreted this to mean "why does the free edition succeed when the premium edition fails?"

Prior to you saying that, I had been using the free edition to test.

**Comment by awsdert** [comment]
No, I was referring to the actual binaries in the same download, give me a mo and I'll screenshot them highlighted

**Comment by awsdert** [comment]
![assetripperhighlight](https://github.com/user-attachments/assets/3394a7dd-f438-4873-9fee-f101b7dc4090)

**Comment by ds5678** [comment]
You have extra files in that folder.

**Comment by awsdert** [comment]
what ones?

**Comment by ds5678** [comment]
Redownload and compare

**Comment by awsdert** [comment]
huh, didn't notice, I just extracted to the same folder expecting any updated files to replace the old ones. So when did the non `.GUI.Free` stop being released?

**Comment by ds5678** [comment]
There were significant changes to the file structure around `1.0.0.0`.

**Comment by awsdert** [comment]
hm, how did I get the `AssetRipper` one then? My link history only goes as far back as the 1.0.17 release

**Comment by ds5678** [comment]
You probably just cleared your history.

**Comment by awsdert** [comment]
That was maybe a year or 2 ago though?

**Comment by ds5678** [comment]
1.0.0 was released on Nov 9, 2023.

**Comment by awsdert** [comment]
hmm, musta cleared my history a little more recently than I thought, it only goes as far back as just over 6 months

**Comment by ds5678** [comment]
Is everything fine now?
