### ISSUE TITLE
[Other]: setting open folder with asset ripper

### ISSUE THREAD

**Issue by tuanvus** [AssetRipper/AssetRipper#1418]
### Describe the issue

I used this command `"F:ToolSAssetRipper_win_x64 (1)AssetRipper.exe" "%V"` to open and import the folder and it ran but to extract I don't know how to extract it to the selected item, as the above command will extrac directly to the root folder of AssetRipper please help me

**Comment by ds5678** [comment]
You seem to be using a very old version of AssetRipper.
