### ISSUE TITLE
[Bug]: error when trying to read the path "GameBundle -> build_webgl.data -> data.unity3d" of the "*.data" file in a Unity WebGL project

### ISSUE THREAD

**Issue by cyberfoxmeow** [AssetRipper/AssetRipper#1419]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

The webXR example I build on Unity by myself. The plugin I was using is: https://github.com/De-Panther/unity-webxr-export.git 

(There is an example demo online here: https://de-panther.github.io/unity-webxr-export/Build/    . But I build the example using the plugin by myself.)

The Unity project is an URP 3D project. 

### Which Unity version did this occur on?

2022.3.16f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I load the folder of the project, and when I try to view the loaded files of "GameBundle -> build_webgl.data -> data.unity3d", there is an error:

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.ThrowHelper.ThrowArgumentOutOfRangeException() + 0x24
   at AssetRipper.GUI.Web.Paths.BundlePath.get_Parent() + 0xf5
   at AssetRipper.GUI.Web.Pages.Bundles.ViewPage.WriteInnerContent(TextWriter) + 0xf0
   at AssetRipper.GUI.Web.DefaultPage.Write(TextWriter) + 0x4d1
   at AssetRipper.Web.Content.WebContent.ToString() + 0x3c
   at AssetRipper.Web.Content.WebContent.WriteToResponse(HttpResponse) + 0x28
   at AssetRipper.GUI.Web.Pages.Bundles.BundleAPI.GetView(HttpContext context) + 0x83
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext) + 0x299
   at AssetRipper.GUI.Web.ErrorHandlingMiddleware.<InvokeAsync>d__0.MoveNext() + 0x2a
```

The file tree of the WebGL project is:
```
D:.
│  index.html
│
├─Build
│      Build_WebGL.data
│      Build_WebGL.framework.js
│      Build_WebGL.loader.js
│      Build_WebGL.wasm
│
└─TemplateData
        favicon.ico
        fullscreen-button.png
        progress-bar-empty-dark.png
        progress-bar-empty-light.png
        progress-bar-full-dark.png
        progress-bar-full-light.png
        style.css
        unity-logo-dark.png
        unity-logo-light.png
        webgl-logo.png
```

Maybe, I think when AsserRipper extracts the `data.unity3d` from `Build_WebGL.data`, some prefix symbols are different from the `*.unity3d` files of other general projects.

### Relevant log output

1.0.16:   [AssetRipper.log](https://github.com/user-attachments/files/16288075/AssetRipper.log)

1.0.18:   [AssetRipper.log](https://github.com/user-attachments/files/16288170/AssetRipper.log)

**Comment by ds5678** [comment]
Your stack trace should be impossible. I'll take a look when I get home.

**Comment by cyberfoxmeow** [comment]
steps:

![image](https://github.com/user-attachments/assets/26130a50-f106-41e7-86b4-2f5e2497748e)

![image](https://github.com/user-attachments/assets/680f1278-dc50-4c8f-9642-f53bb38c5c26)

![image](https://github.com/user-attachments/assets/9db46469-96c9-4e83-a57e-66a341d27faa)

![image](https://github.com/user-attachments/assets/b9cc25b5-7331-4fea-ba9f-81697c7f292c)

**Comment by cyberfoxmeow** [comment]
webGl build: 
[build.zip](https://github.com/user-attachments/files/16288535/build.zip)
