### ISSUE TITLE
[Bug]: MonoBehaviour Import/Export Errors [Darkest Dungeon 2]

### ISSUE THREAD

**Issue by AquaZera** [AssetRipper/AssetRipper#1427]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Darkest Dungeon 2

### Which Unity version did this occur on?

2022.3.16f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

All Mono Behavior scripts say missing Mono Script.

### Relevant log output

[AssetRipper.log](https://github.com/user-attachments/files/16379508/AssetRipper.log)

**Comment by ds5678** [comment]
You probably have to fix compile errors

**Comment by AquaZera** [comment]
Yep, had to work through some compilation errors but it worked after that.
