### ISSUE TITLE
[Enhancement]: Set exported YAML Shader files to Read-Only

### ISSUE THREAD

**Issue by FACS01-01** [AssetRipper/AssetRipper#1434]
### Describe the new feature or enhancement

YAML shader assets can be corrupted if Unity Editor thinks they are dirty and tries to save/overwrite them.
To solve this, AssetRipper generates a Patcher script for the Project: "AvoidSavingYamlShaders.cs".

I propose that, instead of inserting an extra script into the Project, the YAML Shader files can be set to Read-Only instead, using available APIs from System.IO.

This also benefits Primary Content Extraction, that doesn't have a target Project where to insert the Patcher script.

**Comment by ds5678** [comment]
Primary content extraction doesn't export anything as yaml. Generic assets are serialized as json.

**Comment by ds5678** [comment]
> I propose that, instead of inserting an extra script into the Project, the YAML Shader files can be set to Read-Only instead, using available APIs from System.IO.

I assume you verified that this works and that Unity doesn't use similar APIs to make it writable?

**Comment by ds5678** [comment]
Assuming that it's effective, I am in favor of doing this for Unity project export. I really like that the protection wouldn't depend on scripts compiling.

**Comment by FACS01-01** [comment]
Ahh sorry, while testing this I forgot to delete your Patcher 😅 and without it Unity does ignore the ReadOnly flag and edits the shader anyways.
Doing more research, Unity devs said they were going to fix this issue, but seems there has been no update since 2009, still broken.
I guess this has to be closed as can't be implemented.
