### ISSUE TITLE
Texture 2D assigned on materials broken

### ISSUE THREAD

**Issue by Fuckhead-Gaming-HD** [AssetRipper/AssetRipper#1438]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Block City Wars 6.4.5/4.1.1

### Which Unity version did this occur on?

Unity 5.3.7p1 (x64 Windows)

Unity 5.1 (x64 Windows)

Unity 2017.4.40f1 (x64 Windows)

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

When open with original Unity version, material are broken and set to no texture2d, when update project to Unity 2017.4.40 , texture assigned but broken and assigned random stuff to objects.
![CB20625A-2C44-4115-87CA-55273EB94080](https://github.com/user-attachments/assets/afa9091a-5719-4500-b995-1e8c908aa35f)
![730D2DB3-680D-4E5E-A347-0AC8EFCFFA3B](https://github.com/user-attachments/assets/d5e87533-3aff-4fa4-b235-93e5eb583da8)
![EEEF236E-593A-4F1D-8844-4A0C4241B038](https://github.com/user-attachments/assets/74939cc8-df54-4146-b95a-b7952e984a75)

**Comment by ds5678** [comment]
Upgrading the project generally breaks it because Unity projects are fragile.

**Comment by Fuckhead-Gaming-HD** [comment]
> Upgrading the project generally breaks it because Unity projects are fragile.

The textures get reset to nothing when using the original Unity version , but when update to editor 2017.4.40 , the textures are there, but some are missing , and the textures in materials are assigned but they are incorrectly put in , this only happens to Block City Wars (any versions) , not other games like Pixel Gun 3D

**Comment by ds5678** [comment]
So what are you asking from me?

**Comment by Fuckhead-Gaming-HD** [comment]
> So what are you asking from me? I'm not sure what the conditions for closure are for this GitHub issue.

I assume its just the game itself being broken , im just gonna redo its textures now.
