### ISSUE TITLE
[Enhancement]: Unity packages instead of importing them, mark them to be installed.

### ISSUE THREAD

**Issue by CODEHUBHQ** [AssetRipper/AssetRipper#1442]
### Describe the new feature or enhancement

Is there a feature, that asset ripper won't export unity packages, however, when I open the project in unity these packages will be installed. so they just don't import them from the apk.

all I need from the project is the UI, character models (prefabs without the scripts but main components), and other assets not related to the packages outside of unity. is there an option for that. then the not working scripts and add their name and dummy methods if possible if not just the scripts names or remove them at all.

but when I do that manually most of the character models are not working and missing.

**Comment by ds5678** [comment]
Unity package information is not encoded in games.
