### ISSUE TITLE
[Question]: AssetRipper GUI became web based ?

### ISSUE THREAD

**Issue by walektine** [AssetRipper/AssetRipper#1443]
### Question

There is a question, since last update is AssetRipper for Mac OS become as web based app ? cause before i could launch it as mac os application, but right now i saw it opens local http server and web browser window.
seems "Running on Mac" (https://assetripper.github.io/AssetRipper/articles/RunningOnMac.html) is not actual right now.

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by ds5678** [comment]
The guide is likely outdated. I do not maintain it.

**Comment by walektine** [comment]
> The guide is likely outdated. I do not maintain it.

I see, but what do to then , who could help with that.

**Comment by ds5678** [comment]
> right now i saw it opens local http server and web browser window.

It sounds like everything is fine. What was your actual problem.

**Comment by based64-eth** [comment]
how do i open a folder/file on mac in the web-based gui? i cant for the life of me figure out how to open the file upload dialog. dragging a folder or file into the browser-based gui just opens up a new tab with the resource uri.

**Comment by ds5678** [comment]
@based64-eth Just paste the file path. File Dialogs supposed don't work for Mac, so I have them disabled, but I forgot to hide the button.
