### ISSUE TITLE
[Bug]: game 'Loop8: Summer of Gods' fails to list files

### ISSUE THREAD

**Issue by newby24** [AssetRipper/AssetRipper#1444]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://steamdb.info/app/2127430/

### Which Unity version did this occur on?

2021.3.9a0

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

AssetRipper never loads the assets, when selecting the whole folder, even after waiting for a very long time. In the console output I can see a bunch of errors.
When I try to unpack individual asset bundle files, they tend to open and are able to be extracted no problem. The issue only occurs when I point AssetRipper to the whole game's folder.

### Relevant log output

[AssetRipper.log](https://github.com/user-attachments/files/16630042/AssetRipper.log)

**Comment by ds5678** [comment]
Hello, I'll take a look at your log either tonight or tomorrow night.

**Comment by newby24** [comment]
> Hello, I'll take a look at your log either tonight or tomorrow night.

Thank you. Feel free to request additional info or anything. I just find this super weird, especially given that I am able to extract individual asset bundles no problem, yet Asset Ripper just fails to do anything meaningful when pointed directly to the game's folder.

**Comment by ds5678** [comment]
A log for each scenario would be helpful.

**Comment by newby24** [comment]
> A log for each scenario would be helpful.

[(game folder) AssetRipper.log](https://github.com/user-attachments/files/16631774/game.folder.AssetRipper.log)
[(individual bundle) AssetRipper.log](https://github.com/user-attachments/files/16631776/individual.bundle.AssetRipper.log)

**Comment by ds5678** [comment]
Duplicate of #740
