### ISSUE TITLE
[Bug]: Error received when attempting to open a file 

### ISSUE THREAD

**Issue by some-guy-idk** [AssetRipper/AssetRipper#1447]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

I hadn't even opened the file yet, so this is N/A.

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

I was trying to simply open a game file when I received the error message "Unable to load DLL 'nfd' or one of its dependencies: The specified module could not be found".

### Relevant log output

[AssetRipper.log](https://github.com/user-attachments/files/16635591/AssetRipper.log)

**Comment by ds5678** [comment]
That can happen if:
* You try to run AssetRipper from inside the zip file.
* You move the AssetRipper exe or delete the files around it.
* Your computer is Arm64.

**Comment by some-guy-idk** [comment]
i have used assetripper multiple times but today it just refused to work. all the files are in the Assetripper folder, and the zip file has already been extracted. my computer is not arm64.

**Comment by some-guy-idk** [comment]
i also reninstalled it but it still doesn't work

**Comment by ds5678** [comment]
Screenshot of your installation folder

**Comment by some-guy-idk** [comment]
ok after a day it finally worked. i am sorry for wasting your time. thanks for the help!
