### ISSUE TITLE
[Bug]: Unity 4.7.2 crash opening scene (Menu)

### ISSUE THREAD

**Issue by zeranoname** [AssetRipper/AssetRipper#1457]
### Are you on the latest version of AssetRipper?

No, I need to download a newer version and try again.

### Which release are you using?

Windows x64

### Which game did this occur on?

Block Strike

### Which Unity version did this occur on?

4.7.2f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

crash opening scene (Menu) 
I use last gui version Asset Ripper.
P.S. - I also want to say that when decompiling a game on Unity 5.6.5 using Utiny Ripper, it does not cause crashes
```
Platform assembly: G:\Unity Installs\4.7.2f1\Editor\Data\Mono\lib\mono\2.0\Mono.Security.dll (this message is harmless)
Platform assembly: G:\Unity Installs\4.7.2f1\Editor\Data\Managed\nunit.framework.dll (this message is harmless)
Task failed: Verifier Task
Crash!!!
SymInit: Symbol-SearchPath: 'G:/Unity Installs/4.7.2f1/Editor/Data/MonoEmbedRuntime;.;G:\Unity Projects\Block Strike;G:\Unity Installs\4.7.2f1\Editor;C:\Windows;C:\Windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530
```

### Relevant log output
[AssetRipper.log](https://github.com/user-attachments/files/16686555/AssetRipper.log)

**Comment by ds5678** [comment]
Might be #811

**Comment by zeranoname** [comment]
> Может быть #811

There is no LightningData in the Menu scene.

**Comment by ds5678** [comment]
> There is no LightningData in the Menu scene.

It's not a GameObject. It's a independent asset.

> Unity 5.6.5 using Utiny Ripper

uTinyRipper does not recover a significant portion of asset types, including LightingDataAsset. It also attempts to bump the Unity version up to 2017.3.0.

**Comment by zeranoname** [comment]
> > В сцене меню нет LightningData.
> 
> Это не GameObject. Это независимый актив.
> 
> > Unity 5.6.5 с использованием Utiny Ripper
> 
> uTinyRipper не восстанавливает значительную часть типов ассетов, включая LightingDataAsset. Он также пытается повысить версию Unity до 2017.3.0.

I know that this is not a GameObject. Here are all the lighting files that the Menu has.
![image](https://github.com/user-attachments/assets/ae4a2709-53a3-4e99-bdf4-56a54cf07635)
![image](https://github.com/user-attachments/assets/d79c2aad-36fb-4d2f-84cf-b5d848d39cda)
What solution to the problem can you offer?

**Comment by ds5678** [comment]
> What solution to the problem can you offer?

I encourage you to investigate and report back with more information.

**Comment by zeranoname** [comment]
> > Какое решение проблемы вы можете предложить?
> 
> Я призываю вас провести расследование и предоставить более подробную информацию.

What exactly do you want to know? I can record the screen first decompilation before opening the Menu scene.

**Comment by zeranoname** [comment]
> > Какое решение проблемы вы можете предложить?
> 
> Я призываю вас провести расследование и предоставить более подробную информацию.

Also, I can say that if I delete all scripts from the project and enter the Menu scene, there will be no crash.

**Comment by ds5678** [comment]
Oh, you need to fix the compile errors.

**Comment by zeranoname** [comment]
> О, вам нужно исправить ошибки компиляции.

?

As soon as I fix all the errors in the scripts in the project, and go to the menu, I get a crash.

**Comment by ds5678** [comment]
Try decompiled instead of hybrid.

**Comment by zeranoname** [comment]
> Try decompiled instead of hybrid.
I'm sorry, I didn't quite understand what you mean.

**Comment by zeranoname** [comment]
> Try decompiled instead of hybrid.

I'm sorry, I didn't quite understand what you mean.

**Comment by zeranoname** [comment]
![image](https://github.com/user-attachments/assets/22809558-0e79-4fd7-93db-d914ce90fedf)
I don't use scripts from Asset Ripper, I take scripts from Ilspy.

**Comment by zeranoname** [comment]
> Try decompiled instead of hybrid.

![image](https://github.com/user-attachments/assets/eeb8de93-0d0d-4493-8be0-edaea19b90b7)
I decided to try it, and I got this error right away.

**Comment by ds5678** [comment]
That error has nothing to do with script export. It happened because you changed your game files.

**Comment by ds5678** [comment]
Closing because you use a very outdated version of the software.

**Comment by zeranoname** [comment]
> Закрываюсь, так как вы используете очень устаревшую версию программного обеспечения.

xD, thank you)) 
I always knew that utiny ripper was better.
