### ISSUE TITLE
[Bug]: doesnt work

### ISSUE THREAD

**Issue by Joshouaaaaaa** [AssetRipper/AssetRipper#1464]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

![image_2024-08-25_141720659](https://github.com/user-attachments/assets/742e273e-adbb-4777-b271-770ef5ff2d7e)
this is what happens when i try exporting it

### Which Unity version did this occur on?

i dont know 

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

didnt export

### Relevant log output

help

**Comment by ds5678** [comment]
Please be sure you have uploaded your `AssetRipper.log` file. It is in the same folder as the exe file. :)
