### ISSUE TITLE
[Enhancement]: Suggestion on adding a way to extract a video from an asset.

### ISSUE THREAD

**Issue by SJCoding0130** [AssetRipper/AssetRipper#1467]
### Describe the new feature or enhancement

 As of the current version, there is no way to extract a video from an asset. So I'm suggesting it here

**Comment by ds5678** [comment]
Videos can already be exported for Unity Project Export. What are you asking for?

* Export in Primary Content Extraction?
* UI preview?
* UI download button?
* All three?

**Comment by SJCoding0130** [comment]
preview
