### ISSUE TITLE
[Bug]: Default version / Target version for version changing not loaded from file

### ISSUE THREAD

**Issue by RaenonX** [AssetRipper/AssetRipper#1468]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

N/A

### Which Unity version did this occur on?

N/A

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

As title. Starting AR with this file [AssetRipper.Settings.json](https://github.com/user-attachments/files/16762447/AssetRipper.Settings.json) at the same directory will load almost everything except the version specification.

**Comment by ds5678** [comment]
Note that the new settings file format is incompatible with the old one.

**Comment by RaenonX** [comment]
> Note that the new settings file format is incompatible with the old one.

Got it, thanks!
