### ISSUE TITLE
[Possible Bug]: Possible Asset Deduplication Miss

### ISSUE THREAD

**Issue by RaenonX** [AssetRipper/AssetRipper#1474]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

[Pokemon Sleep](https://play.google.com/store/apps/details?id=jp.pokemon.pokemonsleep&hl=en_US)

### Which Unity version did this occur on?

2022.3.24f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

In the `catalog_37.json` file of the game, there are 2 entries that ultimately would connect to the attached file:
```
{
  "path": "Spine/Pokemon/245/sleep-rare/sleep-rare.png",
  "hash": "50755e6692cc346fcab6ae2802f02870"
},
{
  "path": "Spine/Pokemon/245/sleep-rare/sleep-rare_2.png",
  "hash": "adb8466bb2bc2470c95fb16c60e3260a"
},
{
  "path": "Spine/Pokemon/245/sleep-rare/shiny/sleep-rare.png",
  "hash": "75e96489a0b954bd59cf2f2f172d2bc1"
},
{
  "path": "Spine/Pokemon/245/sleep-rare/shiny/sleep-rare_2.png",
  "hash": "afda6342fa9d148a796cdb6404c37bd8"
},
```
However, by running text search in all the extracted files exported as unity project, and grouped by their bundle name, only the following 2 hashes got an connection to an `*.asset` file:
- `50755e6692cc346fcab6ae2802f02870` -> `sleep-rare.asset`
- `adb8466bb2bc2470c95fb16c60e3260a` -> `sleep-rare_2.asset`

Following the same pattern, `75e96489a0b954bd59cf2f2f172d2bc1` and `afda6342fa9d148a796cdb6404c37bd8` should be able to point to an `*.asset` file for each as well.

The corresponding png exists with the de-duped naming like `sleep-rare_0.png` and `sleep-rare_2_0.png`, so I am suspecting that the `*.asset` file deduplication is somehow lost during the process.

[5760a4b7f8408057ce08a65afb572216.zip](https://github.com/user-attachments/files/16824825/5760a4b7f8408057ce08a65afb572216.zip)

### Relevant log output

[AssetRipper.log](https://github.com/user-attachments/files/16824851/AssetRipper.log)

**Comment by ds5678** [comment]
AssetRipper does not currently use catalog json files.

**Comment by RaenonX** [comment]
> AssetRipper does not currently use catalog json files.

I know. but I don't think that the hash inside catalog json file matching `guid` of the `*.asset` files is a coincidence.

FWIW, in `AuxiliaryFiles\path_id_map.json`, I am seeing 2 entries with the same `Name` of `sleep-rare`:
```json
{
  "PathID": 3092792823749969684,
  "Name": "sleep-rare",
  "Type": "Texture2D"
},
{
  "PathID": -8381533049420688397,
  "Name": "sleep-rare",
  "Type": "Texture2D"
},
```

If `*.asset` and `*.png` has 1-to-1 relationship, then the red-marked one could be the missing files because of the naming conflict (they all named as `sleep-rare`.
```diff
+sleep-rare.asset
+sleep-rare.asset.meta
+sleep-rare.png
+sleep-rare.png.meta
-sleep-rare_0.asset
-sleep-rare_0.asset.meta
+sleep-rare_0.png
+sleep-rare_0.png.meta
```

**Comment by ds5678** [comment]
Can you describe the problem in one sentence? I'm having trouble seeing the forest instead of the trees.

**Comment by RaenonX** [comment]
> Can you describe the problem in one sentence? I'm having trouble seeing the forest instead of the trees.

Sorry of piling tons of IDs on your face. 

With 2 entries of assets having `Name` of `sleep-rare` according to `path_id_map.json`, I expect to see `sleep-rare_0.asset` and `sleep-rare_0.asset.meta` getting exported, if a `Texture2D` will have 1 `*.asset` and 1 `*.png`. (the red-green-ish table in https://github.com/AssetRipper/AssetRipper/issues/1474#issuecomment-2322919262 shows what seems to be missing)

**Comment by ds5678** [comment]
I assume the .asset files are sprites. Did you verify that the sprite you're looking for actually exists?

**Comment by RaenonX** [comment]
> I assume the .asset files are sprites. Did you verify that the sprite you're looking for actually exists?

If this is what you mean, then yes

![image](https://github.com/user-attachments/assets/5cae7f6a-a59e-4a02-bfc9-e1bf015f75eb)

**Comment by ds5678** [comment]
In the asset page for each of those, look at the dependencies tab.

**Comment by RaenonX** [comment]
> In the asset page for each of those, look at the dependencies tab.

For some reason, if I go to Game Bundle > Collections > CAB-* > Assets, I am only seeing 1 Sprite despite having 2 SpriteInformation for each.

------------------------

A bit out of the topic for this issue, but for what I am trying to do, if there's anyway to export the highlighted string to yaml, it's also fine

![image](https://github.com/user-attachments/assets/c55b670b-3cb4-4b0d-b4be-81f5223494ab)

**Comment by RaenonX** [comment]
In case helpful, if I got to "Sprite Data Storage" and click on each `sleep-rare`, 
![image](https://github.com/user-attachments/assets/d03f8d76-8a02-48a3-b6d3-f0230ddf2c68)

They have different Path ID,
![image](https://github.com/user-attachments/assets/188f2383-caec-44c0-b5df-68075d2f1cd2)
![image](https://github.com/user-attachments/assets/0bfe30ef-da2c-41db-aedb-cb0de29b21b5)

And the texture of them will lead to different Texture2D.
![image](https://github.com/user-attachments/assets/bbb5c218-2bae-438f-a7c4-8d0b6cf2165c)
![image](https://github.com/user-attachments/assets/7e40a393-6757-4c05-bdcb-4a761e7e4006)

**Comment by ds5678** [comment]
I just pushed a commit which should let you see dependencies for the generated SpriteInformationObject assets, which I should mention are per texture, not per sprite.

**Comment by RaenonX** [comment]
> I just pushed a commit which should let you see dependencies for the generated SpriteInformationObject assets, which I should mention are per texture, not per sprite.

Thanks, do you happen to have a built `*.exe` so I can run it?

**Comment by ds5678** [comment]
https://github.com/AssetRipper/AssetRipper/actions/runs/10646695956

**Comment by RaenonX** [comment]
In the `SpriteInformationObject` of Path ID = 1, nothing extra:
![image](https://github.com/user-attachments/assets/934a428a-3ae4-4df1-aed4-f909bc47ed00)

The `sleep-rare` here leads to the Texture2D of original path = `Assets\75e96489a0b954bd59cf2f2f172d2bc1`

In the `SpriteInformationObject` of Path ID = 6, there's an additional `Sprites[].Key`:
![image](https://github.com/user-attachments/assets/39cc33b7-27ca-47a1-95df-466620a36e58)

The `sleep-rare` from `Texture` leads to the Texture2D of original path = `Assets\50755e6692cc346fcab6ae2802f02870`
The `sleep-rare` from `Sprites[].Key` leads to a Sprite of original path = `Assets\50755e6692cc346fcab6ae2802f02870`

**Comment by ds5678** [comment]
No bug then. The game was just different than you expected.

**Comment by RaenonX** [comment]
> No bug then. The game was just different than you expected.

I see. In this case, is there any way to export the `Original Path` from Texture2D to YAML?

![image](https://github.com/user-attachments/assets/83d4bf4e-60ee-4e2d-84ab-a219a2ee7f4e)

**Comment by ds5678** [comment]
No, that would violate the Unity formatting.

**Comment by RaenonX** [comment]
> No, that would violate the Unity formatting.

I see. Hopefully last question - is there anyway I can either get the `Original Path` on Texture2D, or get the things from the Sprite Data Storage out? It seems like the duplicated sprites are just disconnected from the whole thing all of sudden.

**Comment by ds5678** [comment]
To be clear, Sprite Data Storage and everything in it is generated by AssetRipper. There's no Unity equivalent to these artificial assets. `SpriteInformationObject` is a root asset I create to hold the hierarchical information about a texture and its associated sprites.

> is there anyway I can either get the Original Path on Texture2D, or get the things from the Sprite Data Storage out?

Not without coding.

**Comment by RaenonX** [comment]
> To be clear, Sprite Data Storage and everything in it is generated by AssetRipper. There's no Unity equivalent to these artificial assets. `SpriteInformationObject` is a root asset I create to hold the hierarchical information about a texture and its associated sprites.

I see, thanks for the insights!

> > is there anyway I can either get the Original Path on Texture2D, or get the things from the Sprite Data Storage out?
> 
> Not without coding.

If you don't mind, could you point me to where I should be looking to, so I can fork the project and customize the exported YAML to include that `Original Path`?

**Comment by ds5678** [comment]
https://github.com/AssetRipper/AssetRipper/blob/d70048e2a4d1c1a5702ed389ce56e5a96ebedb38/Source/AssetRipper.Export.UnityProjects/YamlWalker.cs

**Comment by RaenonX** [comment]
> https://github.com/AssetRipper/AssetRipper/blob/d70048e2a4d1c1a5702ed389ce56e5a96ebedb38/Source/AssetRipper.Export.UnityProjects/YamlWalker.cs

Thanks! Will explore a bit and ask questions in discussion if I have any, thanks for all your help!
