### ISSUE TITLE
[Bug]: A lot of errors are generated when attempting to load assets for the game "A Mother's Inferno"

### ISSUE THREAD

**Issue by mg8973** [AssetRipper/AssetRipper#1476]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

A Mother's Inferno

### Which Unity version did this occur on?

3.4.0f5

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

A ton of errors are generated when I open the data folder for this game, and a lot of the extracted assets are marked as "Unreadable".

### Relevant log output

[AssetRipper.log](https://github.com/user-attachments/files/16826122/AssetRipper.log)

**Comment by ds5678** [comment]
AssetRipper only supports 3.5 and higher.
