### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by VXliSX** [AssetRipper/AssetRipper#1495]
### Question

AssetRipper just doesn't appear in the files. I've re-downloaded it many times but the Application just does not appear. It appeared the first time I downloaded AssetRipper, but that was back in June. But I can't remember what happened to it. But anyway, Asset Ripper Application does not appear in the files. Really strange and super annoying.

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by ds5678** [comment]
https://github.com/AssetRipper/AssetRipper/releases
