### ISSUE TITLE
[Bug]: Unable to load DLL 'nfd' or one of its dependencies

### ISSUE THREAD

**Issue by randomazzy11** [AssetRipper/AssetRipper#1497]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

none

### Which Unity version did this occur on?

none

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

I try to run asset ripper and select "open file" or "open folder" in the web gui (im using firefox btw if that helps)  and nothing happens but i get an error in the console saying nfd dll file is not found. In the assetripper root folder (excracted btw) there is a nfd.dll but no matter what i try to do (put it in a different folder, download an older release,reboot) it keeps complaining about this dll. Im not running it from the zip file and im using x64 and i didnt move it out of the assetripper folder (all of the assterripper files are in one folder) Also this is a very fresh install of windows.

### Relevant log output

[AssetRipper.log](https://github.com/user-attachments/files/17034611/AssetRipper.log)

**Comment by randomazzy11** [comment]
suddenly fixed itself, closing

**Comment by jesseconnr** [comment]
For anyone finding this and the others in the future, you might need the latest vc++ redistributable.

- https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist
