### ISSUE TITLE
[Bug]: Infinite waiting after loading game folder [Dofus Unity Beta]

### ISSUE THREAD

**Issue by Arkwell9112** [AssetRipper/AssetRipper#1498]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://www.dofus.com/fr : Dofus 2.0
In Unity version actually in beta phase.

### Which Unity version did this occur on?

2022.3.29a0
Got this from the output of AssetRipper.

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

When loading the Dofus_Data folder from game files the process seems to work normally until "Application model created in xx.xxms", then just nothing happen.

### Relevant log output

[AssetRipper.log](https://github.com/user-attachments/files/17050115/AssetRipper.log)

**Comment by ds5678** [comment]
@Arkwell9112 are you still experiencing the problem?

**Comment by TiagoXavi** [comment]
I had the same problem. But the loading wasn't infinite. It took a lot of time but not infinite

**Comment by qyzhaojinxi** [comment]
stuck after Application model created
