### ISSUE TITLE
[Bug]: Cant export all files on the latest version older versions works ok 

### ISSUE THREAD

**Issue by proganime1200** [AssetRipper/AssetRipper#1511]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

All unity 

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Its stock on  Exporting to Unity version on all unity version

**Comment by Hyperatox** [comment]
[Patreon here] Can confirm asset bundle export does not work anymore
I tested it with the very same file on these versions, the test returns are in the attachments.
[AssetRipperFailed.log](https://github.com/user-attachments/files/17279636/AssetRipperFailed.log)
[AssetRipperWorking.log](https://github.com/user-attachments/files/17279647/AssetRipperWorking.log)

**Comment by ds5678** [comment]
@proganime1200 I am able to reproduce this behavior and am investigating.

@Hyperatox Your program seems to have stalled earlier than @proganime1200. I have not been able to reproduce that.

**Comment by ds5678** [comment]
Should be resolved now

**Comment by Hyperatox** [comment]
> @Hyperatox Your program seems to have stalled earlier than @proganime1200. I have not been able to reproduce that.
1.1.6.0 fixed it work fine now! Thank you!
