### ISSUE TITLE
[Bug]: Infinite "SceneView.Repaint"

### ISSUE THREAD

**Issue by ilnarildarovuch** [AssetRipper/AssetRipper#1523]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

- Non of those, this is written from scratch (?) modification for Plants vs. Zombies Fusion Mod. Not found English download, here is Russian (PC): https://www.playground.ru/plants_vs_zombies/file/plants_vs_zombies_mod_plants_vs_zombies_fusion_edition_pk_i_android-1726884

### Which Unity version did this occur on?

2022.3.20f1c1 (c1 have simple patch, so it can be taken as 2022.3.20f1)

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

It's not really infinite, but if it closes, it getting open again. When deleting dinamic libs, it's getting ok, but it cannot open for example "TMPro", cause this in libs. I tried to open this by pre-installed DLL (This is didn't work). May this be caused by Chinese text in path or files.
![Снимок экрана 2024-10-14 222334](https://github.com/user-attachments/assets/1d11ced3-1fe7-45ab-87d8-fc46d42e6c93)

### Relevant log output

[AssetRipper.log](https://github.com/user-attachments/files/17383373/AssetRipper.log)

**Comment by ds5678** [comment]
This kind of issue is unlikely to be prioritized due to the large time commitment for investigation.
