### ISSUE TITLE
[Enhancement]: Linux Arm64 build?

### ISSUE THREAD

**Issue by gphg** [AssetRipper/AssetRipper#1525]
### Describe the new feature or enhancement

Windows and Mac has Arm64 downloads, Linux don't.

**Comment by ds5678** [comment]
I had issues with cross compilation for Linux. I think those can be resolved, but it wasn't trivial like Mac and Windows.

**Comment by ds5678** [comment]
Implemented in 4f93ff3428c80568fb6f8b3ebcf43f7818fb554c

**Comment by gphg** [comment]
Thanks!
