### ISSUE TITLE
[Bug]: [Error] : atlas is not the same as mappedAtlas

### ISSUE THREAD

**Issue by Prota100** [AssetRipper/AssetRipper#1526]
### Are you on the latest version of AssetRipper?

No, I need to download a newer version and try again.

### Which release are you using?

Unselected

### Which game did this occur on?

Cult of the Lamb

### Which Unity version did this occur on?

2021.3.16f1

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

keep getting errors 

### Relevant log output

[EhSSAutD.txt](https://github.com/user-attachments/files/17396923/EhSSAutD.txt)

**Comment by Prota100** [comment]
https://pastebin.com/EhSSAutD

**Comment by ds5678** [comment]
Duplicate of #740

**Comment by BonecoSinforoso** [comment]
The same happened here, in this same game.
