### ISSUE TITLE
[Bug]: Assets\Scripts\Assembly-CSharp\#####.cs(271,94): error CS0535: '#####._003C#####' does not implement interface member 'IDisposable.Dispose()'

### ISSUE THREAD

**Issue by 1392-github** [AssetRipper/AssetRipper#1528]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

2021.3.22f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

When opening the created project with Unity, the error message below is displayed and script loading fails.
[Bug]: Assets\Scripts\Assembly-CSharp\#####.cs(271,94): error CS0535: '#####._003C#####' does not implement interface member 'IDisposable.Dispose()'

**Comment by ds5678** [comment]
Script compilation errors are somewhat normal because ILSpy decompilation is imperfect.

**Comment by 1392-github** [comment]
The problem is that even though a dummy script is created as an alternative, the dummy method that must be specified in the interface is not created.

**Comment by ds5678** [comment]
Could be https://github.com/SamboyCoding/Cpp2IL/issues/310

Either way, it's an upstream issue

**Comment by 1392-github** [comment]
The problem is that errors occurred in too many scripts and the properties in the inspector do not appear as shown above.
![image](https://github.com/user-attachments/assets/dc855f1e-1ea8-4ffe-abfe-a0c383bade12)

**Comment by 1392-github** [comment]
How do I make the inspector properties appear even if there are Unity script errors?
