### ISSUE TITLE
.FBX or .OBJ Wavefront mesh export?

### ISSUE THREAD

**Issue by Fuckhead-Gaming-HD** [AssetRipper/AssetRipper#1529]
### Describe the new feature or enhancement

For example , a FBX option or Wavefront OBJ option could be added along with GLB and Yaml  meshes export drop down menu without having to convert the Yaml or GLB meshes to the desired format using a unity package , or a separate tool.

**Comment by ds5678** [comment]
As stated in Discord, removing support for formats other than GLB was an intentional design decision to avoid the footgun of users assuming all formats export the same and to reduce development overhead.
