### ISSUE TITLE
[Bug]: all custom shaders are broken

### ISSUE THREAD

**Issue by Mustafa-Agha** [AssetRipper/AssetRipper#1536]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Steel And Flesh 2

https://play.google.com/store/apps/details?id=com.VS.SteelAndFlesh2&hl=en

### Which Unity version did this occur on?

2022.3.50f1 LTS

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

All custom shaders are broken, here is an example of fx/water shader

```
Shader "FX/Water" {
	Properties {
		_WaveScale ("Wave scale", Range(0.02, 0.15)) = 0.063
		_ReflDistort ("Reflection distort", Range(0, 1.5)) = 0.44
		_RefrDistort ("Refraction distort", Range(0, 1.5)) = 0.4
		_RefrColor ("Refraction color", Vector) = (0.34,0.85,0.92,1)
		[NoScaleOffset] _Fresnel ("Fresnel (A) ", 2D) = "gray" {}
		[NoScaleOffset] _BumpMap ("Normalmap ", 2D) = "bump" {}
		WaveSpeed ("Wave speed (map1 x,y; map2 x,y)", Vector) = (19,9,-16,-7)
		[NoScaleOffset] _ReflectiveColor ("Reflective color (RGB) fresnel (A) ", 2D) = "" {}
		_HorizonColor ("Simple water horizon color", Vector) = (0.172,0.463,0.435,1)
		[HideInInspector] _ReflectionTex ("Internal Reflection", 2D) = "" {}
		[HideInInspector] _RefractionTex ("Internal Refraction", 2D) = "" {}
	}
	//DummyShaderTextExporter
	SubShader{
		Tags { "RenderType" = "Opaque" }
		LOD 200
		CGPROGRAM
#pragma surface surf Standard
#pragma target 3.0

		struct Input
		{
			float2 uv_MainTex;
		};

		void surf(Input IN, inout SurfaceOutputStandard o)
		{
			o.Albedo = 1;
		}
		ENDCG
	}
}
```

However this shader shows as follows:-

![01](https://github.com/user-attachments/assets/510deb78-5519-4272-8d4b-39f76475df16)

here is another shader that should show terrain gameobject:-

![02](https://github.com/user-attachments/assets/abfaaa94-328c-4270-8a9a-1a3a74976303)

And the same goes for all custom shaders, just white shaders.

### Relevant log output

[AssetRipper.log](https://github.com/user-attachments/files/17484141/AssetRipper.log)

**Comment by ds5678** [comment]
They're not broken; they're just dummy shaders. It's one of the export settings.

**Comment by Mustafa-Agha** [comment]
Is there a way to export the actual shader?
