### ISSUE TITLE
[Bug]: 你的bug把我桌面所有文件永久清空了

### ISSUE THREAD

**Issue by Asuna-NanShi** [AssetRipper/AssetRipper#1538]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

unity6000.0.23

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

我使用了导出功能，选择了桌面路径，结果把我桌面所有文件永久清空了，气死我了

**Comment by ds5678** [comment]
Duplicate of #1283

**Comment by CetPYze** [comment]
你导出的时候他有提示你该文件夹不是空的若确实导出会自动清空(大意),你可能没有注意到

**Comment by Asuna-NanShi** [comment]
确实是我没有注意到提示，但是我很惊讶这居然是这样设计的而不是个bug，自动新建一个子文件夹并且使用它这个操作很难吗？
