### ISSUE TITLE
[Question]: I can't access the AssetRipper user interface

### ISSUE THREAD

**Issue by LotusGame** [AssetRipper/AssetRipper#1539]
### Question

![image](https://github.com/user-attachments/assets/a04484c6-4ee1-4326-9f24-eb851fb8275c)
![image](https://github.com/user-attachments/assets/2a4229fa-af26-4a6e-8e84-b8b406c45eca)

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by SamboyCoding** [comment]
There are instructions in your second image.

**Comment by LotusGame** [comment]
Thanks for your feedback, I am Vietnamese, it is quite difficult to communicate in English, can you be more detailed?
![image](https://github.com/user-attachments/assets/3b35d923-876b-494c-b673-f74cc8002ed1)

**Comment by SamboyCoding** [comment]
Open http://127.0.0.1:55271 in your browser.

**Comment by LotusGame** [comment]
I did that, but I'm not sure if I paid correctly? I can't open the app interface
![image](https://github.com/user-attachments/assets/43694497-c721-4a54-92f6-b131a2fc3482)
![image](https://github.com/user-attachments/assets/c253cb28-09a5-48f7-b81c-04189687b985)

**Comment by LotusGame** [comment]
> Thank you for submitting your first issue here. Please be sure you have uploaded your `AssetRipper.log` file. It is in the same folder as the exe file. :)
Can you please guide me in more detail? Thank you
![image](https://github.com/user-attachments/assets/23f99139-96e4-4b9b-af9f-a25ac6c83ff0)

**Comment by SamboyCoding** [comment]
Ah, so you're actually trying to find out where to download the premium version?

**Comment by LotusGame** [comment]
Tôi muốn thoát khỏi giao diện này và chuyển sang giao diện người dùng AssetRipper
Please guide me and pay it, or payment guide, AssetRiper interface installation
![image](https://github.com/user-attachments/assets/7c5bc22e-9473-4e59-9d61-80121366d726)

**Comment by ds5678** [comment]
Top left corner of the screen is a menu.

**Comment by LotusGame** [comment]
I still can't open the assetripper interface. Please someone with a picture to help me

**Comment by ds5678** [comment]
![image](https://github.com/user-attachments/assets/334da533-8cdd-4450-9b74-04ce60e9ec4f)
