### ISSUE TITLE
[Bug]: Last version, select folder button not working.

### ISSUE THREAD

**Issue by LuckyMenOrNot** [AssetRipper/AssetRipper#1551]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

-

### Which Unity version did this occur on?

-

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

select folder dont work

**Comment by LuckyMenOrNot** [comment]
запишу тогда видео

**Comment by LuckyMenOrNot** [comment]
https://github.com/user-attachments/assets/d077c6c8-ce2c-4014-9f48-b6e76adc2e76

**Comment by ds5678** [comment]
It looks like Vue isn't downloading for you.

**Comment by ds5678** [comment]
> запишу тогда видео

Я не говорю по-русски.

**Comment by LuckyMenOrNot** [comment]
Sorry, I wrote this automatically. is there a solution to this problem? Of course, I could insert the path, but doing this all the time is a little inconvenient

> > запишу тогда видео
> 
> Я не говорю по-русски.

**Comment by ds5678** [comment]
You could use a VPN if it's being regionally blocked. You can also provide Vue locally with a command line argument.

**Comment by LuckyMenOrNot** [comment]
It's working! thank you, I turned on the program to fix YouTube and Discord, which are blocked, apparently it was turned on before, so I didn’t see such a problem before

**Comment by ds5678** [comment]
You're welcome
