### ISSUE TITLE
[Other]: Please run a Performance Profile on `Master of Garden`

### ISSUE THREAD

**Issue by TheEvilSocks** [AssetRipper/AssetRipper#1555]
**Game:** https://www.crunchyroll.com/games/eminenceinshadow
Launch the game, this will download some base data. 
After getting through the download head over to the menu in the bottom right and select "Batch Download" to download the rest of the assets.
Assets will be located in `AppData\LocalLow\Unity\Crunchyroll Games LLC_MasterofGarden`

### Describe the issue
Exporting of any `AnimationPlayableAsset` takes several seconds.
My current observation occurred after 30+ hours of exporting

**Comment by TheEvilSocks** [comment]
I cancelled the previous attempt after 60ish hours 😅, and made a local change to have it ignore any collection that starts with `animation` during export. This has brought down the import+export time to 8 hours.

**Comment by ds5678** [comment]
I loaded the assets. That took an hour and a half; I will profile import later and see if there's any hot spots that can be improved.

Then, I profiled 20 minutes of primary content extraction. These were the results:

* GLB prefabs and scenes: 44.6%
* Images: 25.0%
* Json: 17.4%
  * Animation clips seem to be about 92% of this, or 15.9% of the total.
* GLB meshes: 7.9%
* Log statements: 2.5%
* `FileSystem.GetUniqueName`: 1.4%
  * This is almost entirely `File.Exists` and `Directory.Exists`.

In terms of improvements, GLB and image export are more-or-less as good as they're going to get for now. However, the others can be improved by excluding certain asset types from export:

* All animation assets
* `ComputeShader`
* `Material`
* `MonoBehaviour`s
* `PreloadData`
* `SceneAsset`
* `SpriteInformationObject`

> Exporting of any AnimationPlayableAsset takes several seconds.

I did not notice this in my profile. Perhaps it only happens after a significant amount have been created?

**Comment by Prosopho** [comment]
You did mention only doing primary content where they likely exported unity project. Perhaps should've tried doing that as well?

**Comment by ds5678** [comment]
> You did mention only doing primary content where they likely exported unity project. Perhaps should've tried doing that as well?

I actually tried unity project export first, and it completely finished in 3 hours. Then, I reached out on discord and discovered that they were using primary content extraction.
