### ISSUE TITLE
"Post-Export" How do i make it so it fully exports?

### ISSUE THREAD

**Issue by vnh-jpg** [AssetRipper/AssetRipper#1556]
### Describe the issue

When i try assetripping a unity game with the unity project button it just says at the end "Post-export finished" and when i check the files they are still in .META, .ASSET and others. How do i fix this???

**Comment by vnh-jpg** [comment]
i want to make it full export

**Comment by ds5678** [comment]
You sound like you want primary content instead of a unity project.
