### ISSUE TITLE
Improve Dataless Font Export

### ISSUE THREAD

**Issue by modusc896d352** [AssetRipper/AssetRipper#1570]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Chinese iOS version of Zombiegal Kawaii (Bēnghuài Xuéyuán). likely no longer available from the Apple App Store, but worldwide iOS version is still up.

### Which Unity version did this occur on?

4.3.2f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

all i had to do was to export Unity assets as "primary assets" to a folder of my choice and wait for everything to be exported into a folder.

however, of basically everything that was exported from Unity data, only fonts didn't "make the cut".

### Relevant log output

[AssetRipper.log](https://github.com/user-attachments/files/17967640/AssetRipper.log)

**Comment by ds5678** [comment]
Not really a bug because those fonts just have no data, but I can make them export as json instead of exporting nothing.

**Comment by modusc896d352** [comment]
might as well tbh

**Comment by ds5678** [comment]
Implemented in 57fb1336b3a3fc5f0974fce0b6fa664071fe4004
