### ISSUE TITLE
[Enhancement]: offline functionality

### ISSUE THREAD

**Issue by ChainSwordCS** [AssetRipper/AssetRipper#1586]
### Describe the new feature or enhancement

I tried using AssetRipper Free v1.1.7 while not connected to the internet, and it seemed like it only half worked.

The following files failed to load, as they are retrieved from cdn.jsdelivr.net:
- bootstrap.min.css
- bootstrap.bundle.min.js
- popper.min.js

I suspect it's probably possible to include these files in the binary release, either bundled in the executable or alongside it, hence this feature request.

**Comment by ds5678** [comment]
`--local-web-file`

**Comment by QJJXK555** [comment]
@ds5678 What parameters follow this option --local-web-file?

**Comment by ds5678** [comment]
--help

**Comment by QJJXK555** [comment]
@ds5678 I don't know what “local-web-file” is, I tried like this but it doesn't work offline
![image](https://github.com/user-attachments/assets/c04bc1dc-94ad-41d9-8904-cb6f40f314b9)

**Comment by ds5678** [comment]
eg `--local-web-file path/to/bootstrap.min.css`
