### ISSUE TITLE
[Bug]: AssetRipper Windows x64 v1.1.8.0.  Download Failed Virus Detect by Windows Security

### ISSUE THREAD

**Issue by DEVMX-JAAB-AS** [AssetRipper/AssetRipper#1587]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

N/A

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

I can't download AssetRipper v1.1.8.0. Microsoft Defender Antivirus Detects a Serious Trojan Named: Trojan:Script/Wacatac.B!ml
![2024-12-09 (3)](https://github.com/user-attachments/assets/3016dd79-e1c6-436e-847e-edcf03faa2bd)

**Comment by DEVMX-JAAB-AS** [comment]
Please Fix

**Comment by ds5678** [comment]
It's nothing to worry about. Windows always does that after a release because it hasn't encountered that binary enough. If you're really concerned, drop it into something like VirusTotal.

**Comment by DEVMX-JAAB-AS** [comment]
Ok later I'll download it again. Well, first I'm going to download Asset Ripper Premium since yesterday I subscribed to their Patreon again

**Comment by ds5678** [comment]
Thank you for the subscription.

I'm closing this as not a software issue. Feel free if you suspect otherwise.
