### ISSUE TITLE
[Bug]: Unreadable steaming assets

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#1604]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

pummel party

### Which Unity version did this occur on?

2021.3.30

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Hello ;)

After I load the game (_data folder), when i go to see the loaded files, all assets appear as unreadable:
example1:
![Unreadable](https://github.com/user-attachments/assets/e0da103d-bc93-48e9-ad9a-149f1752c187)

example2:
![Screenshot 2024-12-18 155943](https://github.com/user-attachments/assets/4d150bca-16ff-4cd3-b8ab-412c855ff522)

log file doesn't show anything relevant -no warnings, no errors...

any ideas ?

Kind regards,
Zbuffer

**Comment by ds5678** [comment]
This should have been a discussion, but anyway, the bundle Unity version was stripped. There's a field in the settings called `Default Version`. Set it to the correct version and your bundle will load.

**Comment by Zbuffers** [comment]
Sorry for the misplaced post.

Works like a charm after setting the default version ;) yay :)
Thaks for the quick replay

**Comment by Coolkatisa** [comment]
How do I find out what version of unity to use for specific games?

**Comment by ds5678** [comment]
> How do I find out what version of unity to use for specific games?

The whole point of version stripping is to make this harder. You might be able to find out by looking at exe properties. Alternatively, you could just guess until everything loads without errors.
