### ISSUE TITLE
[Question]: cant extract those files 

### ISSUE THREAD

**Issue by Anonymouse2400** [AssetRipper/AssetRipper#1622]
### Question

ive looked the contents via your app 
![image](https://github.com/user-attachments/assets/c5086308-2777-4a80-98f4-9ab4977585d0)
![image](https://github.com/user-attachments/assets/e07f8884-bbb9-4830-975f-4acf17243e89)
![image](https://github.com/user-attachments/assets/f7bc73b4-66c3-440b-900a-2938aac667ac)

but theres no asset being extracted 
![image](https://github.com/user-attachments/assets/17e592f0-e5b2-445d-9cd7-5e6bbf3c40bd)

the game streaming asset is using unity 5.5.5f1

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by ds5678** [comment]
Your bundle contains nothing, so nothing is exported.

**Comment by Anonymouse2400** [comment]
> Your bundle contains nothing, so nothing is exported.

hello do i need to get assetbundlemanifest to make it work on the project im decompiling or its optional cause i this post is im tryign to get to extract the assetbundlemanifest thanks and happy new year

**Comment by ds5678** [comment]
`AssetBundle` and `AssetBundleManifest` are useless, which is why AssetRipper excludes them from export.

**Comment by Anonymouse2400** [comment]
> `AssetBundle` and `AssetBundleManifest` are useless, which is why AssetRipper excludes them from export.

very thanks for this now i dont have to think of any issues involving those manifesst thanks again for the replay and happy new year
