### ISSUE TITLE
[Enhancement]: Version-Specific Assembly Generation

### ISSUE THREAD

**Issue by ds5678** [AssetRipper/AssetRipper#164]
### Describe the new feature or enhancement

The [AssemblyDumper](https://github.com/ds5678/AssemblyDumper) will be used to create version-specific assemblies from the information in the [TypeTreeDumps](https://github.com/ds5678/TypeTreeDumps) repository.

This will allow:
* Reading any asset type
* Reading assets for any supported version
* Exporting to the original version instead of `2017.3.0f1`

This is a planned feature for the `0.2.0.0` release.

**Comment by vale7z4387ruwrejmhsr** [comment]
this is already planned? ok great
