### ISSUE TITLE
[Bug]: SerializedFile with index ______ was not found in dependencies

### ISSUE THREAD

**Issue by acap09** [AssetRipper/AssetRipper#172]
### Describe the issue

I got this error: **Failed to export game content: SerializedFile with index 1065353215 was not found in dependencies**

How to fix this? (Export all files)

**Comment by ds5678** [comment]
This is an issue I'm currently tracking. If you're looking for a quick fix, disabling streaming assets often resolves this issue at the expense of not exporting any assets from that folder.

**Comment by sp00ktober** [comment]
[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7613181/AssetRipper.log)
Just wanted to add mine, same issue different index.

**Comment by dan771** [comment]
[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7709276/AssetRipper.log)
I had same error too @ds5678

**Comment by dan771** [comment]
@ds5678 has there been a fix yet the, deleting streaming assets did not work for me

**Comment by ds5678** [comment]
You can try again with an alpha build. There was a bug in `0.1.8.1` preventing that button in the settings menu from working.

**Comment by dan771** [comment]
> You can try again with an alpha build. There was a bug in `0.1.8.1` preventing that button in the settings menu from working.
[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7779054/AssetRipper.log)

Nope didnt work still. Is there any other asset rippers out here compatable with Unity 2020 that isn't asset studio?

**Comment by ds5678** [comment]
If you're only interested in programs that produce usable Unity projects, then I'm not aware of anything else that could help you.

**Comment by sp00ktober** [comment]
> > You can try again with an alpha build. There was a bug in `0.1.8.1` preventing that button in the settings menu from working.
> 
> [AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7779054/AssetRipper.log) Nope didnt work still (also tried with disableing importing streaming assets too). Is there any other asset rippers out here compatable with Unity 2020 that isn't asset studio?

maybe try https://github.com/nesrak1/UABEA

**Comment by dan771** [comment]
> If you're only interested in programs that produce usable Unity projects, then I'm not aware of anything else that could help you.

I heard somewhere theres a way to change a few things in utinyripper to make that work with unity 2020?

**Comment by dan771** [comment]
> > > You can try again with an alpha build. There was a bug in `0.1.8.1` preventing that button in the settings menu from working.
> > 
> > 
> > [AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7779054/AssetRipper.log) Nope didnt work still (also tried with disableing importing streaming assets too). Is there any other asset rippers out here compatable with Unity 2020 that isn't asset studio?
> 
> maybe try https://github.com/nesrak1/UABEA

Thanks!

**Comment by ds5678** [comment]
> > If you're only interested in programs that produce usable Unity projects, then I'm not aware of anything else that could help you.
> 
> I heard somewhere theres a way to change a few things in utinyripper to make that work with unity 2020?

AssetRipper is a direct fork of uTinyRipper

**Comment by ds5678** [comment]
> > > You can try again with an alpha build. There was a bug in `0.1.8.1` preventing that button in the settings menu from working.
> > 
> > 
> > [AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7779054/AssetRipper.log) Nope didnt work still (also tried with disableing importing streaming assets too). Is there any other asset rippers out here compatable with Unity 2020 that isn't asset studio?
> 
> maybe try https://github.com/nesrak1/UABEA

Although UABEA is a wonderful tool, it does not produce Unity projects like I assumed dan771 was looking for.

**Comment by dan771** [comment]
> > > > You can try again with an alpha build. There was a bug in `0.1.8.1` preventing that button in the settings menu from working.
> > > 
> > > 
> > > [AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7779054/AssetRipper.log) Nope didnt work still (also tried with disableing importing streaming assets too). Is there any other asset rippers out here compatable with Unity 2020 that isn't asset studio?
> > 
> > 
> > maybe try https://github.com/nesrak1/UABEA
> 
> Although UABEA is a wonderful tool, it does not produce Unity projects like I assumed dan771 was looking for.

Ok, yea i am looking for unity project, how big of an issue is the bug here? Could it just be made to skip any objects that encounter this bug when exporting

**Comment by BabyWhite69** [comment]
I have the same problem with different index (215068240), I tried different versions since 1.7.2
[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7787234/AssetRipper.log)

**Comment by dan771** [comment]
> Ok, yea i am looking for unity project, how big of an issue is the bug here? Could it just be made to skip any objects that encounter this bug when exporting?

@ds5678

**Comment by ds5678** [comment]
> Ok, yea i am looking for unity project, how big of an issue is the bug here? Could it just be made to skip any objects that encounter this bug when exporting?

It's a big enough issue that it shouldn't be ignored. I've been focused on other portions of the project and haven't had time to look into this. However, if you so desire, you can modify the AssetRipper source to force it to continue.

**Comment by dan771** [comment]
> > Ok, yea i am looking for unity project, how big of an issue is the bug here? Could it just be made to skip any objects that encounter this bug when exporting?
> 
> It's a big enough issue that it shouldn't be ignored. I've been focused on other portions of the project and haven't had time to look into this. However, if you so desire, you can modify the AssetRipper source to force it to continue.

Ok i haven't really looked through any of the code rlly, can u give me an overview of where things are etc.

**Comment by dan771** [comment]
im guessing i just delete `throw new Exception($"{nameof(SerializedFile)} with index {fileIndex} was not found in dependencies");` in AssetRipper-master\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs

**Comment by dan771** [comment]
and then also how do i build it to work with GUI console?

**Comment by ds5678** [comment]
I just pushed fb461671ffe845d46591f99d3fa01138393947b4 which may help some of you

**Comment by dan771** [comment]
> I just pushed [fb46167](https://github.com/AssetRipper/AssetRipper/commit/fb461671ffe845d46591f99d3fa01138393947b4) which may help some of you

Worked for me!

**Comment by ds5678** [comment]
With #164 done, this should no longer be an issue. If it is, post a new issue.
