### ISSUE TITLE
[Bug]: Failed to load game content: Non-negative number required. (Parameter 'capacity')

### ISSUE THREAD

**Issue by Paddymancer** [AssetRipper/AssetRipper#175]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2020.1.15f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Getting a "Failed to load game content: Non-negative number required. (Parameter 'capacity')" error when selecting/dragging game folder with AssetRipper. 

### Relevant log output

[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7595264/AssetRipper.log)

**Comment by AestheticalZ** [comment]
Same issue here, but with Bloons TD6.

**Comment by ds5678** [comment]
I'll take a peak, but no promises

**Comment by ds5678** [comment]
I am able to reproduce the problem on BTD6

**Comment by ds5678** [comment]
Fixed in 4b75e12b6ce6560587f531f63148014ba0b7c996

However BTD6 still suffers from #281
