### ISSUE TITLE
[Enhancement]:  RAM limit

### ISSUE THREAD

**Issue by BurAndBY** [AssetRipper/AssetRipper#185]
### Describe the new feature or enhancement

Make a setting that will be able to limit RAM amount. Sometimes AssetRipper just uses 99% of RAM. I want to make limit of ram like using only 3GB out of 6GB.
![image](https://user-images.githubusercontent.com/48630651/143835538-1d9768b5-699a-4b59-a7d4-27ec06575449.png)

**Comment by ds5678** [comment]
This is currently an infeasible request since AssetRipper has to decompress the entire game into RAM.

**Comment by ds5678** [comment]
Although I'm always looking for ways to improve performance, including RAM usage, there probably won't ever be 1 singular fix, so I'm going to close this.
