### ISSUE TITLE
[Question]: Mac Directions to Launch Executable

### ISSUE THREAD

**Issue by RumitKmphitech** [AssetRipper/AssetRipper#224]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version MacOS x64

### Which Unity version did this occur on?

2020

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

How to open assetsRipper in macos please make a video or tips 
Thanks..

**Comment by ds5678** [comment]
You're most likely having issues because Mac thinks the file isn't executable. I don't have a Mac but I think there might be a file property for that. If there isn't a file property, you should be able to do it with `chmod +x AssetRipper` in a terminal.

**Comment by ds5678** [comment]
inactivity
