### ISSUE TITLE
[Bug]: Failed to export game content: Mono.Cecil.CustomAttributeArgument[]

### ISSUE THREAD

**Issue by GUEST-1001** [AssetRipper/AssetRipper#225]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2017.3.0f3

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Export all file and got error "Failed to export game content: Mono.Cecil.CustomAttributeArgument[]"
https://youtu.be/d8QzsiFA4F4

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/7839364/AssetRipper.log)

**Comment by ds5678** [comment]
Closed in favor of #227

**Comment by ds5678** [comment]
As a work-around, you can disable script export
