### ISSUE TITLE
[Bug]: tried to rip limitless, this error happened

### ISSUE THREAD

**Issue by fajnygosciu1234** [AssetRipper/AssetRipper#231]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

not applicable

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

when trying to export all files from limitless crazygames webgame, this happens "Failed to export game content: Value was either too large or too small for an unsigned byte."

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/7877483/AssetRipper.log)

**Comment by fajnygosciu1234** [comment]
after it extracted "BoxDefuse" assetripper gave up and gave me the error

**Comment by ds5678** [comment]
fixed in 759c559e504298134b418eac81ee2a27fd9f4fcd

**Comment by fajnygosciu1234** [comment]
i want the official release to fix this, since i do not want to build it myself

**Comment by ds5678** [comment]
> i want the official release to fix this, since i do not want to build it myself

Ignoring your ungrateful tone, there are links here to the latest automated builds of AssetRipper.

https://assetripper.github.io/AssetRipper/articles/Downloads.html#alpha-builds-
