### ISSUE TITLE
[Bug]: The exported animation resource has only one frame

### ISSUE THREAD

**Issue by qq1035732175** [AssetRipper/AssetRipper#253]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

all versions

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I exported KOF All star and several other games, the character animation is abnormally large, (I don't know if it is normal), the animation is only one frame, the others are all blank, the unpacking export does not show any errors, it only appears in the latest version 0.19 , I use 0.18.1 the animation works fine！

**Comment by ds5678** [comment]
I'm focused on other things at the moment. However, I discovered that 3cfa53b4a43338c4409022e8e0bf3d0ee63a8e4a is responsible for this regression. If you would like to work on this, I would happily accept a pull request for it.

**Comment by qq1035732175** [comment]
Of course
