### ISSUE TITLE
[Bug]: Error during reading asset type Shader 

### ISSUE THREAD

**Issue by skyline9394** [AssetRipper/AssetRipper#258]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest build of AssetRipper. 0.1.9.1

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

![Capture111](https://user-images.githubusercontent.com/23480817/152738462-8f88c46a-5364-4783-9f67-f347588dcbbd.PNG)

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Error during reading of asset type Shader. V: 2021.1.10f1 P: StandaloneWin64Player N: unity default resources Path: G:\Program Files (x86)\Initial Unity\Initial Unity_Data\Resources\unity default resources
System.NullReferenceException: Object reference not set to an instance of an object.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8012950/AssetRipper.log)

**Comment by ds5678** [comment]
Thank you for reporting this. It was a simple fix

**Comment by skyline9394** [comment]
how can i fix it?

**Comment by ds5678** [comment]
You don't have to do anything except download a new alpha build

**Comment by skyline9394** [comment]
ok thx
