### ISSUE TITLE
[Bug]: assetripper connsol wont launch at all

### ISSUE THREAD

**Issue by TheBestFudge** [AssetRipper/AssetRipper#263]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Console Version Windows x64

### Which Unity version did this occur on?

2019.4.31f1

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

hye sorry nnot sure if it's mono or il2cpp It's vrc but I dont thi kit's relavent sice I cat eve run the consol. it looks like it just opens a cmd window and the emidietly closes itself

**Comment by SamboyCoding** [comment]
That's how the console version works? It's designed to be used from a console. If you want a UI, download the GUI version

**Comment by TheBestFudge** [comment]
oh sorry I'm a bit dumb xd
