### ISSUE TITLE
[Bug]: Cpp2IlInjected.AnalysisFailedException("CPP2IL failed to recover any usable IL for this method.");

### ISSUE THREAD

**Issue by SALAZARDev29** [AssetRipper/AssetRipper#270]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.2.20 Or Or Higher

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

![1](https://user-images.githubusercontent.com/99881562/154478625-d0f0dcdf-7a77-431a-b467-7f85b016cc29.PNG)

**Comment by ds5678** [comment]
Please report any Cpp2IL issues on the [Cpp2IL](https://github.com/SamboyCoding/Cpp2IL) repository.
