### ISSUE TITLE
[Enhancement]: Cpp2IlInjected.AnalysisFailedException("CPP2IL failed to recover any usable IL for this method.");

### ISSUE THREAD

**Issue by SALAZARDev29** [AssetRipper/AssetRipper#271]
### Describe the new feature or enhancement

![1](https://user-images.githubusercontent.com/99881562/154480863-88a0c753-baa4-45bf-9ce3-f2325a26d185.PNG)

**Comment by ds5678** [comment]
AssetRipper has no ability to resolve this. It just uses the Cpp2IL nuget package. Please redirect any Cpp2IL issues/enhancements to the [Cpp2IL](https://github.com/SamboyCoding/Cpp2IL) repository.
