### ISSUE TITLE
[Bug] Audio export issues

### ISSUE THREAD

**Issue by 0-Satanael** [AssetRipper/AssetRipper#278]
Issue:
when it comes to extracting Audio It is the best however it can't find all assets i had to use AssetStudio instead and it was able to find all Audio Assets. the game was Master Duel it is free game. i hope to fix it.

Log:
System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.22000.0
System : Operating System: Windows x64
System : AssetRipper Version: 0.1.9.3
System : AssetRipper Build Type: Release x64 Published
System : UTC Current Time: 2/24/2022 7:42:31 AM
System : UTC Compile Time: Thu Feb 17 09:36:14 UTC 2022
VersionManager : Loading version handlers...
VersionManager : No assemblies to load.
Plugin : Loading plugins...
Plugin : Finished loading plugins.
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : IgnoreStreamingAssets: False
General : ExportPath: D:\Downloads\New folder (2)\AssetRipperGUI_win64\Ripped
General : ExportDependencies: False
General : IgnoreAssetBundleContentPaths: False
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshCoordinateSpace: Unity
General : MeshExportFormat: Native
General : ScriptExportMode: Decompiled
General : ScriptLanguageVersion: AutoSafe
General : SpriteExportMode: Native
General : TerrainExportMode: Native
General : TextExportMode: Parse
General : Attempting to read files from D:\Games\SteamLibrary\steamapps\common\Yu-Gi-Oh!  Master Duel
Import : PC game structure has been found at 'D:\Games\SteamLibrary\steamapps\common\Yu-Gi-Oh!  Master Duel'
Import : Collecting game files...
Import : Asset bundle 'data.unity3d' has been found
Import : Collecting Streaming Assets...
Import : Asset bundle '0022d818' has been found
Import : Asset bundle '04542ccc' has been found
Import : Asset bundle '07287401' has been found
Import : Asset bundle '0734444a' has been found
Import : Asset bundle '080892d9' has been found
Import : Asset bundle '0897767a' has been found
Import : Asset bundle '09b1a0a5' has been found
Import : Asset bundle '09c9fc2b' has been found
Import : Asset bundle '0a575018' has been found
Import : Asset bundle '0ab0e835' has been found
Import : Asset bundle '0f7a624e' has been found
Import : Asset bundle '1048d961' has been found
Import : Asset bundle '111cba7a' has been found
Import : Asset bundle '132e458a' has been found
Import : Asset bundle '136f1dd9' has been found
Import : Asset bundle '140b4328' has been found
Import : Asset bundle '1710b8f9' has been found
Import : Asset bundle '1732a032' has been found
Import : Asset bundle '17d470ff' has been found
Import : Asset bundle '192ac0f0' has been found
Import : Asset bundle '1935f47e' has been found
Import : Asset bundle '1ad951f2' has been found
Import : Asset bundle '1c37d0e8' has been found
Import : Asset bundle '1f04dab8' has been found
Import : Asset bundle '2007f50a' has been found
Import : Asset bundle '260bf789' has been found
Import : Asset bundle '26f9597c' has been found
Import : Asset bundle '286ce798' has been found
Import : Asset bundle '2902f3fc' has been found
Import : Asset bundle '2ad49d74' has been found
Import : Asset bundle '2fbdbba2' has been found
Import : Asset bundle '30b9a1c9' has been found
Import : Asset bundle '3199f41c' has been found
Import : Asset bundle '35da6e55' has been found
Import : Asset bundle '3941ac53' has been found
Import : Asset bundle '3957c929' has been found
Import : Asset bundle '3de6fd95' has been found
Import : Asset bundle '3f8966d6' has been found
Import : Asset bundle '42192615' has been found
Import : Asset bundle '43578128' has been found
Import : Asset bundle '47d6e0bd' has been found
Import : Asset bundle '4a131491' has been found
Import : Asset bundle '4e4a81e2' has been found
Import : Asset bundle '4eb85870' has been found
Import : Asset bundle '5212bb01' has been found
Import : Asset bundle '5241aeb0' has been found
Import : Asset bundle '59a015e5' has been found
Import : Asset bundle '6286ac55' has been found
Import : Asset bundle '68bedd5a' has been found
Import : Asset bundle '6ab0a1b8' has been found
Import : Asset bundle '6b71cf4a' has been found
Import : Asset bundle '6c0f22fa' has been found
Import : Asset bundle '6ec828c5' has been found
Import : Asset bundle '704431b0' has been found
Import : Asset bundle '71996f09' has been found
Import : Asset bundle '7255b2c0' has been found
Import : Asset bundle '746ca9b9' has been found
Import : Asset bundle '7729f5a9' has been found
Import : Asset bundle '7735c949' has been found
Import : Asset bundle '78fd82f5' has been found
Import : Asset bundle '803ca5c4' has been found
Import : Asset bundle '82973d9d' has been found
Import : Asset bundle '84bdc451' has been found
Import : Asset bundle '86802243' has been found
Import : Asset bundle '86b0bc76' has been found
Import : Asset bundle '87dea812' has been found
Import : Asset bundle '898ae9ef' has been found
Import : Asset bundle '8b8b47f3' has been found
Import : Asset bundle '9063013c' has been found
Import : Asset bundle '9091d8ae' has been found
Import : Asset bundle '9166ab63' has been found
Import : Asset bundle '9169b281' has been found
Import : Asset bundle '91be9499' has been found
Import : Asset bundle '951617a1' has been found
Import : Asset bundle '96f3e3d9' has been found
Import : Asset bundle '9755e52b' has been found
Import : Asset bundle '9c77b68e' has been found
Import : Asset bundle '9eb790ec' has been found
Import : Asset bundle 'a6f77eab' has been found
Import : Asset bundle 'aac6fd8f' has been found
Import : Asset bundle 'aba43fd0' has been found
Import : Asset bundle 'b0b7861e' has been found
Import : Asset bundle 'b1a73a99' has been found
Import : Asset bundle 'b2e26a22' has been found
Import : Asset bundle 'b4c73adc' has been found
Import : Asset bundle 'b8d3fa09' has been found
Import : Asset bundle 'bbe1e375' has been found
Import : Asset bundle 'be1838e2' has been found
Import : Asset bundle 'be2e25dd' has been found
Import : Asset bundle 'c0fa51ee' has been found
Import : Asset bundle 'c6b51cd7' has been found
Import : Asset bundle 'c77776e0' has been found
Import : Asset bundle 'c7d4ad2a' has been found
Import : Asset bundle 'c867b276' has been found
Import : Asset bundle 'c91f0874' has been found
Import : Asset bundle 'ca210c2f' has been found
Import : Asset bundle 'd22620b5' has been found
Import : Asset bundle 'd60d7765' has been found
Import : Asset bundle 'd7c30075' has been found
Import : Asset bundle 'd80843a7' has been found
Import : Asset bundle 'e12b0bf4' has been found
Import : Asset bundle 'e1740362' has been found
Import : Asset bundle 'e2231290' has been found
Import : Asset bundle 'e250b478' has been found
Import : Asset bundle 'e4242169' has been found
Import : Asset bundle 'e45f7922' has been found
Import : Asset bundle 'e54ed689' has been found
Import : Asset bundle 'e6a65b9d' has been found
Import : Asset bundle 'e76431aa' has been found
Import : Asset bundle 'e8e77bdf' has been found
Import : Asset bundle 'e9760459' has been found
Import : Asset bundle 'f55e9c97' has been found
Import : Asset bundle 'f5d19e44' has been found
Import : Asset bundle 'f6c29b36' has been found
Import : Asset bundle 'f6f5e242' has been found
Import : Asset bundle 'f7378875' has been found
Import : Asset bundle 'f7385a8b' has been found
Import : Asset bundle 'f74cd03e' has been found
Import : Asset bundle 'f7926cce' has been found
Import : Asset bundle 'fc6e839b' has been found
Import : Files use the 'Il2Cpp' scripting backend.
Import : During Il2Cpp initialization, found Unity version: 2020.3.18
Cpp2IL : Initializing Metadata...
Cpp2IL : Using actual IL2CPP Metadata version 27.1
Cpp2IL : Initialized Metadata in 618ms
Cpp2IL : Searching Binary for Required Data...
Cpp2IL : Got Binary codereg: 0x181A3B1A0, metareg: 0x181A41BB0 in 1182ms.
Cpp2IL : Initializing Binary...
Cpp2IL : Initialized Binary in 386ms
Cpp2IL : Mapping pointers to Il2CppMethodDefinitions...
Cpp2IL : Processed 65592 OK (90ms)
Cpp2IL : Building assemblies...This may take some time.
Cpp2IL : Finished Building Assemblies in 1600ms
Cpp2IL : Fixing up explicit overrides. Any warnings you see here aren't errors - they usually indicate improperly stripped or obfuscated types, but this is not a big deal. This should only take a second...
Cpp2IL : Fixup complete (127ms)
Import : During Il2Cpp initialization, found X86_64 instruction set.
Import [Warning] : Assembly 'Unity.ShaderGraph.Editor' hasn't been found
Import [Warning] : Unable to read Sub_RGBA_Channel_Selection, because valid definition for script SubGraphAsset wasn't found
Import [Warning] : Unable to read UnlitReceiveShadow_ShadowCoordToAtten, because valid definition for script SubGraphAsset wasn't found
Import [Warning] : Unable to read Sub_SmoothstepBlur, because valid definition for script SubGraphAsset wasn't found
Import [Warning] : Unable to read Sub_TilingScrollOffset, because valid definition for script SubGraphAsset wasn't found
Import [Warning] : Unable to read Sub_SoftParticle, because valid definition for script SubGraphAsset wasn't found
Import [Warning] : Unable to read Sub_gradient linear, because valid definition for script SubGraphAsset wasn't found
General : Finished reading files

**Comment by ds5678** [comment]
I'll take a look

**Comment by ds5678** [comment]
I am able to reproduce your issue

**Comment by 0-Satanael** [comment]
> I am able to reproduce your issue

I Tried the latest version issue still persists.
as you can see Asset Ripper was able to find 265 Only
![Untitled1](https://user-images.githubusercontent.com/40186693/156420497-ee03f6fc-46ff-4798-800e-424d90b68b74.png)
Asset Studio found 731
![Untitled2](https://user-images.githubusercontent.com/40186693/156420618-42a377e6-ddf4-4386-85d1-bff231743a48.png)

**Comment by ds5678** [comment]
I know. I haven't had time to focus on this issue. Issue reproduction only means that the same thing happened on my machine.

**Comment by ds5678** [comment]
I revisited this and discovered that there are no missing audio clips. AssetStudio finds the same number (265) as AssetRipper. Your 731 number is user error.
