### ISSUE TITLE
[Bug]: Failure to extract *.bundle file

### ISSUE THREAD

**Issue by Doc-4** [AssetRipper/AssetRipper#280]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

EXE version 2020.3.0.13088070
UABE method failed, presumably unity version too new for it? I do have the appropriate redists, so it's not that.

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Nothing found in what I'm certain is the file where at the very least the soundtrack is loaded from. I used procmon to trace the read file operations to it. I've logged both loading the executable and the *.bundle file separately. The former returns a bunch of assets, none of which seemed to be relevant at a glance, the latter returns a message that nothing at all was found. My guess is it's not accessing any of the *.bundle files correctly, and all of the notable assets are in those. (the unity application is a container for the soundtrack and art assets that came with the deluxe version of Melty Blood Lumina)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8142059/AssetRipper.log)
[AssetRipper2.log](https://github.com/AssetRipper/AssetRipper/files/8142060/AssetRipper2.log)

**Comment by ds5678** [comment]
Do [UABEA](https://github.com/nesrak1/UABEA) or [AssetStudio](https://github.com/Perfare/AssetStudio) open it successfully?

Can you open the file in a [hex editor](https://hexed.it/) and take a screenshot of the top?

**Comment by ds5678** [comment]
Can you open the file in a [hex editor](https://hexed.it/) and take a screenshot of the top?

**Comment by Doc-4** [comment]
Yeah no problem, I figured that was for the version number as well, my mistake. I assume you want the EXE as the bundle is unreadable, but I included both
![EXEHex](https://user-images.githubusercontent.com/60247583/155844165-e7134157-f2fb-4e14-9dcd-c86ae656dffd.PNG)
![FileHex](https://user-images.githubusercontent.com/60247583/155844170-b1c6f5c5-e245-4c74-b352-f5b670a69cd5.PNG)
.

**Comment by Doc-4** [comment]
No, it doesn't recognize *.bundle files at all seemingly, UABEA worked for retrieving the unity version number

**Comment by ds5678** [comment]
I thought as much. Unfortunately, those bundles are encrypted.

**Comment by Doc-4** [comment]
Makes sense, the hex reads like nonsense. Is it possible to run the application with things attached to in some way dump the encryption keys or something of that nature? My knowledge of technology far exceeds my current ablity to code, sadly, or I'd have tried to do it myself. Unlike the similar soundtrack from the recently released elden ring, there's no way to export sound files in the application.

**Comment by ds5678** [comment]
It is possible to reverse engineer/dump the encryption keys. However, any approach (other than brute force) would be game-specific.

**Comment by ds5678** [comment]
Unless the developer is using a custom Unity engine, the decryption is likely being done by code in the game's assemblies.
