### ISSUE TITLE
[Question]: How to make a pull request?

### ISSUE THREAD

**Issue by vale7z4387ruwrejmhsr** [AssetRipper/AssetRipper#288]
### Describe the new feature or enhancement

i got the Inspiration from https://github.com/AssetRipper/AssetRipper/pull/283/commits and coded some stuff too for different components those being   AudioEchoFilter   AudioHighPassFilter    AudioChorusFilter   AudioDistortionFilter  StreamingController
 
so since i donno how jannify uploaded the files so you can see it so here is a zip file of the project 
https://www.mediafire.com/file/qekhbuy1d33kp0m/Assetripper_proj.zip/file

**Comment by ds5678** [comment]
I only accept changes via the pull request system. However, there are lots of resources to help you. In addition to the official guides and documentation, there are numerous blog posts detailing the process for first time contributors.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by ds5678** [comment]
I also have resources to help you with the support you're looking to add. Here is a zip file containing information about all the times that an asset structure has changed in format. The numbers inside correspond to ClassIDType. An empty file means that the asset type does not exist after that version.

[AllComparisons.zip](https://github.com/AssetRipper/AssetRipper/files/8173390/AllComparisons.zip)

**Comment by vale7z4387ruwrejmhsr** [comment]
ok i will create the pull request later
