### ISSUE TITLE
[Enhancement]: Don't export kBacking fields and compiler-generated classes

### ISSUE THREAD

**Issue by Panthr75** [AssetRipper/AssetRipper#290]
### Describe the new feature or enhancement

I was attempting to export the assets of GTFO with only fields so I can at least view the scripts and the fields associated with them, but I get over 9999+ compiler errors, mostly relating to kBacking fields being exported, and compiler-generated AsyncStateMachines being exported.

**Comment by ds5678** [comment]
Outside my control. This is either an issue with ILSpy or Cpp2IL. If you want less errors, reduce the script content level.

**Comment by Panthr75** [comment]
This was with Script Level 1, which should only export fields and basic types

**Comment by ds5678** [comment]
Discussion moved to #291
