### ISSUE TITLE
[Bug]: Script Stripping Bugs

### ISSUE THREAD

**Issue by Panthr75** [AssetRipper/AssetRipper#291]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.4.21f

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

When exporting a game (in this case GTFO) on Scripting Level 1 (Only fields), the exported enums that aren't from nested types are empty.

#### eEasingType
Exported code:
```cs
public enum eEasingType
{

}

```
Code from mono reference (Rundown 6 DNSpy)
```cs
using System;

public enum eEasingType
{
	Linear,
	EaseInQuad,
	EaseOutQuad,
	EaseInOutQuad,
	EaseInCubic,
	EaseOutCubic,
	EaseInOutCubic,
	EaseInQuart,
	EaseOutQuart,
	EaseInOutQuart,
	EaseInQuint,
	EaseOutQuint,
	EaseInOutQuint,
	EaseInSine,
	EaseOutSine,
	EaseInOutSine,
	EaseInExpo,
	EaseOutExpo,
	EaseInOutExpo,
	EaseInCirc,
	EaseOutCirc,
	EaseInOutCirc
}
```
#### ValueSmoother+SmootherType
Exported code:
```cs
using UnityEngine;

public class ValueSmoother
{
	public enum SmootherType
	{
		Vec3,
		Vec2,
		Float
	}
	// (extra code removed)
}
```
Code from mono reference (Rundown 6 DNSpy)
```cs
using System;
using UnityEngine;

public class ValueSmoother
{
	public enum SmootherType
	{
		Vec3,
		Vec2,
		Float
	}
	// (extra code removed)
}
```

**Comment by ds5678** [comment]
I am able to reproduce this.

**Comment by ds5678** [comment]
If you would like to work on this and #290, the relevant code is here:

https://github.com/AssetRipper/AssetRipper/blob/master/AssetRipperLibrary/Exporters/Scripts/MethodStripper.cs

**Comment by ds5678** [comment]
Here are the derived types of `EntityDeclaration`

![Screenshot 2022-03-02 194756](https://user-images.githubusercontent.com/49847914/156475218-2c8cc634-6f16-4141-8a06-173d6f9ad14d.png)

**Comment by Panthr75** [comment]
I also noticed that constructors don't get exported (which is fine, but exported attributes is where a problem arises)

**Comment by Panthr75** [comment]
Could we potentially create stub constructors?

**Comment by ds5678** [comment]
> I also noticed that constructors don't get exported (which is fine, but exported attributes is where a problem arises)

I'm focused on other sections of the project right now, so I'm happy to let you take the reins on this issue.

> Could we potentially create stub constructors?

I haven't used ILSpy's API much, so I don't know its full capabilities. The code in the file I mentioned above was based on a snippet from spacehampster:

https://github.com/icsharpcode/ILSpy/issues/2223#issuecomment-733413237

**Comment by Panthr75** [comment]
Almost got this somewhat workable. Exporting GTFO's scripts now only give 334 errors instead of 33,000

**Comment by Panthr75** [comment]
Okay it turns out it's a bit more complicated than that

Current todo (that I can think of at least):
- [x] Remove anything with `CompilerGenerated` attribute or `AsyncStateMachine` attribute
- [x] Remove fields with special names (e.g. `<DEBUG_ENABLED>k__backingField`)
- [x] Strip inner types
- [x] Dont strip enum member definitions from enums
- [x] Implement basic constructors stubs
- [ ] Ensure constructor stubs call valid base constructor
- [ ] Ensure struct fields are assigned in struct constructor stubs
- [ ] Ensure interfaces are properly implemented (generate method stubs if needed [e.g, `IDisposable` required `Dispose` method])
- [ ] Ensure abstract members are implemented (generate stubs for implementations)
- [ ] Switch `Optional` attribute out for assigning the value of the parameter to `default`
- [ ] Remove unresolved attributes (like Nullable and NullableContext, as these aren't supported in Unity)

**Comment by Panthr75** [comment]
> > Switch Optional attribute out for assigning the value of the parameter to default

> This is a Cpp2IL issue that's being worked on.

Do you know at what time it will be fixed? Or are we just gonna have to wait :(

**Comment by ds5678** [comment]
> Do you know at what time it will be fixed? Or are we just gonna have to wait :(

Sorry, I don't know

**Comment by ds5678** [comment]
@Panthr75 how's it going?

**Comment by Panthr75** [comment]
@ds5678 I've been busy with some IRL stuff, but as of now so I haven't really had time to work on this.
I can setup a fork as of now at least

**Comment by Panthr75** [comment]
Currently worked on another project for exporting the scripts properly with methods, but so it would compile (scripting level 2 i think) and I'll leave some of my discoveries here:

Scripting Level 2 does not:
- Set out parameters in exported methods
- Correctly return "null" for a generic type. should use `default!` instead of null
- Export Attributes on members correctly. Duplicate attributes (like obsolete) get exported frequently enough to make it a pain.
- Export Base Constructor calls
- Strip kBacking fields, Strip AsyncStateMachines, and their attributes.
- Export Auto-Properties (Properties with just `{ get; set; }`)
- Export StructLayout attribute correctly (Exports `StructLayout(0, ` instead of `StructLayout(LayoutKind.Sequential, `)

After looking at the exported GameAssemblies, it's clear why this is the case. It seems to be a problem with the IL getting exported.

**Comment by ds5678** [comment]
I assume your game is IL2Cpp. Scripting level 2 is just the default Cpp2IL output.

**Comment by Panthr75** [comment]
Yeah. I guess this is kind-of a Cpp2IL issue?

**Comment by ds5678** [comment]
> Yeah. I guess this is kind-of a Cpp2IL issue?

Indeed. Once the Cpp2IL rewrite reaches parity with the current version, we'll switch over.

**Comment by ds5678** [comment]
> We have a mono reference from a couple of updates ago. Maybe there could be a way to merge the mono and IL2CPP implementation?

Not possible to do inside AssetRipper. However, you could do external processing on the outputted game assemblies and rerip using those.

**Comment by Panthr75** [comment]
> Not possible to do inside AssetRipper. However, you could do external processing on the outputted game assemblies and rerip using those.

Problem is there are some genuine code changes between IL2CPP and mono. (e.g. GTFO added `MLSArrayDescriptorReferenceDataBlock`) Maybe it could serve as an intermediate Scripting Level 2/3 layer?

Question is if this should be part of ILSpy, or AssetRipper.

**Comment by Panthr75** [comment]
We still have to fix assetripper exporting compiler-generated code, though

**Comment by Panthr75** [comment]
Take for example `PlayFabClientAPI` from GTFO. This gets exported: https://gist.github.com/Panthr75/7af12b64b44041c6dc50ed6a52d5c107

**Comment by ds5678** [comment]
> Question is if this should be part of ILSpy, or AssetRipper.

Neither. Assembly filling should be its own thing. If there's sufficient demand for it, I'll consider making it sometime after the new gui and implement it into AssetRipper as a library

**Comment by ds5678** [comment]
> We still have to fix assetripper exporting compiler-generated code, though

If Cpp2IL is improved, ILSpy will do this automatically.

**Comment by Panthr75** [comment]
Do you use a fork of Cpp2IL by chance?

**Comment by ds5678** [comment]
> Do you use a fork of Cpp2IL by chance?

No, AssetRipper uses the Cpp2IL nuget package. Why do you ask?

**Comment by Panthr75** [comment]
Just out of curiosity if we could start a fork once Cpp2IL gets updated

**Comment by ds5678** [comment]
There are only a few situations in which I would consider making an AssetRipper fork of Cpp2IL.
1. It becomes a requirement for NativeAOT in AssetRipper.
2. Sam and I somehow encounter irreconcilable creative differences.
3. Sam decides to pause or cease development of Cpp2IL.

**Comment by ds5678** [comment]
A quick note: script export in AssetRipper uses the ILSpy decompiler differently than it uses itself. Some example code can be found here:

https://github.com/icsharpcode/ILSpy/blob/d5be62eb80513cfa10aa362655867ce28508fd82/ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs#L203-L250

Mirroring this implementation would likely lead to improved script export and faster decompile times.
