### ISSUE TITLE
Error during reading of asset type AnimationClip. V: 2018.4.24f1

### ISSUE THREAD

**Issue by NiezSellami** [AssetRipper/AssetRipper#311]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version MacOS x64

### Which Unity version did this occur on?

2018.4.24f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

[Error] : Error during reading of asset type AnimationClip. V: 2018.4.24f1 P: StandaloneWin64Player N: sharedassets0.assets Path: sharedassets0.assets
System.Exception: End of stream. Read 35268, expected 1114636288 elements
 ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8248170/AssetRipper.log)

**Comment by ds5678** [comment]
Your game uses a custom version of Unity with nonstandard asset structures.
