### ISSUE TITLE
[Bug]: Cannot Export, Failed to resolve UnityEngine.Camera

### ISSUE THREAD

**Issue by QuinnBast** [AssetRipper/AssetRipper#325]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

Unity 5.6.2.0

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

After importing all of the files from the game, Asset ripper is unable to export the files.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8320097/AssetRipper.log)

**Comment by ds5678** [comment]
Get rid of your duplicate assemblies and try again

**Comment by ds5678** [comment]
closed because of inactivity
