### ISSUE TITLE
[Bug]: There is no curve with index 0 in any of previous frames

### ISSUE THREAD

**Issue by Virjoinga** [AssetRipper/AssetRipper#327]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

4.3.1f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

AssetRipper throws an error when trying to export certain animation clips.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8327715/AssetRipper.log)

**Comment by ds5678** [comment]
From Discord: "this bug was introduced sometime between `0.1.8.1` and `0.1.9.0`."

**Comment by Virjoinga** [comment]
Can't seem to find which version this occurs in first or when it wasn't an issue. To my knowledge (after downloading multiple releases) it seems to have always been a problem. This bug still occurs on the latest release, 0.3.2.1.

**Comment by Virjoinga** [comment]
sorry accident

**Comment by Bebop182** [comment]
Same issue on my end on v0.3.4.0 for a unity project in version 4.6.5
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12707507/AssetRipper.log)

**Comment by ds5678** [comment]
#1210 made some changes which might have resolved your issue. Can you re-rip your project with the latest continuous integration build and verify that the issue is indeed resolved?

**Comment by Virjoinga** [comment]
> #1210 made some changes which might have resolved your issue. Can you re-rip your project with the latest continuous integration build and verify that the issue is indeed resolved?

It has been resolved:
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/14467414/AssetRipper.log)
