### ISSUE TITLE
[Bug]: Unauthorized File Access

### ISSUE THREAD

**Issue by aragornsquid** [AssetRipper/AssetRipper#330]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.4.31f1.12409535

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

it gets like 20% there and will then error and stop extracting

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8346212/AssetRipper.log)

**Comment by ds5678** [comment]
From the .NET documentation, either the caller does not have the required permission, the path specified a file that is read-only, or the path specified a file that is hidden.

**Comment by aragornsquid** [comment]
is there a way to fix this?

**Comment by ds5678** [comment]
It's most likely not a problem in AssetRipper

**Comment by aragornsquid** [comment]
So its something with my computer? If thats the case what would it be? As a few do extract but a few do not
