### ISSUE TITLE
[Bug]: Prefab Naming Issue

### ISSUE THREAD

**Issue by Q4st** [AssetRipper/AssetRipper#331]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2018.4.23f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Getting the correct filename when reading, but getting the container name when exporting！
![1](https://user-images.githubusercontent.com/58507193/160151090-024798d3-af37-476c-8d57-e1be60e4baf2.PNG)
![2](https://user-images.githubusercontent.com/58507193/160151096-ae8a08c2-6f64-4a51-9ff1-d08fd745c621.PNG)
game sample：
[GameData1_00ac6a80.zip](https://github.com/AssetRipper/AssetRipper/files/8351867/GameData1_00ac6a80.zip)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8351875/AssetRipper.log)

**Comment by ds5678** [comment]
Not AssetRipper's fault. The internal asset bundle paths are obfuscated as short numerical strings. You can select Group By Asset Type in the settings if you don't want to use the bundle paths for export.
