### ISSUE TITLE
[Bug]: Duplicate source code

### ISSUE THREAD

**Issue by cyberangel67** [AssetRipper/AssetRipper#333]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

Believe it is Unity 2019 LTS

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Log file is attached to previous ticket I raised 5 to 10 mins ago, but when I go to the source files, I am seeing about 20+ copies of the code labelled as the orginal and with an extension of 1-23+

 

### Relevant log output

Log file attached to previous ticket I raised 5 to 10mins ago

**Comment by ds5678** [comment]
Looking at the log from #332, this has so many issues. In particular, it is suffering from #281

**Comment by ds5678** [comment]
I just found someone else with this duplicate script issue, so it's probably not a one off. Anything you can discover about the issue might be helpful, especially if one release version causes it and another doesn't.

**Comment by cyberangel67** [comment]
The only thing I can tell you is that the version of Asset Rippper I downloaded around the 22nd Feb, didn't have this issue.

**Comment by ds5678** [comment]
I need more specific information than that. Do some testing

**Comment by cyberangel67** [comment]
Well I don't know what to tell you, the same game on a version of AssetRipper that was released roughly 4 weeks ago, does not suffer this issue. I can't supply any more information than that, other than show you a video of it being ripped by AssetRipper and not duplicating the source code.

**Comment by ds5678** [comment]
You can download old versions of AssetRipper and test

**Comment by cyberangel67** [comment]
Yes I know, I checked the version I used last was around the 22 Feb, I then downloaded the latest and I got 2 major errors. I get something has changed, I am just letting you know that I didn't have an issue, where I am now.

I'll recheck in a few weeks, and try again.

**Comment by Onixiya** [comment]
This happens on IL2CPP games as well. Using freshly compiled build with commit 1f958554f74336156f9fa4861db1eca6593c6715
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8402555/AssetRipper.log)
