### ISSUE TITLE
[Bug]: Commit 'move localizations folder' (6315c8d) 

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#342]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

n/a

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

Hi,
After the commit 'move localizations folder', I can compile fine (Debug Windows x64), but when running, it breaks trying to find 'en_US.json'. (Excecption at line 63 in LocalizationManager.
Note: moving back  the 'Localization folder back into 'AssetRipperGUI' and recompiling, all is fine.
Just to let you know.
Regards

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8398375/AssetRipper.log)

**Comment by vale7z4387ruwrejmhsr** [comment]
they forgot to change the string LocalizationFilePrefix in LocalizationManager.cs i guess because i searched for that folder and just got this .cs file and i open it and a string wasn't changed so that explains it anyway these types of mistakes happen to me sometimes as well

**Comment by Zbuffers** [comment]
Hi, I don't think modifying LocalizationFilePrefix  will change anything because in LocalizationManager.cs, Assembly.GetExecutingAssembly().GetManifestResourceNames() only returns "!AvaloniaResources", and no localization json is found
