### ISSUE TITLE
[Bug]: Audio Export Failures Before Unity 5

### ISSUE THREAD

**Issue by gugaferreila** [AssetRipper/AssetRipper#353]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

4.2.0

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

asset rippper dosen't extract all game files like audios meshes textures etc this is hapennig on 7 days to die alpha 1.1

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8459939/AssetRipper.log)

**Comment by ds5678** [comment]
From your log, it seems you only have issues with audio export. Do you have reason to believe there are issues with other asset types?

**Comment by gugaferreila** [comment]
> From your log, it seems you only have issues with audio export. Do you have reason to believe there are issues with other asset types?

Yes because when i extract textures with asset Studio i see much more textures

**Comment by ds5678** [comment]
I'll look into it

**Comment by ds5678** [comment]
I was unable to downgrade my 7 Days to Die installation that far, so I can't reproduce this.

**Comment by ds5678** [comment]
Closed because of inactivity

**Comment by ds5678** [comment]
Well, I can't reproduce this without 1.1 game files.

**Comment by gugaferreila** [comment]
can i sent the files for you to try to reproduce this error?

**Comment by ds5678** [comment]
> can i sent the files for you to try to reproduce this error?

I don't know for sure if I can legally accept that, but I think it would be okay since I actually own 7 Days to Die on Steam.

**Comment by gugaferreila** [comment]
so how do i sent to you?

**Comment by ds5678** [comment]
I can most easily be reached on Discord. There's a link to the AssetRipper server in the readme.

**Comment by gugaferreila** [comment]
sorry i'm new to github so i don't know where discord is on github page

**Comment by ds5678** [comment]
I was able to reproduce the audio decoding issues and improved the log messages in e6e7beb320c693ef82bd91caa6f0a01c31f522f0. This was caused by AssetRipper assuming everything is FSB audio, even though it usually isn't on Unity version earlier than 5.

**Comment by Virjoinga** [comment]
I was about to make an issue for this. I tried multiple AR releases and the culprit seems to be version 0.2.0.5. That version and above has this problem.
0.2.0.4 log (working):
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12173094/AssetRipper.log)
0.2.0.5 log (not working):
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12173100/AssetRipper.log)
I hope this is enough to help.
