### ISSUE TITLE
i give up

### ISSUE THREAD

**Issue by vale7z4387ruwrejmhsr** [AssetRipper/AssetRipper#359]
### Describe the issue

so in my playersettings.cs it has issues with the productname string in a unity 2018.2.21 game it says error playersettings 177
but in 2020.3.11 it says none of that ok i am doing something wrong but what?

here is the file
[PlayerSettings.txt](https://github.com/AssetRipper/AssetRipper/files/8508423/PlayerSettings.txt)

**Comment by ds5678** [comment]
#164 is days away

**Comment by vale7z4387ruwrejmhsr** [comment]
so what you mean is i have to wait until v0.2.0.0 get's released? fine

**Comment by ds5678** [comment]
duplicate of #164
