### ISSUE TITLE
[Enhancement]: Export unity packages

### ISSUE THREAD

**Issue by Panthr75** [AssetRipper/AssetRipper#360]
### Describe the new feature or enhancement

When exporting on any script level besides 0, AssetRipper will export every game assembly. This includes `Unity.TextMeshPro` and `Unity.Mathematics` , just to name a few.

This can cause issues specifically with IL2CPP games as getting TextMeshPro working requires downloading the unity package from the package manager and replacing GUIDs in all assets.

This problem can simply be mitigated by detecting assemblies like `Unity.TextMeshPro` and automatically using the package from the package manager. This may lead to some problems though, as some mono scripts in TextMeshPro contain multiple types. However, all "Components" have their own MonoScript so it should be fine.

**Comment by ds5678** [comment]
And how would AssetRipper know that an assembly belongs to a unity package? It certainly can't use the Unity API.

Assuming that the user provides the unity packages, there still presents the issue of parsing them. It would require lots of changes to the source generation and our yaml code. This something I've considered, but it is not easy. It won't happen at least until the new gui is finished.

**Comment by Panthr75** [comment]
Are we not allowed to query packages.unity.com to download the required packages?

**Comment by ds5678** [comment]
> Are we not allowed to query packages.unity.com to download the required packages?

Definitely not. AssetRipper will never contact Unity servers for any reason.

**Comment by Jannify** [comment]
The main peoblem is that the package version information is lost when building the game. So not only would we have to make api requests and yaml hacks, we would also need to analyse the package version from something like the dll hash, its layout or the classes it contains which are all not valid and error free solutions.

**Comment by Panthr75** [comment]
At least it should export text mesh pro as a unity package

**Comment by xiaopeng12138** [comment]
I also have TextMeshPro issues. What I do now is just delete the package from package manager and use decompiled version of TMP. I don't think it is the right way to do that. If the original package version is hard to get, we can just manually select which version it gonna be. The version of those basic package can be easily guessed depends on unity version.
