### ISSUE TITLE
[Other]: Disordered textures (sprites) when extracted

### ISSUE THREAD

**Issue by amVspR** [AssetRipper/AssetRipper#363]
### Describe the issue

I used the latest version of AssetRipper. However, the exported sprite is (purposely) disordered like this: https://i.imgur.com/4tAms3m.png . The extracted BG or CG is OK though. Any help or advice on how to fix this would be much appreciated! If you need any additional files for more information, please ask. 
Assetripper.log + exported project files: https://mega.nz/file/J1IwRYpZ#oijZ8TadZytQ8I1sJMwBv6ygwcZqpba-psJRLIPerw0

**Comment by amVspR** [comment]
I've just updated the required files.

**Comment by ds5678** [comment]
There's nothing more than AssetRipper can do. The developers, as you said, have purposefully disordered the image before using it in Unity. The only things you can do are either write a program to process each image, or manually fix them with an image editor.
