### ISSUE TITLE
[Enhancement]: Select Export Mode for Single Asset Export

### ISSUE THREAD

**Issue by misternebula** [AssetRipper/AssetRipper#364]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.4.27f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Selecting globalgamemanagers.assets and exporting all misses some items out that are normally seen in the GUI hierarchy. Clicking on the specific shader and exporting selected also gives nothing except the project version file.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8550582/AssetRipper.log)

**Comment by ds5678** [comment]
The shader is likely one of the Unity Engine shaders, for which AssetRipper automatically redirects any references.

**Comment by misternebula** [comment]
This game has custom replacements for those shaders

**Comment by misternebula** [comment]
And it doesn't really "redirect" it, because it throws an error and doesn't output any file.

**Comment by ds5678** [comment]
> it throws an error

It does not. `ExportedFile [Warning] : 'Engine 2017.3.0f3' failed to export` is just a deceptive side effect of me reporting failed exports for other exporters. It successfully did not export the shader.

> And it doesn't really "redirect" it
> doesn't output any file

If you were exporting more assets, those assets would "correctly" reference Unity Engine shaders, because AssetRipper redirects those references. If the engine exporter were disabled, then Unity would respond with conflict errors when you loaded the project.

> And this project is 2019, not 2017

Don't worry. It knows you're using 2019.4.27f1

**Comment by misternebula** [comment]
So then it's impossible to export the custom shaders in the game?

**Comment by ds5678** [comment]
Not impossible because there's no fundamental difference between normal assets and engine assets. However, I won't do any major graphical changes until the gui rewrite.

BTW AssetRipper exports dummy shaders. The engine shaders are probably a closer equivalent of your game's custom engine shaders.

**Comment by misternebula** [comment]
> BTW AssetRipper exports dummy shaders.

What about the option to export disassembled shaders? Yes they wont compile, but I've been able to reverse engineer them from that state.

**Comment by ds5678** [comment]
Although AssetRipper allows disassembly export, it won't be "supported" until I can have some time to focus on it. However, when I do the new gui, I'll remember that you want this option.

**Comment by ds5678** [comment]
As a temporary workaround, you can comment out this line:
https://github.com/AssetRipper/AssetRipper/blob/master/AssetRipperLibrary/Ripper.cs#L267

**Comment by misternebula** [comment]
Thanks so much!

**Comment by ds5678** [comment]
Closed because of the workaround and irrelevance. Unity Engine shaders have public source code available.
