### ISSUE TITLE
[Bug]: Cannot bake lighting because mesh format is invalid

### ISSUE THREAD

**Issue by normusF7** [AssetRipper/AssetRipper#368]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2021.3.1f1 / 2020.3.18.f1

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

When I try to bake lighting in a scene (Progressive CPU/GPU) extracted by AssetRipper all models throw this error:

`[PathTracer] Failed to add geometry for mesh 'mesh_name'; mesh format is invalid.`

where mesh_name is name of the mesh.

**Comment by ds5678** [comment]
I suspect this may be because of static meshes. However, it could also be because 2021.3 isn't fully supported yet. When #164 is implemented, you can try again.

**Comment by ds5678** [comment]
#164 is done

**Comment by ds5678** [comment]
Closed for inactivity
