### ISSUE TITLE
[Bug]: Shader dissassembly Export error

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#372]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.4.34f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Hi,

Cannot Extract Shaders using the 'Disassembly' Option.
-> Failed to export game content: Magic number 0 doesn't match

After a little digging, it looks like the problem is a wrong dataOfffset in file: 
ShaderTextRestorer\Exporters\DirectX\DXShaderTextExtractor.cs (line 14)
-> `dataOffset = DXDataHeader.GetDataOffset(version, gpuPlatform);` (version is 2019.4.34f1 and gpuPlatform is d3d11)
returns 6 when it should return **38** (found the DXBCFourCC at this offset when looking into the 'data' byte array), for this specific case.

When I 'Force' the dataOffset at 38, all shaders get exported nicely ;)

I don't know if this is specific to the Unity Version or the shader types, so mayby a more specific check for UnityVersion is required in ShaderTextRestorer\Exporters\DirectX\DXShaderTextExtractor.cs (line23):
-> `return HasGSInputPrimitive(version) ? 6 : 5;`

Hope this can help ;)
Regards

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8638653/AssetRipper.log)

**Comment by ds5678** [comment]
I consulted with nes on this. Apparently, he already solved this on his wip shader decompilation fork. You should check that out. Until he's ready for his changes to be merged, shader disassembly will have very limited support on this repository. I recommend you redirect any issues related to shader disassembly onto his fork for the time being.
<https://github.com/nesrak1/AssetRipper/tree/shader-dec>
