### ISSUE TITLE
[Bug]: System.Collections.Generic.Dictionary seems judged as serializable made asset deserialize failed.

### ISSUE THREAD

**Issue by lifeengines** [AssetRipper/AssetRipper#373]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Console Version Windows x64

### Which Unity version did this occur on?

2018.4.36f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

System.Collections.Generic.Dictionary seems judged as serializable made asset deserialize failed.

**Comment by ds5678** [comment]
This should be resolved in 1ce15b1359ecad12aabcac576b3635ddb740531d
