### ISSUE TITLE
[Bug]: Unknown attribute 44543834 for Light

### ISSUE THREAD

**Issue by qq1035732175** [AssetRipper/AssetRipper#378]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2020.3.32f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

rainbow six mobile game unpacking error

Two errors

1 An item with the same key has already been added. Key: LeaderboardPosition_BG_1(Sprite)
2 Unknown attribute 44543834 for Light
[leaderboardrankevolutionstylesheetsregistry_assets_all_7339e46035102e2d0727b03936aaea8b.zip](https://github.com/AssetRipper/AssetRipper/files/8653782/leaderboardrankevolutionstylesheetsregistry_assets_all_7339e46035102e2d0727b03936aaea8b.zip)
[ui3dstageregistry_assets_all_92859fa250098d3123da0e2f3be73c3e.zip](https://github.com/AssetRipper/AssetRipper/files/8653783/ui3dstageregistry_assets_all_92859fa250098d3123da0e2f3be73c3e.zip)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8653789/AssetRipper.log)

**Comment by ds5678** [comment]
I'll take a look
