### ISSUE TITLE
[Other]: Core Class Casting

### ISSUE THREAD

**Issue by NoahHahm** [AssetRipper/AssetRipper#383]
### Describe the issue

Recently, it was confirmed that the type was created through AssetRipper.SourceGenerated.dll.

```
ex.
foreach (var asset in ripper.GameStructure.FileCollection.FetchAssets()) {
   Mesh cls = (Mesh)asset // type casting error
}
```

There is a problem that type casting does not work as above.

Is there any way to cast the class referenced in AssetRipper.SourceGenerated.dll to Core Classes ?

**Comment by ds5678** [comment]
The source generated classes are a replacement for the classes in AssetRipperCore/Classes/. The latter just hasn't been removed yet.

**Comment by NoahHahm** [comment]
I was using the asset ripper to parse information about assets.
for example, I use it to first check the contents of the assets made by external designers.
as the class is recently created through SourceGenerated, it is not type-cast to the prototype of Core Class.
I used to access and use Indices in the mesh to check the TriangleCount, but I'm having a problem recently because it doesn't cast.

**Comment by ds5678** [comment]
In the future, `AssetRipper.Core.Classes.Mesh.Mesh` just won't exist. All the functionality for the "Core" classes is being moved to extension methods on source generated interfaces. The source generated classes, are faster, more accurate, less memory intensive, and easier to maintain.

**Comment by NoahHahm** [comment]
I understand.  So how do I safely cast UnityObjectBase from ripper.GameStructure.FileCollection.FetchAssets to a generated class?  If you don't know which version of a typeclass will come in, do you have to check everything?

**Comment by ds5678** [comment]
This should answer most of your questions about inheritance:
https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/object-oriented/inheritance
