### ISSUE TITLE
[Bug]: [Error] : SerializedFileException: v:2019.4.26f1 p:StandaloneWin64Player t:MonoBehaviour n:sharedassets6.assets

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#402]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Console Version Windows x64

### Which Unity version did this occur on?

2019.4.26f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Hello,

I get an Error while loading the game:

[Error] : SerializedFileException: v:2019.4.26f1 p:StandaloneWin64Player t:MonoBehaviour n:sharedassets6.assets
Path:E:\Games\A Tale of Synapse\A Tale Of Synapse_Data\sharedassets6.assets
Message: Read 68 but expected 80 for asset type MonoBehaviour

I checked and version prior to 0.2 works fine.
log attached.
Hope this can help ;)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8747389/AssetRipper.log)

**Comment by ds5678** [comment]
You self-compiled on Debug mode. That's why this happened
