### ISSUE TITLE
[Other]: it can't export monoscript ? (.cs file)

### ISSUE THREAD

**Issue by makarhuyaker** [AssetRipper/AssetRipper#407]
### Describe the issue

.

**Comment by ds5678** [comment]
Provide your log

**Comment by ds5678** [comment]
The whole log. Just drop the file into the comment box

**Comment by ds5678** [comment]
I see what's happening. You dropped `globalgamemanagers.assets` into AssetRipper. This file doesn't contain any script data. That's only contained in `*.dll` files. You need to rip the whole game or include mono `*.dll` files with your file.

**Comment by ds5678** [comment]
GameObject is predefined asset type. Monobehaviours are not predefined. The `MonoScript` asset type just contains the name of the script to use from the dll file.

**Comment by ds5678** [comment]
> what is predefined asset ?

Anything on this list. https://github.com/AssetRipper/AssetRipper/blob/master/AssetRipper.Fundamentals/ClassIDType.cs
