### ISSUE TITLE
[Bug]: Assembly Resolve Failure

### ISSUE THREAD

**Issue by githubexplorer2342** [AssetRipper/AssetRipper#408]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2021.2.10f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

When it's decompiling the monoscripts, it only exports a few then a error appears.

### Relevant log output

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19043.0
System : Operating System: Windows x64
System : AssetRipper Version: 0.2.0.2
System : AssetRipper Build Type: Release x64 Published
System : UTC Current Time: 5/26/2022 7:59:33 PM
System : UTC Compile Time: Wed May 25 04:13:57 UTC 2022
Plugin : Loading plugins...
Plugin : Finished loading plugins.
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : ExportRootPath: E:\software\assetripper\Ripped
General : ExportDependencies: False
General : IgnoreAssetBundleContentPaths: False
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshCoordinateSpace: Unity
General : MeshExportFormat: Native
General : ScriptExportMode: Decompiled
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Texture2D
General : TerrainExportMode: Native
General : TextExportMode: Parse
General : Attempting to read files from E:\RagdollGame
Import : Game file 'globalgamemanagers' has been found
Import : Game file 'level0' has been found
Import : Mixed game structure has been found at E:\RagdollGame
Import : Files use the 'Mono' scripting backend.
Import : Assembly 'UnityEngine.IMGUIModule' has been loaded
Import : Assembly 'UnityEngine.CoreModule' has been loaded
Import : Assembly 'UnityEngine.TextRenderingModule' has been loaded
Import : Assembly 'mscorlib' has been loaded
Import : Assembly 'UnityEngine.UI' has been loaded
Import : Assembly 'netstandard' has been loaded
Import : Assembly 'Unity.RenderPipelines.Core.Runtime' has been loaded
Import : Assembly 'Assembly-CSharp' has been loaded
Import : Assembly 'UnityEngine.Physics2DModule' has been loaded
Import : Assembly 'UnityEngine.AnimationModule' has been loaded
General : Finished reading files
General : About to begin export to E:\Things\Tests\globalgamemanagers\globalgamemanagers
General : Removing any files from a previous export...
Export : Attempting to export assets to E:\Things\Tests\globalgamemanagers\globalgamemanagers...
Export : Starting pre-export
Export : Starting export
Export : Game files have these Unity versions: 2021.2.10f1
Export : Exporting to Unity version 2021.2.10f1
Export : Preparing for export...
Import : Assembly 'UnityEngine.UIElementsModule' has been loaded
Import : Assembly 'UnityEngine.TilemapModule' has been loaded
Import : Assembly 'UnityEngine.TextCoreTextEngineModule' has been loaded
Import : Assembly 'UnityEngine.Purchasing' has been loaded
Import : Assembly 'Unity.RenderPipelines.Universal.Runtime' has been loaded
Import : Assembly 'UnityEngine.Advertisements' has been loaded
Import : Assembly 'Unity.Timeline' has been loaded
Import : Assembly 'Unity.InternalAPIEngineBridge.001' has been loaded
Import [Warning] : Assembly 'UnityEngine.TestRunner' hasn't been found
Import : Assembly 'Unity.Burst' has been loaded
Import : Assembly 'UnityEngine.Purchasing.Stores' has been loaded
Import : Assembly 'Unity.TextMeshPro' has been loaded
Import : Assembly 'UnityEngine.Monetization' has been loaded
Import : Assembly 'Unity.Mathematics' has been loaded
Import : Assembly 'Unity.2D.SpriteShape.Runtime' has been loaded
Import : Assembly 'Unity.2D.IK.Runtime' has been loaded
Import : Assembly 'Unity.2D.Animation.Runtime' has been loaded
Import : Assembly 'Unity.RenderPipelines.Core.ShaderLibrary' has been loaded
Import : Assembly 'Purchasing.Common' has been loaded
Import : Assembly 'UnityEngine.Purchasing.Codeless' has been loaded
Import : Assembly 'UnityEngine.XR.LegacyInputHelpers' has been loaded
Import : Assembly 'Unity.2D.Common.Runtime' has been loaded
Import : Assembly 'Unity.2D.PixelPerfect' has been loaded
Import : Assembly 'UnityEngine.Purchasing.SecurityStub' has been loaded
Import : Assembly 'UnityEngine.Purchasing.SecurityCore' has been loaded
Import : Assembly 'UnityEngine.SpatialTracking' has been loaded
Import : Assembly 'Unity.RenderPipelines.Universal.Shaders' has been loaded
Import : Assembly 'UnityEngine.Purchasing.WinRTCore' has been loaded
Import : Assembly 'UnityEngine.Purchasing.AppleStub' has been loaded
Import : Assembly 'Unity.Analytics.DataPrivacy' has been loaded
Import : Assembly 'UnityEngine.Purchasing.AppleCore' has been loaded
Import : Assembly 'Unity.RenderPipeline.Universal.ShaderLibrary' has been loaded
Import : Assembly 'UnityEngine.Purchasing.AppleMacosStub' has been loaded
Import : Assembly 'Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary' has been loaded
Import : Assembly 'UnityEngine.Purchasing.WinRTStub' has been loaded
Import : Resource file 'resources.assets.resS' has been loaded
Import : Resource file 'sharedassets0.assets.resS' has been loaded
Export : Preparation complete. Starting to export now...
ExportedFile : 'PlayerSettings' exported
ExportedFile : 'InputManager' exported
ExportedFile : 'TagManager' exported
ExportedFile : 'AudioManager' exported
ExportedFile : 'ShaderNameRegistry' exported
ExportedFile : 'GraphicsSettings' exported
ExportedFile : 'TimeManager' exported
ExportedFile : 'DelayedCallManager' exported
ExportedFile : 'PhysicsManager' exported
ExportedFile : 'BuildSettings' exported
ExportedFile : 'QualitySettings' exported
ExportedFile : 'NavMeshProjectSettings' exported
ExportedFile : 'Physics2DSettings' exported
ExportedFile : 'RuntimeInitializeOnLoadManager' exported
ExportedFile : 'StreamingManager' exported
ExportedFile : 'VFXManager' exported
ExportedFile : 'level0' exported
ExportedFile : 'Engine 2021.2.10f1' exported
ExportedFile : 'Hidden/BlitCopyHDRTonemap' exported
ExportedFile [Warning] : 'Hidden/Internal-UIRDefaultWorld' failed to export
Export : Exporting scripts...
Export : Decompiling Unity.RenderPipelines.Core.Runtime
Export : Exporting assembly definition 'Unity.RenderPipelines.Core.Runtime.asmdef'
Export : Decompiling Assembly-CSharp
Export : Decompiling Unity.RenderPipelines.Universal.Runtime
[Error] : System.Exception: Could not resolve Unity.RenderPipelines.Universal.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
   at AssetRipper.Library.Exporters.Scripts.ScriptDecompiler.DecompileWholeProject(WholeAssemblyDecompiler decompiler, AssemblyDefinition assembly, String outputFolder) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\ScriptDecompiler.cs:line 34
   at AssetRipper.Library.Exporters.Scripts.ScriptDecompiler.DecompileWholeProject(AssemblyDefinition assembly, String outputFolder) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\ScriptDecompiler.cs:line 29
   at AssetRipper.Library.Exporters.Scripts.ScriptExporter.Export(IExportContainer container, IEnumerable`1 assets, String dirPath, Action`3 callback) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\ScriptExporter.cs:line 96
   at AssetRipper.Library.Exporters.Scripts.ScriptExportCollection.Export(IProjectAssetContainer container, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\ScriptExportCollection.cs:line 64
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 151
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 62
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 98
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, Func`2 filter) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 161
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 142
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIExportManager.cs:line 55

General : UI Reset

**Comment by ds5678** [comment]
Do you have a steam db link for this game? We're having trouble reproducing your bug.

**Comment by Panthr75** [comment]
AssetRipper is detecting a mixed folder structure. What folder are you using to import into AssetRipper?

**Comment by ds5678** [comment]
> If you want, i can send the game to you in order to see if you can reproduce the bug.

If your friend owns the game and is okay with you doing so, that is preferable.

**Comment by ds5678** [comment]
If he's not comfortable with you posting a link online, it's okay for you to send me a link via a private discord message.

**Comment by Panthr75** [comment]
Wasn't able to reproduce on `master` branch

**Comment by githubexplorer2342** [comment]
> Wasn't able to reproduce on `master` branch

do you mean release? Sorry if i'm confused with this stuff its because im new in GitHub.

**Comment by githubexplorer2342** [comment]
Ok so i tested out a few things and i found out that just inserting the _data folder makes the error not appear, but when i drag the whole contents of the game folder inside AssetRipper the error pops up. I think this is a conflict with a file or something? Not sure.

**Comment by Panthr75** [comment]
Just was able to reproduce with the help of ds5678.

**Comment by githubexplorer2342** [comment]
> Just was able to reproduce with the help of ds5678.
Is it going to be fixed? I really wonder whats the cause of this failure.
