### ISSUE TITLE
[Enhancement]: AssetReference m_AssetGUID

### ISSUE THREAD

**Issue by lishuwei115** [AssetRipper/AssetRipper#415]
### find asset by m_AssetGUID in AssetReference

how to find Asset by m_AssetGUID in AssetReference?

**Comment by lishuwei115** [comment]
![image](https://user-images.githubusercontent.com/20329904/171591843-de17d3df-9646-4a23-85a7-fd1214cc2108.png)
how to find asset reference when use addressable AssetReference class

**Comment by lishuwei115** [comment]
Sorry, the issue is closed due to misoperation

**Comment by lishuwei115** [comment]
Sorry, it's my fault, I didn't express it clearly, 
I didn't mean that, I just thought if there is any way to know the original guid, so that the object can be found according to the value of m_AssetGUID

**Comment by lishuwei115** [comment]
My purpose is not to find the original guid, because the original guid is used in the AssetReference, and when the project is exported, the original guid is still retained, so the association of the object is lost.

**Comment by lycc193** [comment]
Hi, the issue described here is that in the original project, a resource is referenced through an `AssetReference`, and during serialization into a `ScriptableObject`, this reference is saved as a GUID in the field `AssetReference.m_AssetGUID`.
However, after the original project is compiled, or potentially after exporting with AssetRipper, the GUID of the original asset changes, causing the `AssetReference` to become invalid. The question is how to restore this reference.
