### ISSUE TITLE
[Bug]: missing scripts on prefab after exporting dll

### ISSUE THREAD

**Issue by hanicraft** [AssetRipper/AssetRipper#428]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

flappy bird remake

### Which Unity version did this occur on?

2017 but tried 2019 and 2021

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

im exported scripts as dll because i tired of fixing scripts after export
the dlls exported successfully but when im loaded the scene and runned the game im got this warning in editor
"referenced script ("script name") on this behaviour is missing"
im researched it and im found out that the scripts are missing from prefab i tried to add it but it didnt even found the scripts
also i cant open script inside dll unity plugin

**Comment by ds5678** [comment]
Log please

**Comment by hanicraft** [comment]
System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19043.0
System : Operating System: Windows x64
System : AssetRipper Version: 0.2.0.3
System : AssetRipper Build Type: Release x64 Published
System : UTC Current Time: 6/11/2022 7:30:04 PM
System : UTC Compile Time: Wed Jun  1 18:54:32 UTC 2022
Plugin : Loading plugins...
Plugin : Finished loading plugins.
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : ExportRootPath: F:\tools\AssetRipperGUI_win64\Ripped
General : ExportDependencies: False
General : IgnoreAssetBundleContentPaths: False
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshCoordinateSpace: Unity
General : MeshExportFormat: Native
General : ScriptExportMode: DllExportWithoutRenaming
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Native
General : TerrainExportMode: Native
General : TextExportMode: Parse
General : Attempting to read files from D:\games\flappybirdclone1.0\1.0\flappybirdclone_Data
Import : PC data directory found. Setting root to parent directory
Import : PC game structure has been found at 'D:\games\flappybirdclone1.0\1.0\flappybirdclone_Data'
Import : Collecting game files...
Import : Game file 'globalgamemanagers' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
Import : Collecting Streaming Assets...
Import : Files use the 'Mono' scripting backend.
Import : During Mono initialization, found 9 assemblies
General : Finished reading files
General : About to begin export to D:\games\flappybirdclone1.0\decompiled\flappybirdclone
General : Removing any files from a previous export...
Export : Attempting to export assets to D:\games\flappybirdclone1.0\decompiled\flappybirdclone...
Export : Starting pre-export
Export : Starting export
Export : Game files have these Unity versions: 2017.1.0f3
Export : Exporting to Unity version 2017.1.0f3
Export : Preparing for export...
Import [Warning] : Assembly 'UnityEngine.TestRunner' hasn't been found
Import [Warning] : Assembly 'UnityEngine.HoloLens' hasn't been found
Import [Warning] : Assembly 'UnityEngine.Purchasing' hasn't been found
Import [Warning] : Assembly 'UnityEngine.Analytics' hasn't been found
Import [Warning] : Assembly 'UnityEngine.Advertisements' hasn't been found
Import : Resource file 'sharedassets1.assets.resS' has been loaded
Import : Resource file 'sharedassets0.assets.resS' has been loaded
Import : Resource file 'sharedassets0.resource' has been loaded
Export : Preparation complete. Starting to export now...
ExportedFile : 'PlayerSettings' exported
ExportedFile : 'InputManager' exported
ExportedFile : 'TagManager' exported
ExportedFile : 'AudioManager' exported
ExportedFile : 'ScriptMapper' exported
ExportedFile : 'GraphicsSettings' exported
ExportedFile : 'TimeManager' exported
ExportedFile : 'DelayedCallManager' exported
ExportedFile : 'PhysicsManager' exported
ExportedFile : 'BuildSettings' exported
ExportedFile : 'QualitySettings' exported
ExportedFile : 'NetworkManager' exported
ExportedFile : 'MasterServerInterface' exported
ExportedFile : 'NavMeshProjectSettings' exported
ExportedFile : 'Physics2DSettings' exported
ExportedFile : 'RuntimeInitializeOnLoadManager' exported
ExportedFile : 'CloudWebServicesManager' exported
ExportedFile : 'UnityConnectSettings' exported
ExportedFile : 'level0' exported
ExportedFile : 'level1' exported
Export : Exporting scripts...
Export : Finished exporting scripts
ExportedFile : 'ScriptExportCollection' exported
ExportedFile : 'Engine 2017.1.0f3' exported
ExportedFile : 'Engine 2017.1.0f3' exported
ExportedFile : 'Brightness' exported
ExportedFile : 'PipeBody' exported
ExportedFile : 'BrightnessSpritesheet' exported
ExportedFile : 'MedalSpritesheet' exported
ExportedFile : 'Panel' exported
ExportedFile : 'PipeEnd' exported
ExportedFile : 'Instructions' exported
ExportedFile : 'Engine 2017.1.0f3' exported
ExportedFile : 'UI_GameOver' exported
ExportedFile : 'UI_InGameFadeOut' exported
ExportedFile : 'GameOver' exported
ExportedFile : 'InGame' exported
ExportedFile : 'Prefab' exported
ExportedFile : 'Engine 2017.1.0f3' exported
ExportedFile : 'Font Material' exported
ExportedFile : 'Font Material' exported
ExportedFile : 'Button' exported
ExportedFile : 'BackgroundDay' exported
ExportedFile : 'BackgroundNight' exported
ExportedFile : 'Engine 2017.1.0f3' exported
ExportedFile : 'BirdSpritesheet 1' exported
ExportedFile : 'Ground' exported
ExportedFile : 'white' exported
ExportedFile : 'Engine 2017.1.0f3' exported
ExportedFile : 'PlayIcon' exported
ExportedFile : 'black' exported
ExportedFile : 'FlyingBlue' exported
ExportedFile : 'FlyingGreen' exported
ExportedFile : 'FlyingRed' exported
ExportedFile : 'FlyingYellow' exported
ExportedFile : 'IdleBlue' exported
ExportedFile : 'IdleGreen' exported
ExportedFile : 'IdleRed' exported
ExportedFile : 'IdleYellow' exported
ExportedFile : 'Ground' exported
ExportedFile : 'sfx_smash' exported
ExportedFile : 'sfx_score' exported
ExportedFile : 'sfx_fall' exported
ExportedFile : 'sfx_swoosh2' exported
ExportedFile : 'sfx_swoosh' exported
ExportedFile : 'BirdBlue' exported
ExportedFile : 'Ground' exported
ExportedFile : 'font_pixelmix' exported
ExportedFile : 'font_dimitri' exported
ExportedFile : 'BirdGreen' exported
ExportedFile : 'BirdRed' exported
ExportedFile : 'BirdYellow' exported
Export : Finished exporting assets
Export : Exporting type trees...
Export : Saving game assemblies...
Export : Finished post-export
General : Export Complete!

**Comment by ds5678** [comment]
> im exported scripts as dll because i tired of fixing scripts after export

This is not always a viable solution to your script fixing issue.

> the dlls exported successfully but when im loaded the scene and runned the game im got this warning in editor
"referenced script ("script name") on this behaviour is missing"

Unity overwrites your `Assembly-CSharp.dll` causing this missing script issue. Frameworks like [ThunderKit](https://github.com/PassivePicasso/ThunderKit) hook editor functions to prevent this.
