### ISSUE TITLE
[Enhancement]: Progress Indicator for `Preparing for Export...`

### ISSUE THREAD

**Issue by HametAk** [AssetRipper/AssetRipper#442]
### Describe the new feature or enhancement

![image](https://user-images.githubusercontent.com/70479098/175295232-a2c1b3d1-006f-4496-9553-4493ae6c884f.png)

It would help more if there is a "remaining time: x minutes" or a progress bar on the right site instead of "This might take a minute", cause this message doesn't help after waiting more than x hour(s).

**Comment by ds5678** [comment]
Not really feasible
