### ISSUE TITLE
[Bug]: Scence not working

### ISSUE THREAD

**Issue by Dhruva678** [AssetRipper/AssetRipper#444]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

 https://gamejolt.com/games/CastleofMinar/604953

### Which Unity version did this occur on?

2020.3.23f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

When I try to play te scence it doesnt start it shows all complier errors fixed before you enter playmode

**Comment by ds5678** [comment]
Normal

**Comment by Dhruva678** [comment]
how to solve it

**Comment by ds5678** [comment]
You fix the errors. Script decompilation is not perfect.
