### ISSUE TITLE
Remove Ogg and Vorbis dependencies

### ISSUE THREAD

**Issue by ds5678** [AssetRipper/AssetRipper#446]
AssetRipper uses [Fmod5Sharp](https://github.com/SamboyCoding/Fmod5Sharp) for decoding the [FMOD](https://www.fmod.com/) banks contained in `AudioClip`s. Fmod5Sharp currently relies on [Ogg](https://github.com/xiph/ogg) and [Vorbis](https://github.com/xiph/vorbis) for producing ogg audio files. It should be possible to use managed code instead.

- [ ] SamboyCoding/Fmod5Sharp#2
- [ ] Implement any required changes in AssetRipper

**Comment by SamboyCoding** [comment]
I'm happy to announce that the issue in Fmod5Sharp is fixed.
