### ISSUE TITLE
[Bug]: Monobehaviours wont export

### ISSUE THREAD

**Issue by kira-develops** [AssetRipper/AssetRipper#452]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

FNaF AR: Special Delivery

### Which Unity version did this occur on?

2018.4.35

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Every time I try to export everything from the APK/IPA, all of the monobehaviours throw errors when they're dumping. I have no idea why, they work on other programs, and the DLLs that AssetRipper spits out work to get them on these other programs.

### Relevant log output
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9039003/AssetRipper.log)

**Comment by ds5678** [comment]
Not sure when I changed this, but it should be good now. It was a choice between performance and MonoBehaviour deserialization.
