### ISSUE TITLE
[Other]: Discord server invite expired

### ISSUE THREAD

**Issue by raylu** [AssetRipper/AssetRipper#457]
### Describe the issue

I tried joining the Discord server but couldn't accept the invite. I believe the invite has expired.

Happy to help test in real-time if you want (raylu#2428)

**Comment by ds5678** [comment]
According to Discord, the [link](https://discord.gg/XqXa53W2Yh) isn't expired. I just checked; it's an infinite link.

**Comment by raylu** [comment]
weird... I was able to paste the link in the discord desktop app but couldn't click it in my browser. sorry about the noise. definitely something wrong on my end
