### ISSUE TITLE
[Other]: Extract Shaders

### ISSUE THREAD

**Issue by LucasViniciusDev** [AssetRipper/AssetRipper#462]
### Describe the issue

I wanted to get some shaders, but I noticed that the shaders don't work after I export to a folder.

Has anyone managed to export the shaders?

**Comment by LucasViniciusDev** [comment]
I wanted to get some shaders, but I noticed that the shaders don't work after I export to a folder.

Has anyone managed to export the shaders?

**Comment by ds5678** [comment]
Dummy shaders "work" in the sense that they compile and contain all the properties they're supposed to. 

Disassembled shaders are not designed to be compiled. This is explicitly stated in the user interface.
