### ISSUE TITLE
[Bug]: Sprites in SpriteAtlas can have different properties like PixelsToUnits etc.

### ISSUE THREAD

**Issue by trouger** [AssetRipper/AssetRipper#464]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

My testing project. 
Easy to repro. 
Cause is clear.

### Which Unity version did this occur on?

unity 2020.3 LTS

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Sprites from different textures can have different texture-importer-settings like PixelsToUnits.
When these sprites are packed into a SpriteAtlas in the game build, the reversed game project will have all these sprites under one large Texture2D. As pixelsToUnits is a property of texture importer, all sprites will have the same property value, which is incorrect when compared to the original game project.

IMHO, maybe sprites should be exported as yaml assets, one .asset file for each sprite, so that they can have their own properties.
I've tested this idea in Unity Editor, by creating multiple sprites from textures in code, assign different properties to them, and saving them as .asset files, building the game, and finally running the game...   All things are as expected.

**Comment by ds5678** [comment]
I'll check it out 👍

**Comment by ds5678** [comment]
Fixed in #488
