### ISSUE TITLE
[Bug]: Error with exporting Fall Guys

### ISSUE THREAD

**Issue by kamarad290** [AssetRipper/AssetRipper#466]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

Fall Guys
https://steamdb.info/app/1097150/

### Which Unity version did this occur on?

Unity 2019.4.37

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I imported the game folder into the Asset Ripper GUI and exported it, but the export failed.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9127859/AssetRipper.log)

**Comment by ds5678** [comment]
There's something wrong on your end. Windows isn't letting AssetRipper create that file.
