### ISSUE TITLE
[Bug]: Punishing:Gray Raven  import bug

### ISSUE THREAD

**Issue by leostudiosTM** [AssetRipper/AssetRipper#468]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

https://play.google.com/store/apps/details?id=com.kurogame.gplay.punishing.grayraven.en

### Which Unity version did this occur on?

Android I don't know

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

when i import it crashes

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9129553/AssetRipper.log)

**Comment by ds5678** [comment]
There were two main errors in your log:
* I see the first often with encrypted bundles.
* The second happened because you tried to use AssetRipper on a Unity package.
