### ISSUE TITLE
[Bug]: AudioMixer doesn't export correctly

### ISSUE THREAD

**Issue by trouger** [AssetRipper/AssetRipper#471]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

my test project

### Which Unity version did this occur on?

all versions

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

AudioMixerController, AudioMixerGroupController, AudioMixerEffectController, AudioMixerSnapshotController.
These assets have complex pre-processing when unity builds them. As a result, the editor and release data won't be mapped to each other, so reversing the data is not a trivial task. The current exported AudioMixerGroups lose all audio effect stacks, exposed parameters, snapshot values, transition overrides...
I'm recently working on it and hope to submit a pull request in a few days :)

**Comment by ds5678** [comment]
Are you on the [Discord server](https://discord.gg/XqXa53W2Yh)? I often help new contributors get started in conversations there.

**Comment by ds5678** [comment]
Fixed in #487
