### ISSUE TITLE
[Bug]: Export fails with NullReferenceException when decompiling shader in Stacklands

### ISSUE THREAD

**Issue by benediktwerner** [AssetRipper/AssetRipper#496]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

Stacklands: https://steamdb.info/app/1948280/

### Which Unity version did this occur on?

2020.3.6

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

When exporting Stacklands with Shaders set to "Decompile", the export fails at some point due to a NullReferenceException (see the attached log). It works fine when only disassembling shaders.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9309067/AssetRipper.log)

**Comment by ds5678** [comment]
I pushed a commit updating the nullability in this file. Can you check if the error still happens and send a new log if it does?

**Comment by benediktwerner** [comment]
Exact same exception still. Took a look at it myself, the null value comes from here: https://github.com/AssetRipper/AssetRipper/blob/master/ShaderTextRestorer/UltraShaderConverter/DirectXDisassembler/Blocks/SHDR.cs#L413

This constructor can leave `swizzle` as `null`. VS also warns about it.

I don't understand this stuff enough to tell what the correct behavior should be. I guess maybe just initialize it to an empty array?

The null value then finds its way into the USILOperand via https://github.com/AssetRipper/AssetRipper/blob/master/ShaderTextRestorer/UltraShaderConverter/UShader/DirectX/DirectXProgramToUSIL.cs#L246 called from https://github.com/AssetRipper/AssetRipper/blob/master/ShaderTextRestorer/UltraShaderConverter/UShader/DirectX/DirectXProgramToUSIL.cs#L1410 from https://github.com/AssetRipper/AssetRipper/blob/master/ShaderTextRestorer/UltraShaderConverter/UShader/DirectX/DirectXProgramToUSIL.cs#L140

**Comment by benediktwerner** [comment]
I guess I can add, inserting `else swizzle = Array.Empty<int>();` [here](https://github.com/AssetRipper/AssetRipper/blob/master/ShaderTextRestorer/UltraShaderConverter/DirectXDisassembler/Blocks/SHDR.cs#L480) makes the export complete successfully. Just don't know if it means the shader got decompiled incorrectly somehow 🤷‍♂️
