### ISSUE TITLE
[Bug]: Mesh Coordinate System Conversion

### ISSUE THREAD

**Issue by walllable** [AssetRipper/AssetRipper#499]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

Scene/project originally intended for VRChat

### Which Unity version did this occur on?

Project initially from Unity 5.6.3p1, upgraded to 2019.4.31f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

The exported .glb file appears flipped on the X-axis compared to the original scene.

Unity:
![image](https://user-images.githubusercontent.com/10066958/184297292-39005ff9-81fc-4782-872d-ed39508049ce.png)

Blender:
![image](https://user-images.githubusercontent.com/10066958/184297381-002e2b60-9351-4861-acd9-cb2775d1b32f.png)

**Comment by aldelaro5** [comment]
I am experiencing this on the exported prefabs of a unity 2018.4.12f1 game called Bug fables. It's a mono game.

Tested on 0.2.3.0

**Comment by ds5678** [comment]
I'm aware of this. It happens on all games.
