### ISSUE TITLE
[Enhancement]: Primary Content Extraction

### ISSUE THREAD

**Issue by ds5678** [AssetRipper/AssetRipper#504]
### Describe the new feature or enhancement

Up until this point, AssetRipper has exclusively generated Unity projects. There is demand for a less Unity-focused output mode. I propose a `Primary Content Extraction` mode. It would focus on high profile assets like audio, models, and textures, similar to AssetStudio. Such an addition would have the following benefits:

* AssetRipper would be more competitive with that group of users.
* There would be better segregation of code for these two modes.
* Output would be faster when a Unity project isn't necessary.
* Settings can be split by extraction mode.

**Comment by AraHaan** [comment]
What about FBX as well for games that use FBX files for the 3d assets?

**Comment by ds5678** [comment]
I now only offer 1 model output format because:
* GLB is superior to FBX.
* The code is simpler.
* Users assume all 3D formats are equivalent in quality and use the ones they're familiar with (FBX). Their disappointment at the reduced quality hurts the AssetRipper reputation.

**Comment by AraHaan** [comment]
I wonder if this could also be implemented with a way to define special ways of extracting content via a loadable plugin interface?

**Comment by ds5678** [comment]
> I wonder if this could also be implemented with a way to define special ways of extracting content via a loadable plugin interface?

Not likely to happen
