### ISSUE TITLE
[Bug]: Unity crash when importing Mon Bazou

### ISSUE THREAD

**Issue by Bluscream** [AssetRipper/AssetRipper#505]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

[Mon Bazou](https://steamdb.info/app/1520370/)

### Which Unity version did this occur on?

2021.2.16f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

![image](https://user-images.githubusercontent.com/3318223/184640020-c6890ba5-02d5-4284-a25a-bc0626e93c96.png)

### Relevant log output

[Editor.log](https://github.com/AssetRipper/AssetRipper/files/9337345/Editor.log)
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9337353/AssetRipper.log)

**Comment by Bluscream** [comment]
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9337353/AssetRipper.log)

**Comment by ds5678** [comment]
The unity crash log seems to suggest that this is related to shaders.

**Comment by Bluscream** [comment]
Mhm, so how should we proceed? Next time i'll skip shader extraction? Or did something in the shader extraction progress f*ck up and can be fixed?

**Comment by Bluscream** [comment]
Mhm, that still doesn't help me to decide how to proceed now and especially next time i need to extract a project

**Comment by ds5678** [comment]
There's nothing I can do to help you.
