### ISSUE TITLE
[Bug]: ExposedReference can't read

### ISSUE THREAD

**Issue by PlayNull001** [AssetRipper/AssetRipper#511]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

[2019_4_28f1_ExposedReference_Bug.zip](https://github.com/AssetRipper/AssetRipper/files/9352479/2019_4_28f1_ExposedReference_Bug.zip)

### Which Unity version did this occur on?

2019.4.28f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

ExposedReference can't read

https://docs.unity3d.com/ScriptReference/ExposedReference_1.html

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9352471/AssetRipper.log)

**Comment by ds5678** [comment]
I just updated the assembly framework (#227 1ce15b1359ecad12aabcac576b3635ddb740531d). I may get a chance to look at this soon. It's possible this has been solved; I did not check.

**Comment by ds5678** [comment]
I verified that this is still not functioning. However, the code is much simpler now if you want to contribute a fix. I'll be focusing on other things unless I encounter this in my own work.
