### ISSUE TITLE
[Bug]: decompiled the game, but scripts with errors

### ISSUE THREAD

**Issue by PolisoNOFF** [AssetRipper/AssetRipper#514]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

https://store.steampowered.com/app/412470/Metal_War_Online_Retribution/

### Which Unity version did this occur on?

2020.3.25f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

I decompiled the game, everything is fine in it, but the scripts are broken, the photo below

https://yapx.ru/v/TYVo6

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9372374/AssetRipper.log)

**Comment by ds5678** [comment]
I can't see the image. GitHub lets you include images directly in issues.

Regardless, script errors are normal and largely out of my control.
