### ISSUE TITLE
[Bug]: Assets export failled

### ISSUE THREAD

**Issue by L0w1y** [AssetRipper/AssetRipper#517]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

https://play.google.com/store/apps/details?id=com.axlebolt.standoff2

### Which Unity version did this occur on?

2019.4.22

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

failled export assets

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9386589/AssetRipper.log)

**Comment by ds5678** [comment]
Try the latest alpha build and see if it happens there. I made a bunch of changes in this section of the codebase.

**Comment by L0w1y** [comment]
> Try the latest alpha build and see if it happens there. I made a bunch of changes in this section of the codebase.

I forgot to say that everything works on the last alpha

**Comment by ds5678** [comment]
> everything works on the last alpha

So this issue is good for closure?
