### ISSUE TITLE
[Enhancement]: Support .pdb 

### ISSUE THREAD

**Issue by L0w1y** [AssetRipper/AssetRipper#519]
### Describe the new feature or enhancement

Add support for loading .pdb characters when disassembling .so, as in IDA

**Comment by ds5678** [comment]
What `.so` files in your game have a pdb?

**Comment by ds5678** [comment]
In any case, AssetRipper uses [Cpp2IL](https://github.com/SamboyCoding/Cpp2IL) for IL2Cpp recovery. If you think it could be improved, post an issue there instead. I have little control over its development.
