### ISSUE TITLE
[Bug]: System.Exception: Incorrect number of bytes written. -1 instead of 76805260 for 9745 compressed bytes

### ISSUE THREAD

**Issue by Piipperi** [AssetRipper/AssetRipper#522]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

https://play.google.com/store/apps/details?id=jp.pokemon.pokemonunite

### Which Unity version did this occur on?

2019.4.15f1

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

Unable to rip the game assets, up on opening the folder it errors out quickly. Tried extracting the APK with apktool, and also tried without extracting it and just opening the APK directly with AssetRipper

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9396801/AssetRipper.log)

**Comment by ds5678** [comment]
Given that this is Pokemon, it's most likely encrypted assets
