### ISSUE TITLE
[Bug]: Unity packages import along with normal scripts.

### ISSUE THREAD

**Issue by CristiZama** [AssetRipper/AssetRipper#535]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2022.1.14f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

So when I decompiled a game called "Cell Machine" and i got errors because the unity packages were imported into the monoscripts forlder and the packages folder. Its fairly easy to fix but annoying so please take that in mind. This happens on other games too.

### Relevant log output
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9539715/AssetRipper.log)

**Comment by ds5678** [comment]
> System : AssetRipper Version: 0.2.2.0

Your installation is outdated.
