### ISSUE TITLE
[Enhancement]: Change default output and log path

### ISSUE THREAD

**Issue by sparr** [AssetRipper/AssetRipper#536]
### Describe the new feature or enhancement

I propose changing the default `ExportRootPath`, `TempFolderPath`, `options.LogFile`, and `options.OutputDirectory` from being in/under the `ExecutingDirectory` to being under either the current working directory or the user's home directory.

On Linux this would be more in keeping with how most other programs work, especially on the command line.

On Linux and Windows this would avoid trying to create files and directories in a location where the user might not have write access.

This would have no impact if the user runs the program from the directory the binary is located in, which is probably a common use case.

**Comment by ds5678** [comment]
The only one you can't change with command line arguments is `TempFolderPath` and I would accept a pull request adding an argument for it.

> On Linux and Windows this would avoid trying to create files and directories in a location where the user might not have write access.

I would think that the opposite would be true since AssetRipper can only be moved to places where the user has write access.

> which is probably a common use case.

I use AssetRipper often and these defaults are tailored for my convenience. Changing them would cause significant annoyance for me.

**Comment by ds5678** [comment]
I'm not very fond of my temporary folder system. Ideally, it could be made unnecessary by memory extraction of file contents (similar to Brotli and GZip), but I'm okay with an argument pull request instead. However, if an argument is added, it will eventually be removed when the ideal solution is implemented.

**Comment by sparr** [comment]
> AssetRipper can only be moved to places where the user has write access

I think this ignores the scenario where it has been installed system-wide by an administrative user and is being run by a non-administrative user, which can happen on any(?) OS. I am guessing that the expected use case is more "portable", with people unzipping the binary and then running it in-place?

**Comment by ds5678** [comment]
> the scenario where it has been installed system-wide by an administrative user and is being run by a non-administrative user

I am not certain this has ever happened for AssetRipper.

> people unzipping the binary and then running it in-place

I've never heard of anyone doing otherwise.
