### ISSUE TITLE
[Bug]: Command line tool requires keyboard input to finish

### ISSUE THREAD

**Issue by sparr** [AssetRipper/AssetRipper#539]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Console Version Linux x64

### Which Unity version did this occur on?

N/A

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

When run from the command line, outputting help text or performing an asset dump or failing due to a parameter error, the program pauses at the end to wait for any keypress before exiting. This is problematic when trying to use the program as part of a script, and mildly annoying when simply typing in another command afterward (so the first letter gets consumed).

I suspect this behavior is intended as a workaround for Windows closing command line windows automatically when their process ends. If that is the case then I think I could write an OS-specific patch to change the behavior on Linux but not Windows (and Mac?).

**Comment by sparr** [comment]
Attempting to work around this in a script via `echo | AssetRipper ...` leads to the following error:

`System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.`

**Comment by ds5678** [comment]
You can pass `-q` as an argument to avoid this.
