### ISSUE TITLE
[Enhancement]: Expose asset Filter options on the command line

### ISSUE THREAD

**Issue by sparr** [AssetRipper/AssetRipper#540]
### Describe the new feature or enhancement

Similar to #537, it would be nice to be able to use the existing Filter functionality from the command line, such as to filter by types. This would greatly reduce the unwanted extraction for my use cases, and presumably for most other folks who are only interested in a single asset type for other reasons. I anticipate many folks would only want to extract textures and/or models.

**Comment by sparr** [comment]
Does completed mean there's already a way to do this that I have overlooked?

**Comment by ds5678** [comment]
"Completed" is just the default for the GitHub close issue button.
