### ISSUE TITLE
[Bug]: Hearthstone export stops at 16%

### ISSUE THREAD

**Issue by Imicek** [AssetRipper/AssetRipper#541]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

Hearthstone

### Which Unity version did this occur on?

I couldn't even extract the files.

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I'm trying to extract Hearthstone files, but after a few exported pieces, the extraction stops working or lags out.
I attached the whole string, I hope it'll help identify the issue.

### Relevant log output

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19044.0
System : Operating System: Windows 64 bit
System : AssetRipper Version: 0.2.3.0
System : AssetRipper Build Type: Release Published
System : UTC Current Time: 09/11/2022 19:22:08
System : UTC Compile Time: Tue Aug 23 06:05:44 UTC 2022
Plugin : Loading plugins...
Plugin : Finished loading plugins.
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : ExportRootPath: D:\Disc\Games\Hearthstone\DatamineV2\AssetRipper_win_x64\Ripped
General : ExportDependencies: False
General : BundledAssetsExportMode: GroupByBundleName
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Decompiled
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
General : Attempting to read files from C:\Program Files (x86)\Hearthstone
Import : PC game structure has been found at 'C:\Program Files (x86)\Hearthstone'
Import : Collecting game files...
Import : Game file 'globalgamemanagers' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
Import : Game file 'level10' has been found
Import : Game file 'level11' has been found
Import : Game file 'level12' has been found
Import : Game file 'level13' has been found
Import : Game file 'level14' has been found
Import : Game file 'level15' has been found
Import : Game file 'level16' has been found
Import : Game file 'level17' has been found
Import : Game file 'level18' has been found
Import : Game file 'level19' has been found
Import : Game file 'level2' has been found
Import : Game file 'level20' has been found
Import : Game file 'level21' has been found
Import : Game file 'level22' has been found
Import : Game file 'level23' has been found
Import : Game file 'level24' has been found
Import : Game file 'level25' has been found
Import : Game file 'level26' has been found
Import : Game file 'level27' has been found
Import : Game file 'level28' has been found
Import : Game file 'level3' has been found
Import : Game file 'level4' has been found
Import : Game file 'level5' has been found
Import : Game file 'level6' has been found
Import : Game file 'level7' has been found
Import : Game file 'level8' has been found
Import : Game file 'level9' has been found
Import : Collecting Streaming Assets...
Import : Files use the 'Mono' scripting backend.
Import : During Mono initialization, found 102 assemblies
General : Finished reading files
General : About to begin export to C:\Users\User\Desktop\ww\Hearthstone
General : Removing any files from a previous export...
Export : Attempting to export assets to C:\Users\User\Desktop\ww\Hearthstone...
Export : Starting pre-export
Export : Starting export
Export : Game files have these Unity versions: 2019.4.37f1
Export : Exporting to Unity version 2019.4.37f1
Export : Preparing for export...
Import : Resource file 'level18.resS' has been loaded
Import : Resource file 'level19.resS' has been loaded
Import : Assembly 'UniTask.Linq' hasn't been found
Import : Assembly 'Unity.InternalAPIEngineBridge.001' hasn't been found
Import : Assembly 'UnityEngine.TestRunner' hasn't been found
Import : Assembly 'Unity.RenderPipelines.Core.ShaderLibrary' hasn't been found
Import : Assembly 'UniTask.DOTween' hasn't been found
Import : Assembly 'UniTask.Addressables' hasn't been found
Import : Assembly 'Unity.RenderPipelines.Universal.Shaders' hasn't been found
Import : Assembly 'UniTask.TextMeshPro' hasn't been found
Import : Assembly 'Unity.2D.Common.Runtime' hasn't been found
Import : Assembly 'Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary' hasn't been found
Import : Assembly 'UnityEngine.TextCoreModule' hasn't been found
Import : Resource file 'globalgamemanagers.assets.resS' has been loaded
Import : Resource file 'resources.assets.resS' has been loaded
Import : Resource file 'resources.resource' has been loaded
Export : Preparation complete. Starting to export now...
ExportedFile : 'PlayerSettings' exported
ExportedFile : 'InputManager' exported
ExportedFile : 'TagManager' exported
ExportedFile : 'AudioManager' exported
ExportedFile : 'ScriptMapper' exported
ExportedFile : 'GraphicsSettings' exported
ExportedFile : 'TimeManager' exported
ExportedFile : 'DelayedCallManager' exported
ExportedFile : 'PhysicsManager' exported
ExportedFile : 'BuildSettings' exported
ExportedFile : 'QualitySettings' exported
ExportedFile : 'NavMeshProjectSettings' exported
ExportedFile : 'Physics2DSettings' exported
ExportedFile : 'ClusterInputManager' exported
ExportedFile : 'RuntimeInitializeOnLoadManager' exported
ExportedFile : 'StreamingManager' exported
ExportedFile : 'VFXManager' exported
ExportedFile : 'level0' exported
ExportedFile : 'level1' exported
ExportedFile : 'level10' exported
ExportedFile : 'level11' exported
ExportedFile : 'level12' exported
ExportedFile : 'level13' exported
ExportedFile : 'level14' exported
ExportedFile : 'level15' exported
ExportedFile : 'level16' exported
ExportedFile : 'LightProbes' exported
ExportedFile : 'level17' exported
ExportedFile : 'Cubemap' exported
ExportedFile : 'LightProbes' exported
ExportedFile : 'level18' exported
ExportedFile : 'Cubemap' exported
ExportedFile : 'level19' exported
ExportedFile : 'level2' exported
ExportedFile : 'LightProbes' exported
ExportedFile : 'level20' exported
ExportedFile : 'LightProbes' exported
ExportedFile : 'level21' exported
ExportedFile : 'LightProbes' exported
ExportedFile : 'level22' exported
ExportedFile : 'LightProbes' exported
ExportedFile : 'level23' exported
ExportedFile : 'LightProbes' exported
ExportedFile : 'level24' exported
ExportedFile : 'LightProbes' exported
ExportedFile : 'level25' exported
ExportedFile : 'LightProbes' exported
ExportedFile : 'level26' exported
ExportedFile : 'LightProbes' exported
ExportedFile : 'level27' exported
ExportedFile : 'LightProbes' exported
ExportedFile : 'level28' exported
ExportedFile : 'level3' exported
ExportedFile : 'level4' exported
ExportedFile : 'level5' exported
ExportedFile : 'level6' exported
ExportedFile : 'level7' exported
ExportedFile : 'level8' exported
ExportedFile : 'level9' exported
ExportedFile : 'Engine 2019.4.37f1' exported
ExportedFile : 'GUI/Text Shader Unlit' exported
Export : Exporting scripts...
Export : Decompiling Assembly-CSharp-firstpass
Export : Decompiling Assembly-CSharp

**Comment by ds5678** [comment]
Your Assembly-CSharp is just big. I can't make ILSpy go any faster.

**Comment by Imicek** [comment]
So what should I do? Or what's wrong? I don't mind waiting for a long time, but I didn't see any progress with the extraction for like 15 minutes, so I closed it.

**Comment by Imicek** [comment]
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9543393/AssetRipper.log)
Here's the log file btw.

**Comment by ds5678** [comment]
I downloaded Hearthstone and was able to decompile everything in the time since your most recent message.

**Comment by Imicek** [comment]
So what might be the issue? Do you have any idea? It stops at 16% for me. I tried to extract the whole Hearthstone folder.

**Comment by ds5678** [comment]
3 potential causes come to mind:
* Ram shortage
* Slow computer
* You selected something in the console.

**Comment by Imicek** [comment]
1) I have 32GB of ram, currently using 38% when the extraction is running
2) I have i9 9900k all cores overclocked to 5.0 Ghz + 3080 Ti
3) I clicked - File -> Open Folder -> Select the whole Hearthstone folder -> Finish loading the list -> Select export all files = here we are at 16%. 😀 Does the Unity version matter in the extraction? I downloaded the 2019 version + I have a 2021 version.

**Comment by Imicek** [comment]
Oh wow, after some more time it actually worked. Never mind, closing the string.
