### ISSUE TITLE
[Bug]: Read 168 but expected 200 for asset type SpriteRenderer.

### ISSUE THREAD

**Issue by loverorser** [AssetRipper/AssetRipper#545]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

Genshin Impact CB1

### Which Unity version did this occur on?

Unity 2017.1.0p122

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Read 168 but expected 200 for asset type SpriteRenderer.
Read 120 but expected 164 for asset type MeshRenderer.
Read 192400 but expected 192416 for asset type Mesh.
And other types such as AnimationClip,AnimatorController and so on.

**Comment by ds5678** [comment]
Mihoyo uses a custom Unity engine.
