### ISSUE TITLE
[Bug]: Crash on Export

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#549]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

A Tale Of Synapse [SteamDB](https://steamdb.info/app/1890810/)

### Which Unity version did this occur on?

2019.4.26f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Hi,
When exporting project Files, AssetRipper crashes:
[Error] : System.Exception: Object's type VideoClip_2019_2_0_a6 isn't assignable from VideoClip_5_6_0_b10

Side Note: Since recently, I notice a lot of errors regarding 'StandaloneWin64Player' (Read 68 but expected 80 for asset type MonoBehaviour. V: 2019.4.26f1 P: StandaloneWin64Player)

See attached log for details.

Keep up the GREAT work ;)
Regards,
Zbuffer

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9620761/AssetRipper.log)

**Comment by ds5678** [comment]
I fixed this locally. I'll push before the next release, which should be within a couple days.

**Comment by ds5678** [comment]
About the monobehaviours, I may work on the switch to AsmResolver really soon
