### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by treenomix** [AssetRipper/AssetRipper#550]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

Genshin Impact cb1

### Which Unity version did this occur on?

Unity 2019

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

https://drive.google.com/file/d/1gO86AKEnb3U-I7W49LWJjLCsKHQxK28p/view?usp=sharing

In old version it typed: "the game structure processor could not find any valid assets"

Game link:

https://drive.google.com/file/d/1Psow3YhpNGxEJ3KB1ry8BpFgecZP-VPa/view?usp=sharing

### Relevant log output

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19044.0
System : Operating System: Windows 64 bit
System : AssetRipper Version: 0.2.4.0
System : AssetRipper Build Type: Release Published
System : UTC Current Time: 09/22/2022 22:26:55
System : UTC Compile Time: Mon Sep 19 15:59:54 UTC 2022
Plugin : Loading plugins...
Plugin : Finished loading plugins.
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : ExportRootPath: D:\cb1\Ripped
General : ExportDependencies: False
General : BundledAssetsExportMode: GroupByBundleName
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Decompiled
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
General : Attempting to read files from D:\cb1\Genshin Impact CBT 1\GS_Data
Import : PC data directory found. Setting root to parent directory
Import : PC game structure has been found at 'D:\cb1\Genshin Impact CBT 1\GS_Data'
Import : Collecting game files...
Import : Game file 'globalgamemanagers' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
Import : Game file 'level2' has been found
Import : Game file 'level3' has been found
Import : Game file 'level4' has been found
Import : Collecting Streaming Assets...
Import [Warning] : The game structure processor could not find any valid assets.
General : Finished reading files
[Error] : AssetRipper.GUI.Exceptions.GameNotFoundException: Exception of type 'AssetRipper.GUI.Exceptions.GameNotFoundException' was thrown.

**Comment by ds5678** [comment]
Genshin Impact uses a custom Unity engine

**Comment by treenomix** [comment]
> Genshin Impact использует собственный движок Unity.

Thank you for help
