### ISSUE TITLE
[Other]: The app doesn't start on MacOS

### ISSUE THREAD

**Issue by Razenpok** [AssetRipper/AssetRipper#551]
### Describe the issue

Hi

I have an M1 Macbook, and I've downloaded the ripper using this link:
https://github.com/AssetRipper/AssetRipper/releases/download/0.2.4.0/AssetRipper_mac_arm64.zip

I've ran `chmod +x` on `AssetRipper` file, and I've even ran `chmod -R +x` on the whole folder, so the files should all have the needed permissions. The problem is that I only get this:

```
razen@Andreis-MBP AssetRipper_mac_arm64 % ./AssetRipper       
zsh: killed     ./AssetRipper
```

**Comment by Razenpok** [comment]
... yeah, I've got no `AssetRipper.log` since the app couldn't even run

**Comment by ds5678** [comment]
Neither I nor any of the major contributors, possess a Mac. If this is something you care about, you should contribute improved Mac support.

**Comment by Razenpok** [comment]
Alright, fair enough
I've got it running by starting it up from an IDE, so it will need some additional investigation on why it wouldn't run as a standalone executable.

**Comment by RY-Hikaru** [comment]
@Razenpok @ds5678 
Hello, I have an M1 Macbook and I also encounter this "kill" problems.
But the "no arm" version (AssetRipper_mac_x64) is works for me on my M1 Macbook.
You can try it instead of the "arm" one.

**Comment by andyoneal** [comment]
macOS doesn't allow arm64 apps to run if they're completely unsigned. you could remove quarantine, chmod +x, and ad-hoc sign it. or you could just use the x64 version as suggested above.

**Comment by Helloyunho** [comment]
I tried self-signing the binary(and yes I have a paid dev account), but it crashes with bus error
![CleanShot 2022-10-09 at 00 26 43](https://user-images.githubusercontent.com/10192625/194715050-97e4ff27-3e8a-4abc-8aa1-00cba88a9fbd.png)

And from lldb, I found that the crash reason is bad access
![CleanShot 2022-10-09 at 00 28 16](https://user-images.githubusercontent.com/10192625/194715170-480a0520-4b87-44a5-af07-e0130d0bcae3.png)

**Comment by Razenpok** [comment]
Love ya guys ❤️
