### ISSUE TITLE
Cannot decompile Among Us correctly

### ISSUE THREAD

**Issue by Pietrodjaowjao** [AssetRipper/AssetRipper#562]
### Describe the issue

It gives errors with TextMeshPro and other basic things, and it detects wrong unity version, probably this is causing the conflict

**Comment by ds5678** [comment]
> TextMeshPro and other basic things

This is not nearly as basic as you might believe.

> it detects wrong unity version

Unless the detected version is zero, I guarantee you it doesn't.
