### ISSUE TITLE
[Bug]: System.IO.IOException: The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by Q4st** [AssetRipper/AssetRipper#571]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

apk:https://m.apkpure.com/cn/%E6%99%82%E4%B9%8B%E7%B4%84/com.meta.twigp/amp

### Which Unity version did this occur on?

2018.4.35

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

[Bug]: System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. 'F:\Unity Project\SZY\globalgamemanagers\ExportedProject\assets\cc_meshes\actors\players\pm\pm_body033\pm_body033_||_g_mesh.asset'

### Relevant log output

[Uploading AssetRipper.log…]()

**Comment by ds5678** [comment]
This has already been resolved.
