### ISSUE TITLE
Error export(System.Exception: Object's type Texture2D_2020_2_0_a16 isn't assignable from IShader)

### ISSUE THREAD

**Issue by ducloc11ts** [AssetRipper/AssetRipper#572]
Are you on the latest version of AssetRipper?
Yes, I'm on the latest release of AssetRipper.

Which release are you using?
GUI Version Windows x64

Which game did this occur on?
Critical Ops:
 https://thejaspel.itch.io/backpack-hero.
https://drive.google.com/file/d/1iAJx9Ec4lQ22Fe1ZirupIeeUNsEhegoG/view?usp=sharing

Which Unity version did this occur on?
Unity 2021.3.9

Is the game Mono or IL2Cpp?
IL2Cpp

Describe the issue.
Asset Ripper just doesn't export the game(Critical Ops). Could You please fix it. I gave you the log down here.

Relevant log output
https://drive.google.com/file/d/1D8YSI7W8WPwA_ALIamIDfCM5hwyC92ar/view?usp=sharing

**Comment by ds5678** [comment]
It sounds like your game uses a custom Unity engine. This kind of error can't happen on the normal engine.
