### ISSUE TITLE
[Bug]: Empty Assets

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#577]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

n/a

### Which Unity version did this occur on?

n/a

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Hi,
When using the latest commit files  as of today (14th ocober), and building the solution myself,
When exporting a project, ScriptableObjects and AnimatorControllers are empty. (I haven't checked other file)
All is fine when using the latest 'official release' (0.2.4.2)

Tested on a couple of games with different Unity Versions (2019 and 2021)

Just to let you guys know...
Kind regards,
Zbuffer

### Relevant log output

n/a

**Comment by ds5678** [comment]
I did a major refactor, so the custom audio mixer and animator controller exporters are currently disabled. They still need ported to the new framework.

Similarly, MonoBehaviour deserialization was removed in the refactor. However, it was recently implemented into the new framework, so I'm not sure what's going on with your scriptable objects.
