### ISSUE TITLE
[Bug]: Failed to load game content: An item with the same key has already been added. Key: level10

### ISSUE THREAD

**Issue by Salmaaan324242** [AssetRipper/AssetRipper#578]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

Bus simulator indonesia

### Which Unity version did this occur on?

2020

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Failed to load game content: An item with the same key has already been added. Key: level10

**Comment by ds5678** [comment]
This situation is already handled on the latest commit.
