### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by UserIdklol** [AssetRipper/AssetRipper#582]
### Describe the new feature or enhancement

Could you please add the correct script export?

**Comment by ds5678** [comment]
You're going to have to be more specific.

**Comment by UserIdklol** [comment]
> Вам придется быть более конкретным.

I mean, when decompiling scripts, unity meta files were generated

**Comment by UserIdklol** [comment]
> You're going to have to be more specific.

and have scripts with code

**Comment by ds5678** [comment]
Please be sure you have uploaded your `AssetRipper.log` file. It is in the same folder as the exe file. :)
