### ISSUE TITLE
[Bug]: System.IO.IOException: 文件名、目录名或卷标语法不正确

### ISSUE THREAD

**Issue by LLH-666** [AssetRipper/AssetRipper#583]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2020.3.39

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

System.IO.IOException: 文件名、目录名或卷标语法不正确

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9857759/AssetRipper.log)

**Comment by ds5678** [comment]
I think this has already been resolved on the latest commit.

**Comment by LLH-666** [comment]
I used the latest GUI version (0.2.4.2) . When I was exporting, I reported an error, which caused the export to be interrupted.

**Comment by ds5678** [comment]
The latest commit is newer than the latest release.

**Comment by LLH-666** [comment]
Excuse me, if it is convenient to answer, when will I be able to see the latest release

**Comment by ds5678** [comment]
Are you asking when the next release will be?

**Comment by LLH-666** [comment]
yes

**Comment by ds5678** [comment]
Normally, I like to do weekly releases, but this particular release is more significant than others. It includes lots of changes. In making these changes, I (intentionally) broke some things in the project. That needs to be rectified before the project is in a release ready state. I can't say when that will happen.
