### ISSUE TITLE
[Bug]: No MonoBehavior scripts in the file, or their names do not match the file name

### ISSUE THREAD

**Issue by CGray1234** [AssetRipper/AssetRipper#584]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

Beat Saber 0.10.1
https://steamdb.info/depot/620981/history/?changeid=M:6316038906315325420

### Which Unity version did this occur on?

2017.4.1f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Everything works fine, except for the scripts. Every script always gives the same message "No MonoBehavior scripts in the file, or their names do not match the file name," but it matches the file name. I'm not sure if this is supposed to happen or what you do to fix it.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9863269/AssetRipper.log)

**Comment by ds5678** [comment]
I think it just has script errors and Unity is giving a misleading error message.

**Comment by CGray1234** [comment]
I don't see any issues with any of the scripts though... is there a certain way to correctly export scripts?
