### ISSUE TITLE
[Other]: Wondering about shader graphs

### ISSUE THREAD

**Issue by oldsportsgit** [AssetRipper/AssetRipper#585]
### Describe the new feature or enhancement

I am just wondering is it easier to make a shader graph decompiler than a regular ol shader decompiler?
and also are you going to implement that to your project or no?

**Comment by ds5678** [comment]
I didn't check, but I think it's a safe assumption that shader graphs compile to regular shaders with no additional metadata included. In light of that, decompiling to shader graph would be more difficult and less accurate than decompiling as traditional shaders.
