### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by p0008874** [AssetRipper/AssetRipper#604]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Tales of Grimm(The Mobile Game)

### Which Unity version did this occur on?

2019.4.40f1

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

![image](https://user-images.githubusercontent.com/75534590/201703603-8f4dea82-c8f6-49f4-887d-78761b42ab63.png)
When you drag and drop into AssetRipper will display No unity game or assets bundle was found in the dropped file.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10004750/AssetRipper.log)

**Comment by ds5678** [comment]
The developer modified that file to prevent ripping.
