### ISSUE TITLE
DllNotFoundException

### ISSUE THREAD

**Issue by JuJuGamesQ** [AssetRipper/AssetRipper#614]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Bendy And The Dark Revival

### Which Unity version did this occur on?

2021.3.6.8233869

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Whenever I'm Around 2% of decompiling bendy and the dark revival the software just tells me to check the logs without any explanation on why it broke

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10078438/AssetRipper.log)

**Comment by ds5678** [comment]
> [Error] : System.DllNotFoundException: Dll was not found.

This error is almost never my fault. However, in your case, it might not matter since that particular dll is being used much less often on the latest alpha build. In fact, I have plans to remove it entirely in the near future.

**Comment by FoobianBlock** [comment]
I'm getting the same error (what a coincidance that you opened this issue 22 hours ago I guess), with a few differences. I'll list them here:

### Which game did this occur on?
SimRail Demo

### Which Unity version did this occur on?
2019.3.0.43809

### Is the game Mono or IL2Cpp?
IL2Cpp

### Describe the issue.
```
System.DllNotFoundException: Dll was not found.
   at AssetRipper.Library.Exporters.Textures.CrunchHandler.DecompressUnityCRN(Byte[] pSrc_file_data, Int32 src_file_size, IntPtr& uncompressedData, Int32& uncompressedSize)
```
while exporting all textures from the SimRail Demo

### Relevant log output
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10086530/AssetRipper.log)

**Comment by ds5678** [comment]
I won't look at any potential bugs on `0.2.4.2`. Use the latest alpha build.

https://nightly.link/AssetRipper/AssetRipper/workflows/publish/master/AssetRipper_win_x64.zip

**Comment by FoobianBlock** [comment]
Tried with the build you sent me and I get the exact same error

**Comment by ds5678** [comment]
Doesn't happen on my machine, nor on lots of other people's machines.

> [Error] : System.DllNotFoundException: Dll was not found.

Again, this error is almost never my fault.

**Comment by FoobianBlock** [comment]
There we go, fixed it! The issue was Windows blocking the DLLs

The fix is right-clicking all DLLs in the executable's folder and trustign them with the checkbox in the bottom right. (It's in German, but the checkbox will be in the same place
![grafik](https://user-images.githubusercontent.com/89279039/203863767-9e83de65-9438-4637-add5-d5e0cf056048.png)
