### ISSUE TITLE
[Enhancement]: Image Export Format - don't convert to jpg/png etc - just leave as raw data

### ISSUE THREAD

**Issue by mrdude2478** [AssetRipper/AssetRipper#615]
### Describe the new feature or enhancement

Please can you add the abiltiy to just export raw image data instead of converting to a bitmap or jpeg/png etc, as twizzled graphics that are converted lose their twizzle data and can't be de-twizzled using other tools.

Also can you add file offset information into the basic information box?

Thanks

**Comment by ds5678** [comment]
> Also can you add file offset information into the basic information box?

I told you in Discord that this won't happen and gave you some alternatives to acquire the information.

> lose their twizzle data

I have doubts that this information is stored. If it was, I would already be de-swizzling the images in the decoder.

It should depend only on the `BuildTarget` of the `SerializedFile`. I presume your game is Nintendo Switch, which has swizzling. AssetRipper does not currently de-swizzle Switch textures.

**Comment by mrdude2478** [comment]
OK thanks, I didn't see any reply on discord and just checked and still don't see anything after my initial post. I see in the Yaml box there is an offset in int format - can you add the abilty to copy this information as there is no way to copy it, also can you put in brackets hex format for the offset? I don't need assetripper to de-swizzle ps4 or swtich game graphics as I just need to get the offsets of the file, then I can rip it myself from the asset to raw and the deswizzle it to dds and filp it manually.

**Comment by ds5678** [comment]
I would recommend you use [AssetsTools.NET](https://github.com/nesrak1/AssetsTools.NET) for your use case.
