### ISSUE TITLE
[Bug]: Volume Label Syntax is Incorrect

### ISSUE THREAD

**Issue by TravelerJay** [AssetRipper/AssetRipper#616]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Bonelab

### Which Unity version did this occur on?

2021.3.5

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Incorrect volume label syntax error appeared in the console when trying to export an animation (that's what I believe it is saying in the console)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10096332/AssetRipper.log)

**Comment by ds5678** [comment]
This has already been solved on the latest commit.

**Comment by TravelerJay** [comment]
Oh okay got it. I'm guessing I just need to wait for the newest release to come out within the next day or two from looking at the release schedule. Thank you very much!
