### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by Soft-me** [AssetRipper/AssetRipper#631]
### Question

Version: 
AssetRipper_win_x64.zip

System:
Windows 10

Hi, I was trying to export shader to shaderLab using following settings:
![image](https://user-images.githubusercontent.com/35207058/205470437-f83e2c95-662a-43b0-8949-d0820551c300.png)

The code should be simple like following:
```
v2f vert(appdata_full v)
{
      v2f o;
      o.position = UnityObjectToClipPos(v.vertex);
}
```
But I get this:
```
v2f vert(appdata_full v)
{
      v2f o;
      float4 tmp0;
      float4 tmp1;
      tmp0 = v.vertex.yyyy * unity_ObjectToWorld._m01_m11_m21_m31;
      tmp0 = unity_ObjectToWorld._m00_m10_m20_m30 * v.vertex.xxxx + tmp0;
      tmp0 = unity_ObjectToWorld._m02_m12_m22_m32 * v.vertex.zzzz + tmp0;
      tmp0 = tmp0 + unity_ObjectToWorld._m03_m13_m23_m33;
      tmp1 = tmp0.yyyy * unity_MatrixVP._m01_m11_m21_m31;
      tmp1 = unity_MatrixVP._m00_m10_m20_m30 * tmp0.xxxx + tmp1;
      tmp1 = unity_MatrixVP._m02_m12_m22_m32 * tmp0.zzzz + tmp1;
      tmp0 = unity_MatrixVP._m03_m13_m23_m33 * tmp0.wwww + tmp1;
      o.position = tmp0;
}
```
I wonder if it's still uncompleted or I just missing something?

**Comment by ds5678** [comment]
In my opinion, those are the same thing. The only difference is that in the decompiled version, the UnityObjectToClipPosition call has been inlined and replaced with its code.

**Comment by SamboyCoding** [comment]
Which makes sense, because UnityObjectToClipPos is marked as inline:
```hlsl
// Tranforms position from object to homogenous space
inline float4 UnityObjectToClipPos( in float3 pos )
{
#if defined(UNITY_SINGLE_PASS_STEREO) || defined(UNITY_USE_CONCATENATED_MATRICES)
    // More efficient than computing M*VP matrix product
    return mul(UNITY_MATRIX_VP, mul(unity_ObjectToWorld, float4(pos, 1.0)));
#else
    return mul(UNITY_MATRIX_MVP, float4(pos, 1.0));
#endif
}
```

**Comment by ds5678** [comment]
I'm going to close this because it seems unlikely that we'll ever be able to outline the method call.

Cleaner matrix multiplication is a possibility once unit tests are implemented.
