### ISSUE TITLE
[Bug]: Shader not export properly

### ISSUE THREAD

**Issue by vuphanus** [AssetRipper/AssetRipper#637]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://steamdb.info/app/1284410/

### Which Unity version did this occur on?

Unity 2021.3.11

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

AssetRipper was work fine with shader with old game version (Unity 2018.4.36). After game update recently, shader export dosen't work anymore. Although AssetRipper doesn't show any error in log, but shader simply not work.

Some error when open with Asset Studio GUI.
![err23](https://user-images.githubusercontent.com/90450323/206887682-7f213813-df3b-4299-b5db-acf0f0fdfdfd.png)

Attachment with two version. _good file name is old version, _bad file name is newest version.
[Gwent.zip](https://github.com/AssetRipper/AssetRipper/files/10201514/Gwent.zip)

**Comment by ds5678** [comment]
Please be sure you have uploaded your AssetRipper.log file. It is in the same folder as the exe file. :)

**Comment by vuphanus** [comment]
Thank you and never mind. I think it's because missing monoscript so that why it's not work properly.

**Comment by ds5678** [comment]
Mono scripts are completely unrelated to shaders.
