### ISSUE TITLE
[Bug]: Script .meta files dont export if the game is Mono, but if its IL2CPP, the script .meta files export.

### ISSUE THREAD

**Issue by githubexplorer2342** [AssetRipper/AssetRipper#638]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

Any Unity version

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

If i export any game in the latest Alpha thats Mono, the script .meta files wont export at all and will just be .cs files. But if the game is IL2CPP, the script .meta files export correctly.

Above is proof of it happening.

![Screenshot 2022-12-12 225109](https://user-images.githubusercontent.com/104936164/207151831-dd3b1b35-f645-4686-a76e-26c4f7422a8a.png)

**Comment by ds5678** [comment]
Thank you for reporting this. I have reproduced the issue on my machine and will have a fix out soon.
