### ISSUE TITLE
[Bug]: Shader Error

### ISSUE THREAD

**Issue by KnatteAnka** [AssetRipper/AssetRipper#640]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Timberborn Stable Update 3

### Which Unity version did this occur on?

2022.1.22f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Crash when trying to export game files. 
Tried different versions but still gives errors.
Before last update of the game (2022.1.6) it did work no problem

Have installed unity 2022.1.22 just to be sure that is not the problem.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10240299/AssetRipper.log)
Settings used:
![image](https://user-images.githubusercontent.com/10638776/207957832-a4efe659-9a61-4f12-a2ab-397f00566aad.png)

**Comment by ds5678** [comment]
This happened because that version of Unity did not have its type trees dumped yet. It has been fixed locally and will be part of the next release.

**Comment by KnatteAnka** [comment]
👍
