### ISSUE TITLE
[Bug]: Assetripper makes an entire new directory to export the game if the folder has spaces

### ISSUE THREAD

**Issue by githubexplorer2342** [AssetRipper/AssetRipper#641]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

Not Applicable

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

In the latest Alpha, if a directory has spaces, it will create a whole new folder with the same name but with %20 instead of spaces to export the game it was given.

Above shows the new folder it created:

![image](https://user-images.githubusercontent.com/104936164/208181351-cc3cc610-e397-45e5-a8ea-bdf449aecb1d.png)

Is this normal or a bug? It worked fine before and actually exported into the folder with spaces.

**Comment by ds5678** [comment]
I greatly appreciate your vigilance in testing the alpha builds. Without you, this bug would have been part of the next release, so thank you for reporting it.

**Comment by githubexplorer2342** [comment]
> I greatly appreciate your vigilance in testing the alpha builds. Without you, this bug would have been part of the next release, so thank you for reporting it.

No problem! I normally test Alpha builds to see if any new bugs pop up so they can be fixed. Basically, an alpha tester 😄

**Comment by ds5678** [comment]
It helps a ton. I wouldn't have noticed this without you.

**Comment by githubexplorer2342** [comment]
> It helps a ton. I wouldn't have noticed this without you.

The reason why i have become a alpha tester was because i havent noticed many using the alpha versions and especially a few bugs can go off the radar like this one. So i decided to become a frequent tester 😄 i hope more testers will be around in the future.
