### ISSUE TITLE
[Bug]: Error happends in export

### ISSUE THREAD

**Issue by Caritusy** [AssetRipper/AssetRipper#644]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Game name : I Wanna Be The Creator
Steam link : https://store.steampowered.com/app/913550

### Which Unity version did this occur on?

Unity 2020.3.17 f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

The error happend when I tried to export all the files.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10251838/AssetRipper.log)

**Comment by Caritusy** [comment]
I have the game's Mono version and IL2CPP version. To sure the file could be running in my unity i used mono version,now i'll try the il2cpp version.

**Comment by ds5678** [comment]
You have duplicate assemblies.
