### ISSUE TITLE
[Bug]: Default audio export fails to find audio data on version 3

### ISSUE THREAD

**Issue by aldelaro5** [AssetRipper/AssetRipper#646]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest pre-release of AssetRipper.

### Which release are you using?

Linux x64

### Which game did this occur on?

Bug Fables: The Everlasting Sapling 

https://steamdb.info/app/1082710/

### Which Unity version did this occur on?

2018.4.12f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

If I export everything default using version 0.3.0.0, I get yaml files instead of ogg files for the audio while on 0.2.4.2, I get proper OGG files which means this is a regression. ds5678 did not know when asked what could cause this.

According to the log files, it seems it couldn't find the audio data, but it could in stable versions before.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10259097/AssetRipper.log)

**Comment by ds5678** [comment]
Can I have a log from `0.2.4.2`? The changes affecting audio should be negligible.
https://github.com/AssetRipper/AssetRipper/compare/0.2.4.2...0.3.0.0

**Comment by aldelaro5** [comment]
Here

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10262657/AssetRipper.log)
