### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by chenyicheng311** [AssetRipper/AssetRipper#648]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

2020.3.35f1c2

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Their tile cannot be exported.
I got an error

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10266161/AssetRipper.log)

**Comment by ds5678** [comment]
This is an outdated version of AssetRipper.

**Comment by chenyicheng311** [comment]
> This is an outdated version of AssetRipper.

But, i use 0.2.4.2
