### ISSUE TITLE
[Bug]: AssetRipper crashes if you click "cancel" instead of clicking "select folder" when exporting

### ISSUE THREAD

**Issue by CGray1234** [AssetRipper/AssetRipper#650]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest pre-release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Beat Saber 0.10.1
https://steamdb.info/depot/620981/history/?changeid=M:6316038906315325420

### Which Unity version did this occur on?

2017.4.1f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Whenever you try to export and click "cancel," AssetRipper crashes.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10283587/AssetRipper.log)

**Comment by ds5678** [comment]
I'll investigate.
