### ISSUE TITLE
[Bug]: "Cannot decompile this assembly to a SDK style project"

### ISSUE THREAD

**Issue by JohnCorby** [AssetRipper/AssetRipper#658]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Outer Wilds ([https://steamdb.info/app/753640/depots/](url))

### Which Unity version did this occur on?

2019.4.39

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

![image](https://user-images.githubusercontent.com/26337121/210033151-5d595e79-3473-46af-afa2-508bda4d563e.png)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10323072/AssetRipper.log)

**Comment by ds5678** [comment]
Should be fixed in 54340d95a49b75e3d689f0882ed00d28afbb2b7f
