### ISSUE TITLE
[Bug]: Fonts material problems

### ISSUE THREAD

**Issue by aldelaro5** [AssetRipper/AssetRipper#668]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Linux x64

### Which game did this occur on?

My own test project here (ignore the name, it doesn't have to do with shaders):

[ShadersExportTest.zip](https://github.com/AssetRipper/AssetRipper/files/10327941/ShadersExportTest.zip)

Issue is very likely affecting Bug Fables: https://steamdb.info/app/1082710/

### Which Unity version did this occur on?

2018.4.12f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

If you check in my project, you will see there is a font assigned to a text mesh that is rendered in front of the camera. Notice that there is no texture or material inside the project, but they are present in the asset explorer (they were auto generated on import).

If I extract with AssetRipper, now the render is wrong. This is because AssetRipper extracted the font material, but the project is opened after extraction, it still autogenerate the font material, but binds the TextMesh to the wrong one that AssetRipper put. I have to remove the material and reset the font to the textmesh so it renders.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10327943/AssetRipper.log)

**Comment by ds5678** [comment]
This is my current understanding of the problem:

* One of the Font properties is a PPtr to a Material
* The referenced material is not shared with any other fonts
* The autogenerated material shows up in an expand out menu similar to imported 3d models
* If the autogenerated material is referenced from a Monobehaviour in the editor, the path id is some consistent number like 2100000

Assuming my understanding is correct, redirecting those materials should be fairly easy. 

* IUnityObjectBase has a property for setting the MainAsset. During the asset processing, for each font, find the referenced material and set its main asset as the font.
* Make the font asset exporter handle materials with a font main asset.
* The font export collection needs to have a `IMaterial?` property. GetExportId needs to return the consistent id for the material. Assets needs to be overridden to return both assets.

**Comment by ds5678** [comment]
> This is my current understanding of the problem

@aldelaro5 in order to move forward with this issue, I need you to verify that my understanding is correct.

**Comment by ds5678** [comment]
> If the autogenerated material is referenced from a Monobehaviour in the editor, the path id is some consistent number like 2100000

I verified this to be correct.

@aldelaro5 do you have a compiled build?

**Comment by aldelaro5** [comment]
It's been a while, but I am p sure I still had the project and made a windows x64 build with it.

[fontMaterial.zip](https://github.com/AssetRipper/AssetRipper/files/11107523/fontMaterial.zip)

Here, I didn't had time to test extraction, but it seems to run fine and render the text correctly.

**Comment by ds5678** [comment]
> fontMaterial.zip

@aldelaro5 Do I have your permission to add these files to the [compiled test projects repository](https://github.com/AssetRipper/TestProjectsCompiled) under its [MIT license](https://github.com/AssetRipper/TestProjectsCompiled/blob/3ac05167bdbb8411f19e61e138e1aca97369fe26/LICENSE), or would you be willing to make a pull request with the files? That would be even better.

**Comment by aldelaro5** [comment]
I am currently busy on another project, but you do have my permission.

**Comment by ds5678** [comment]
> I am currently busy on another project, but you do have my permission.

https://github.com/AssetRipper/TestProjectsCompiled/commit/2fc3801d59593a654832549712f894e88fd06f54
