### ISSUE TITLE
[Bug]: AssetRipper crashes if you accidentally press the export button without loading a game

### ISSUE THREAD

**Issue by githubexplorer2342** [AssetRipper/AssetRipper#674]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

Not Applicable

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

If you press export all or any other export option without loading a game in the program, it will throw a error and then will stop responding or it will close. On 0.2.4.2, this error dosent happen.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10346017/AssetRipper.log)

**Comment by ds5678** [comment]
Thanks for the report!

**Comment by githubexplorer2342** [comment]
You're welcome!
