### ISSUE TITLE
[Bug]: Specified argument was out of the range of valid values. (Parameter 'index')

### ISSUE THREAD

**Issue by wjdgustn** [AssetRipper/AssetRipper#676]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://steamdb.info/app/977950

### Which Unity version did this occur on?

2021.3.10f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

I downloaded game with steamdepotdownloader for clean game build, but I can't use AssetRipper.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10353693/AssetRipper.log)

**Comment by ds5678** [comment]
Please try again on the [latest alpha build](https://nightly.link/AssetRipper/AssetRipper/workflows/publish/master/AssetRipper_win_x64.zip) and send a new log.

**Comment by wjdgustn** [comment]
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10362181/AssetRipper.log)

**Comment by ds5678** [comment]
Something is very messed up with this game. It should not have this many read failures. The couple shader ones are normal, but everything after is unusual.

Are you sure it's not using a custom Unity engine? The amount of failures here is suspiciously high. Looking at your profile, I notice you're a programmer. I encourage you to investigate whatever is going on here, both with the MonoBehaviours and the BuildSettings. I've never had the BuildSettings fail for a normal game, which is why I suspect modifications to the engine.

**Comment by wjdgustn** [comment]
AssetRipper worked for manifest [5006313805043720999(previous build)](https://steamdb.info/depot/977953/history/?changeid=M:5006313805043720999), but it's not working for manifest [8617587627432287742(latest build)](https://steamdb.info/depot/977953/history/?changeid=M:8617587627432287742).
I don't think they changed the Unity engine.

**Comment by ds5678** [comment]
If you gift it to me on Steam, I'll take a brief look at what's going on.

**Comment by ds5678** [comment]
Closed because of inactivity

**Comment by ImanCol** [comment]
Same Error from https://steamdb.info/app/2079120/

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at AssetRipper.Assets.Generics.AssetList`1.get_Item(Int32 index) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Generics\AssetList.cs:line 60
   at AssetRipper.Processing.Scenes.SceneHelpers.TryGetScenePath(AssetCollection serializedFile, IBuildSettings buildSettings, String& result) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\Scenes\SceneHelpers.cs:line 79
   at AssetRipper.Processing.Scenes.SceneDefinitionProcessor.Process(GameBundle gameBundle, UnityVersion projectVersion) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\Scenes\SceneDefinitionProcessor.cs:line 107
   at AssetRipper.Export.UnityProjects.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 123
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\Managers\UIImportManager.cs:line 20

**Comment by ds5678** [comment]
@ImanCol I just pushed a commit which resolves the error you pasted.

**Comment by ImanCol** [comment]
> @ImanCol I just pushed a commit which resolves the error you pasted.

Thank you very much for the quick solution. Is it possible to compile or is it compatible with a .Net other than 7?

**Comment by ds5678** [comment]
@ImanCol https://github.com/AssetRipper/AssetRipper/actions/workflows/publish.yml

**Comment by ImanCol** [comment]
> @ImanCol https://github.com/AssetRipper/AssetRipper/actions/workflows/publish.yml

Hi, thanks for the builds. I have already tried the latest devices and the problem seems to persist. I can only provide the information generated by the .log
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12114401/AssetRipper.log)
[compile_time.txt](https://github.com/AssetRipper/AssetRipper/files/12114403/compile_time.txt)

**Comment by ds5678** [comment]
I accidentally caused #914 in my commit. When I fix it, your issue will be fixed too.

**Comment by ds5678** [comment]
Fixed in 9e4c64e60b1e8c0cc5e42ee646ff1ad2f6d59141
