### ISSUE TITLE
Export all files with saving original file guid

### ISSUE THREAD

**Issue by XsozSF2** [AssetRipper/AssetRipper#680]
### Describe the new feature or enhancement

I think you should add an option to export all files with original file guids (dependencies in globalgamemanagers) instead of generating a new one for each file. It will allow better project re-import in unity

**Comment by ds5678** [comment]
> original file guids

These do not exist in release builds, and even if they did, using them would not be trivial. Assets in the game are substantially different from assets in Unity Editor. A lot of asset processing happens in AssetRipper, including the creation of new assets which get deleted when the game is compiled.
