### ISSUE TITLE
[Bug]: Errors with all monobehavior at import time

### ISSUE THREAD

**Issue by HijackHornet** [AssetRipper/AssetRipper#687]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

WobbleDogs https://steamdb.info/app/1424330/

### Which Unity version did this occur on?

2019.4.23f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

When i try and load the game Exe, i see many errors regading monobehaviors `GoalObject` and `DogLook`, but i think its a separate issue. I'll share those monobehavior properties just in case.
If i then select Dll export without renaming i end up with a broken project where every single one Gameobject in the game has either "unknown script" or scripts that cannot be loaded "check compiler errors or dependencies"

### To reproduce
- Open asset ripper, leave the default values except for Dll export without renaming
- Open file > Wobbledogs.exe
- Export all
- Move the exported project into a new Unity project
![image](https://user-images.githubusercontent.com/2307228/212532734-fa3cc286-fde7-4b82-b8b9-27189487f00f.png)
- With the empty scene i get those errors
![image](https://user-images.githubusercontent.com/2307228/212534000-c60bcfb8-c13a-44d1-b37f-90419bfd3472.png)
- With the main menu i get a lot more as all scene objects have this for example
![image](https://user-images.githubusercontent.com/2307228/212534034-cfa84921-ade4-41dc-8bf0-0059a573e623.png)
This applies to all scripts on all gameobjects
- Since it says Unity.UI is missing i installed it but the errors remains.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10419819/AssetRipper.log)
[Doglook.txt](https://github.com/AssetRipper/AssetRipper/files/10420051/Doglook.txt)
[GoalObject.txt](https://github.com/AssetRipper/AssetRipper/files/10420056/GoalObject.txt)

**Comment by ds5678** [comment]
> Dll export without renaming

This option does not produce a valid project without a script to undo Unity overwriting the Assembly-CSharp dll.
