### ISSUE TITLE
[Bug]: Localization feature isn't working

### ISSUE THREAD

**Issue by RealShiroTheNerd** [AssetRipper/AssetRipper#688]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

Not Applicable

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

Selecting another language simply does not work, even after restarting.

### Relevant log output

[First log (changing the language didn't do anything)](https://github.com/AssetRipper/AssetRipper/files/10419994/AssetRipper.log)
[Log after restarting](https://github.com/AssetRipper/AssetRipper/files/10419999/AssetRipper.log)

**Comment by ds5678** [comment]
Not a bug. I ran into some licensing issues and had to wipe the contributed localizations. This was a one-time thing and won't happen again. However, until new localizations are contributed, the tool will be English-only. If you would like to do so, localizations can be contributed here:
or an element of flds describes a field that is not contained in the field described by the succeeding element of flds

**Comment by Dystnine** [comment]
> Not a bug. I ran into some licensing issues and had to wipe the contributed localizations. This was a one-time thing and won't happen again. However, until new localizations are contributed, the tool will be English-only. If you would like to do so, localizations can be contributed here: https://weblate.samboy.dev/engage/assetripper/

![无标题](https://user-images.githubusercontent.com/123282693/230780919-20015252-19ad-4932-8c64-7f123a713dd7.png)
Localization feature still not working

**Comment by ds5678** [comment]
>Localization feature still not working

Your experience is completely unrelated to the reason this issue was originally posted. That dropdown just doesn't display the language name, but it still works. One of the Avalonia updates must have slightly broken it.
