### ISSUE TITLE
[Bug]: Monobehaviours are blank in the inspector

### ISSUE THREAD

**Issue by CGray1234** [AssetRipper/AssetRipper#690]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Beat Saber 0.10.1

### Which Unity version did this occur on?

2017.4.1f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

In all monobehaviours, they are completely blank in the inspector and I cannot use them in scripts.
![Screenshot (121)](https://user-images.githubusercontent.com/102427011/212591058-f8909b7e-efd5-4f95-8f95-2b922def983a.png)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10422236/AssetRipper.log)

**Comment by ds5678** [comment]
You probably have compile errors.

**Comment by CGray1234** [comment]
You were right, had to fix some scripts and it all worked like magic! Thanks so much!
