### ISSUE TITLE
[Bug]: Separated static meshes not flagged as static

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#702]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

2020.3.33

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Hello again ;)

After export and checking in Unity, I noticed that when I choose the 'separate static mesh option', the corresponding gameObject (the one holding the meshfilter of a static mesh, in a scene or prefab) is not marked as 'static'.
I think the 'm_StaticEditorFlags' Field of the gameObject is not updated, when separating the combined meshes... ?

Just to lt you know...

Have a nice day ;)
Zbuffer

**Comment by ds5678** [comment]
I investigated this a little bit. `m_StaticEditorFlags` is indeed an editor-only field. Its enum is this:
```cs
/// <summary>
/// Full Name: "UnityEditor.StaticEditorFlags"<br />
/// Summary: Static Editor Flags.<br />
/// Summary: Describes which Unity systems consider the GameObject as static, and include the GameObject in their precomputations in the Unity Editor.<br />
/// 3.5.0f5 to Max
/// </summary>
[Flags]
public enum StaticEditorFlags
{
	/// <summary>
	/// Summary: If enabled the object will be considered by the lightmapper and contribute to Global Illumination. Please see ReceiveGI to select how it will receive Global Illumination.<br />
	/// Summary: Include the GameObject when precomputing lighting data.<br />
	/// Summary: When you enable this property, Unity includes the target in Unity.<br />
	/// Summary: Include the target in global illumination calculations.<br />
	/// 2019.2.0a6 to Max
	/// </summary>
	ContributeGI = 1,
	/// <summary>
	/// Summary: Considered static for lightmapping.<br />
	/// Summary: Include the GameObject when precomputing lighting data.<br />
	/// Obsolete Message: 3.5.0f5 to 2019.2.0a6<br />
	/// null<br />
	/// Obsolete Message: 2019.2.0a6 to Max<br />
	/// Enum member StaticEditorFlags.LightmapStatic has been deprecated. Use StaticEditorFlags.ContributeGI instead. (UnityUpgradable) -&gt; ContributeGI<br />
	/// 3.5.0f5 to Max
	/// </summary>
	LightmapStatic = 1,
	/// <summary>
	/// Summary: Considered static for occlusion.<br />
	/// Summary: Mark the GameObject as a Static Occluder in the occlusion culling system.<br />
	/// 3.5.0f5 to Max
	/// </summary>
	OccluderStatic = 2,
	/// <summary>
	/// Summary: Consider for static batching.<br />
	/// Summary: Combine the GameObject's Mesh with other eligible Meshes, to potentially reduce runtime rendering costs.<br />
	/// 3.5.0f5 to Max
	/// </summary>
	BatchingStatic = 4,
	/// <summary>
	/// Summary: Considered static for navigation.<br />
	/// Summary: Include the GameObject when precomputing navigation data.<br />
	/// Obsolete Message: 3.5.0f5 to 2022.2.0a16<br />
	/// null<br />
	/// Obsolete Message: 2022.2.0a16 to Max<br />
	/// Enum member StaticEditorFlags.NavigationStatic has been deprecated. The precise selection of the objects is now done using NavMeshBuilder.CollectSources() and NavMeshBuildMarkup.<br />
	/// 3.5.0f5 to Max
	/// </summary>
	NavigationStatic = 8,
	/// <summary>
	/// Summary: Considered static for occlusion.<br />
	/// Summary: Mark the GameObject as a Static Occludee in the occlusion culling system.<br />
	/// 3.5.0f5 to Max
	/// </summary>
	OccludeeStatic = 0x10,
	/// <summary>
	/// Summary: Auto-generate OffMeshLink.<br />
	/// Summary: Attempt to generate an Off-Mesh Link that starts from this GameObject when precomputing navigation data.<br />
	/// Obsolete Message: 3.5.0f5 to 2022.2.0a16<br />
	/// null<br />
	/// Obsolete Message: 2022.2.0a16 to Max<br />
	/// Enum member StaticEditorFlags.OffMeshLinkGeneration has been deprecated. You can now use NavMeshBuilder.CollectSources() and NavMeshBuildMarkup to nominate the objects that will generate Off-Mesh Links.<br />
	/// 3.5.0f5 to Max
	/// </summary>
	OffMeshLinkGeneration = 0x20,
	/// <summary>
	/// Summary: Consider static for reflection probe.<br />
	/// Summary: Include this GameObject when when precomputing data for Reflection Probes whose Type property is set to Baked.<br />
	/// 5.0.0f4 to Max
	/// </summary>
	ReflectionProbeStatic = 0x40
}
```
Obviously, I need to set `BatchingStatic` to true, but do any of the others need set also?

**Comment by Zbuffers** [comment]
Hi, 
Yes I think that for these, all static flags need to be set. 
Result should be m_StaticEditorFlags: 4294967295 ?

**Comment by ds5678** [comment]
Where does `4294967295` come from? The highest flag is `0x40`, ie 64.

**Comment by Zbuffers** [comment]
That's what unity gives when all flags are set:

extracted gameobject with all static flags set :

![staticFlags](https://user-images.githubusercontent.com/7527771/213890145-73da5d7c-181d-469c-a485-23e6e47d88c9.png)

--- !u!1 &1726541852
GameObject:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  serializedVersion: 6
  m_Component:
  - component: {fileID: 1726541855}
  - component: {fileID: 1726541854}
  - component: {fileID: 1726541853}
  m_Layer: 0
  m_Name: GameObject
  m_TagString: Untagged
  m_Icon: {fileID: 0}
  m_NavMeshLayer: 0
  m_StaticEditorFlags: 4294967295 <----------------------------------------------------------
  m_IsActive: 1

**Comment by ds5678** [comment]
If you unclick `Everything`, does it change to 127?

**Comment by Zbuffers** [comment]
I can't ... Unity sets the everything when I check all of them.
If I uncheck Contribute GI:
m_StaticEditorFlags: 126
![staticFlags](https://user-images.githubusercontent.com/7527771/213892252-07f53f10-1959-4cbf-8a14-cdca6504eba4.png)

**Comment by ds5678** [comment]
I understand. I'll make a note of that.
