### ISSUE TITLE
Assembly-CSharp-firstpass in Plugins

### ISSUE THREAD

**Issue by ds5678** [AssetRipper/AssetRipper#704]
The `Assembly-CSharp-firstpass` assembly needs to be decompiled to `Assets/Standard Assets/` to avoid being merged with `Assembly-CSharp`.

Reference: https://docs.unity3d.com/Manual/ScriptCompileOrderFolders.html

**Comment by Zbuffers** [comment]
Hi,

Better yet, place them in the Assets/Plugins/ folder.
Any code that is inside any project's Assets/plugin/ folder gets compiled into Assembly-CSharp-firstpass.
Only old Unity Standard Assets go in Assets/Standard Assets/
(usually UnityStandardAssets namespace)

my 2 cents ;)

**Comment by ds5678** [comment]
`Assets/Plugins/Assembly-CSharp-firstpass`

**Comment by ds5678** [comment]
Or maybe `Assets/Plugins/Scripts/`.

**Comment by ds5678** [comment]
Implemented in dafbed2d9777f8242286ab37b21d0f8b9cf54f17
