### ISSUE TITLE
[Bug]: exported cubemaps need Y flip

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#705]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

n/a all of them ;)

### Which Unity version did this occur on?

2020.3.35

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Hello again ;)

The complete export (all 6 sides) of cubemaps is a great feature ;)
One thing though:  each of the 6 sides of the cubemap image need to be flipped in the Y.
I checked with a few version of Unity (2018, 2019, 2020), and photoshop, to make sure it's consistent.
Once each side is flipped, the cubemap is good to go :)

Kind regards,
Zbuffer

**Comment by ds5678** [comment]
Did you encounter import issues with Cubemaps? Users have reported errors from Unity about it not being square.

**Comment by Zbuffers** [comment]
yes i have, but only because size was not power of 2 (width or height)
When importing cubemaps, unity wants 6 squares (power of 2 resolution) in the cubemap image.
So in these cases, I just resize the image in photoshop.
It's a warning though, not an error.

**Comment by Zbuffers** [comment]
Hello again, I just encountered an issue with the cubemaps. with Unity2018.4
indeed unity complains that the cubemaps are not power of two
easyfix:
nPOTScale: 0 in the cubemap metafile
and unity is happy. 
Strange thing is that there is no way i know of to set this field in the unity UI, once set to import type Cube.
Hope it can help ;)

**Comment by ds5678** [comment]
Thanks for the report!

**Comment by JohnCorby** [comment]
assetripper already uses nPOTScale: 0
instead, 1 is what makes unity happy. it's also what the default texture importer settings do so i assume its more correct
