### ISSUE TITLE
[Question]: Error Bundle compression '5' isn't supported

### ISSUE THREAD

**Issue by AKA-3939** [AssetRipper/AssetRipper#706]
### Question

When I try to extract assets from the game, it shows up this error. 
Bundle compression '5' isn't supported, and followed up with a long error msg.

But it AssetRipper is working before the game update the client. Now it just shows an error.

**Comment by AKA-3939** [comment]
Uploaded Log
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10496027/AssetRipper.log)

**Comment by ds5678** [comment]
Most likely a custom unity engine.
