### ISSUE TITLE
Ymal Shaders broken for game RecRoom (Unity 2020.3.33f1)

### ISSUE THREAD

**Issue by MadMincraftr** [AssetRipper/AssetRipper#712]
### Describe the issue

Ymal shaders are pink-glitched when exported to/from unity 2020.3.33f1 at least on the game RecRoom.

**Comment by ds5678** [comment]
Not AssetRipper's fault. Yaml export for shaders exports "as-is" and trusts that Unity can load them. There's nothing more that AssetRipper could do.
