### ISSUE TITLE
[Bug]: Terrain Splatmaps with alpha

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#723]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Any game...

### Which Unity version did this occur on?

2018.3,
although I tihnk it applies to all versions

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Hi, 
I just noticed that the terrains' splatmaps (SplatAlpha 0, SplatAlpha 1, etc...)  
have the default "Use alpha as transparency" set to true.

This leads to wrong texture/tiling on the terrain.
Unchecking "Use alpha as transparency" in the editor  fixes it.
So I think that when exporting the splatmap metafile, 
The 'alphaIsTransparency' property needs to be set to 0.

Have a good day ;)

### Relevant log output

n/a

**Comment by ds5678** [comment]
If I am thinking of what you're thinking, those are not supposed to be exported as images. They get embedded in the terrain file.

Relevant code is in the terrain texture processor and the yaml terrain exporter.

**Comment by ds5678** [comment]
@Zbuffers I require proof of what you're claiming. In my testing, splat map textures do not ever get exported as images. These 3 classes prevent that and export them as Yaml with the `TerrainData`.

- https://github.com/AssetRipper/AssetRipper/blob/dbeba151d544488c249b363dc0ff5649e1175741/Source/AssetRipper.Export.UnityProjects/Terrains/TerrainYamlExportCollection.cs
- https://github.com/AssetRipper/AssetRipper/blob/dbeba151d544488c249b363dc0ff5649e1175741/Source/AssetRipper.Export.UnityProjects/Terrains/TerrainYamlExporter.cs
- https://github.com/AssetRipper/AssetRipper/blob/dbeba151d544488c249b363dc0ff5649e1175741/Source/AssetRipper.Processing/TerrainTextureProcessor.cs

If proof is not provided, I'm going to have to close this.

**Comment by ds5678** [comment]
Closing due to the reasons listed above. Feel free to reopen if you think the issue persists.
