### ISSUE TITLE
[Bug]: AnimationClipConverter Read Error

### ISSUE THREAD

**Issue by Q4st** [AssetRipper/AssetRipper#733]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://www.google.com/amp/s/m.apkpure.com/garena-free-fire-android-il/com.dts.freefireth/amp

### Which Unity version did this occur on?

2018.4.11f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Cannot be negative: -1067515904 (Parameter 'count')
2.4.2 does not have this problem, it only appears in the new version 3.0 and above

[optionalab_avatar_04.zip](https://github.com/AssetRipper/AssetRipper/files/10720575/optionalab_avatar_04.zip)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10720571/AssetRipper.log)

**Comment by ds5678** [comment]
I don't know when it was fixed, but it currently works.
