### ISSUE TITLE
Unable to decompress crunched texture

### ISSUE THREAD

**Issue by Deschamps12** [AssetRipper/AssetRipper#735]
Are you on the latest version of AssetRipper?
Yes, I'm on version 0.3.0.6 

Which release are you using?
Windows x64

Which game did this occur on?
Ruined King: A league of legends story

Which Unity version did this occur on?
2019.4.26

Is the game Mono or IL2Cpp?
IL2Cpp

Describe the issue.
Export stops because of system.Exception: Unable to decompress crunched texture 

Relevant log output
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10728457/AssetRipper.log)

**Comment by DatTaiwanGuy** [comment]
how about checking the texture name from the export log and then edit the crunched texture to dxt5 by opening and editing it's bundle using uabea or assetbundleextractor to see if it will work?

**Comment by ds5678** [comment]
For the record, I make no guarantees on being able to rip files created by unofficial sources. The Unity format is proprietary and undocumented. These third party tools could be generating invalid files, especially since none of them are unit-tested.

**Comment by Deschamps12** [comment]
> It looks like the thing breaking everything is cubemaps from reflection probes. would there be a way to skip cubemap textures?

Asset Class: AssetRipper.SourceGenerated.Classes.ClassID_89.Cubemap_2019_4_9
Asset Type ID: 89
Name: ReflectionProbe-0
Image Format: DXT1Crunched
Image Dimensions (width x height): 16 x 16 pixels
Image Size: 2994 bytes

**Comment by C6OI** [comment]
I have the same issue

AssetRipper 0.3.0.6
Windows 10 x64
Unity 5.6.7
Mono
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10733185/AssetRipper.log)

```
Asset Class: AssetRipper.SourceGenerated.Classes.ClassID_89.Cubemap_5_5_0
Asset Type ID: 89
Name: ReflectionProbe-0
Image Format: DXT1Crunched
Image Dimensions (width x height): 512 x 512 pixels
Image Size: 1759470 bytes
```

**Comment by ItsAlphaNeon** [comment]
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10776682/AssetRipper.log)
Same issue here, I tested the same file on an earlier version of AssetRipper and it worked, however it errors and stops on the latest version

**Comment by DatTaiwanGuy** [comment]
only utinyripper works with compressed textures but it's outdated..
