### ISSUE TITLE
[Bug]: Problems with packages and components

### ISSUE THREAD

**Issue by Arurikku** [AssetRipper/AssetRipper#746]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Baldi's Basics ([itch.io link](https://basically-games.itch.io/baldis-basics))
Karlson ([itch.io link](https://danidev.itch.io/karlson))
Call of Unity ([SteamDB link](https://steamdb.info/app/1074630/))
Race ([SteamDB link](https://steamdb.info/app/768800/))

### Which Unity version did this occur on?

2018.2.19f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

When the project is exported, instead of using packages as normal, the packages are decompiled into scripts.

For example, **TextMeshPro** is decompiled as a script, which causes a lot of compile errors, some of which unfixable.
This is the case for every package, such as **Cinemachine**, **Newtonsoft.Json**, **Unity.Timeline**, and many many more.

Blindly deleting the code in the 'Scripts' folder and adding the necessary DLLs in the assets fixes all compiler issues, but all GameObjects who used the components now have a `Missing (Mono Script)`

When using `DLL Export Without Renaming` as a script export format, there are no more errors, but components are left with `Missing (Mono Script)` again.

This can be replicated easily simply by creating an empty scene with just a **TextMeshPro** component, building the game, then exporting it using **AssetRipper**
![image](https://user-images.githubusercontent.com/61802068/220864452-82d97f96-58d4-4ed9-b23b-4ce3081ed26b.png)

### Relevant log output

This probably has nothing to do with the error, but all of these DLLs are the ones causing the problems

![image](https://user-images.githubusercontent.com/61802068/220865492-67da1997-4ee6-4ef9-acea-dd4ee409b30b.png)

**Comment by ds5678** [comment]
> When using DLL Export Without Renaming as a script export format, there are no more errors, but components are left with Missing (Mono Script) again.

Normal. It's not intended for your use case.

> For example, TextMeshPro is decompiled as a script, which causes a lot of compile errors, some of which unfixable.
This is the case for every package, such as Cinemachine, Newtonsoft.Json, Unity.Timeline, and many many more.

Normal. Don't expect this to change anytime soon.

> Blindly deleting the code in the 'Scripts' folder and adding the necessary DLLs in the assets fixes all compiler issues, but all GameObjects who used the components now have a Missing (Mono Script)

Of course. That is how Unity works.

> This probably has nothing to do with the error, but all of these DLLs are the ones causing the problems

Unit test dll's have no impact and are not distributed with the game.

**Comment by Arurikku** [comment]
So is it possible to export a project that uses TextMeshPro or any other package on Unity 2018 (specifically 2018.2.19f1)?

**Comment by ds5678** [comment]
It is infeasible.
