### ISSUE TITLE
[Bug]: grayscale textures in unity

### ISSUE THREAD

**Issue by fajnygosciu1234** [AssetRipper/AssetRipper#747]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

2022,2.8f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

when i extracted a folder with assetbundles and then extracted them, the textures appear grayscale on unity, but show up with colors anywhere else

**Comment by ds5678** [comment]
I don't understand what you want.

**Comment by fajnygosciu1234** [comment]
so, i loaded every folder of an map archive, when i batch decompiled it and opened it in unity, it shows grayscale textures instead of the colored ones
link is here: https://archive.org/download/tro-maps-archive try to test it since i need to rebuild the maps for new unity and game use

**Comment by ds5678** [comment]
That is expected. The developer set the textures that way.

**Comment by ds5678** [comment]
I discussed the issue with someone in Discord. This was caused by a new TextureImporter field added in `2022.1.0a13`. I am currently implementing an improvement for this.
