### ISSUE TITLE
[Bug]: Long Title about a VRC Avatar

### ISSUE THREAD

**Issue by Atroxcity** [AssetRipper/AssetRipper#751]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Unity a VrChat Avatar

### Which Unity version did this occur on?

unity 2019.4.31f

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

So i fully extracted a vrca, but for some reason it keeps getting stuck on body mesh. I even tried it by deleting the mesh, but the prefab of the avatar was invisible. Even when i dragged it into the scene. Please if you guys know how to fix this. Please tell me.

### Relevant log output

![image](https://user-images.githubusercontent.com/126637314/222033467-7375a680-a0c8-4092-a64f-a0d48fabce35.png)
![image2](https://user-images.githubusercontent.com/126637314/222033475-2917a5ef-e6d0-43f4-a7af-e8897a1649a5.png)

**Comment by ds5678** [comment]
> Yes, I'm on the latest release of AssetRipper.

You are not.

**Comment by ds5678** [comment]
Also, I have doubts about the integrity of the source file. These read errors never happen on normal files.

**Comment by Atroxcity** [comment]
oh i'm sorry i thought i was, i use sars. i was told to ask you guys.

**Comment by Atroxcity** [comment]
also it was just a vrca. i can send it if you need it.

**Comment by ds5678** [comment]
I feel like this file was not made in Unity. All my instincts point towards it being created by third party software, such as a reuploader.

**Comment by Atroxcity** [comment]
ohh okay thank you!, sorry for wasting your time.
