### ISSUE TITLE
[Enhancement]: TMPro enhancement

### ISSUE THREAD

**Issue by oldsportsgit** [AssetRipper/AssetRipper#754]
### Describe the new feature or enhancement

so in assetripper if you decompile a game that uses textmeshpro stuff like the textmeshprougui.cs is used instead of unity's builtin textmeshpro i have found a solution to this and that is to change the "guid" if you change the guid for the decompiled textmeshprougui.cs to this m_Script: {fileID: 11500000, guid: f4688fdb7df04437aeb418b961361dc5, type: 3} as far as i know the guid doesn't change and it does work

**Comment by ds5678** [comment]
Duplicate of #746
