### ISSUE TITLE
[Bug]: (happens on IL2CPP and Mono) Scripts do not get fully exported

### ISSUE THREAD

**Issue by In4init3** [AssetRipper/AssetRipper#757]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

[Gorilla Tag](https://steamdb.info/app/1533390/)

### Which Unity version did this occur on?

2019.3.15

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

After exportation, I notice in the scripts that they do not have info attached, just voids and variables. Might be an issue in decompilation as I have also noticed this issue in UTiny.
![image](https://user-images.githubusercontent.com/82238521/223890540-78c70caf-1c44-44e1-b2c1-02b9b33587b3.png)
(sorry for the lazy use of dnspy)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10926712/AssetRipper.log)

**Comment by ds5678** [comment]
> happens on IL2CPP and Mono

It does not happen on Mono.

> I have also noticed this issue in UTiny.

uTiny's primitive decompiler only decompiled fields.
