### ISSUE TITLE
[Question]: How to fix transparent backgrounds not appearing correctly?

### ISSUE THREAD

**Issue by 95huskey** [AssetRipper/AssetRipper#762]
### Question

Asset Class: AssetRipper.SourceGenerated.Classes.ClassID_28.Texture2D_2017_3_0
Asset Type ID: 28
Name: icn_furniture_dj_table
Image Format: RGB24
Image Dimensions (width x height): 256 x 256 pixels
Image Size: 196608 bytes
![icn_furniture_dj_table](https://user-images.githubusercontent.com/23666361/225141946-31474f19-8d74-46e6-9aa6-e879b6f24908.png)

The other stuff from the game is fine it's just the furniture icons.

**Comment by ds5678** [comment]
They are actually like that.

**Comment by 95huskey** [comment]
Oh, that's weird, because they're not like that in the game.

**Comment by ds5678** [comment]
It's RGB24. It has no alpha in the game either.
