### ISSUE TITLE
[Question]: Where are scenes exported too?

### ISSUE THREAD

**Issue by cyberangel67** [AssetRipper/AssetRipper#765]
### Question

I ripped a game that I have ripped many times before, and this time I can not find where the scenes are exported to.

**Comment by ds5678** [comment]
That has not changed recently.

**Comment by HeresHavi** [comment]
Sometimes the scene folder is not directly exported to the root folder. Try a global search within the folder

**Comment by cyberangel67** [comment]
Is there a reason it is not saved in a folder called scenes?

**Comment by ds5678** [comment]
If the developer put the scenes elsewhere, they will be there instead.

**Comment by ds5678** [comment]
If you find that some AssetRipper change has caused a regression in behavior, feel free to reopen this issue.
