### ISSUE TITLE
[Enhancement]: a new option under the "Script export format"

### ISSUE THREAD

**Issue by oldsportsgit** [AssetRipper/AssetRipper#774]
### Describe the new feature or enhancement

So basically i would like to have a option for generating dummy scripts like how utinyripper did So that i don't have to fix compiler errors by myself and just start working on the decomp a little faster.

**Comment by ds5678** [comment]
Never happening. We made a design decision a long time ago that method stubbing is better than method stripping. Use Script Content Level 1.
