### ISSUE TITLE
[Bug]: Mismatched binary content errors started to appear on the latest alpha version

### ISSUE THREAD

**Issue by githubexplorer2342** [AssetRipper/AssetRipper#775]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://steamdb.info/app/962400/

### Which Unity version did this occur on?

2019.2.11

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Lately, mismatched binary content errors started to appear that werent there in the release version of AssetRipper or in the earlier alphas.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11064833/AssetRipper.log)

**Comment by ds5678** [comment]
I want a log from the latest release, too.

**Comment by githubexplorer2342** [comment]
> I want a log from the latest release, too.

Here it is: 
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11066143/AssetRipper.log)

The release does not have this error, which i find weird.

**Comment by ds5678** [comment]
I suspect a certain commit to have caused this discrepancy and have two builds for you to try.

Before: https://github.com/AssetRipper/AssetRipper/actions/runs/4465742015

After: https://github.com/AssetRipper/AssetRipper/actions/runs/4466061643

**Comment by githubexplorer2342** [comment]
Yeah, you were right, that commit made the error appear.

**Comment by archanox** [comment]
I _think_ I may have the same issue,

```
Import : Unable to read MonoBehaviour_4_3_0, because script UIPrefabOptionsScreen layout mismatched binary content (read 48 bytes, expected 56 bytes).
Import : Unable to read MonoBehaviour_4_3_0, because script UISprite layout mismatched binary content (EndOfStreamException).
```

**Comment by ds5678** [comment]
@archanox possible but unlikely. This problem is only observable for a narrow range of commits. You most likely just have normal read errors.

**Comment by ds5678** [comment]
Thank you for reporting this!
