### ISSUE TITLE
[Bug]: Key not found: GUID : 21300000

### ISSUE THREAD

**Issue by Q4st** [AssetRipper/AssetRipper#776]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://play.google.com/store/apps/details?id=com.bandainamcoent.gtekketsug

### Which Unity version did this occur on?

2021.3.9f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

After the game is decrypted, using assetripper to load all resources will report an error:[Bug]: System.Collections.Generic.KeyNotFoundException: Key not found: GUID : 21300000

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11068712/AssetRipper.log)

**Comment by ds5678** [comment]
What happened?

**Comment by Q4st** [comment]
It is because of spine2d, I deleted four resources through debugging, it has no problem

**Comment by ds5678** [comment]
@Q4st can you try again on the latest commit? It should still error, but I implemented a ToString override on GUID, so it may give us slightly better information.

**Comment by Q4st** [comment]
@ds5678 
When I try again, I get two errors, including the GUID issue raised last time, both errors crash AssetRipper, exiting！

[Error1.txt](https://github.com/AssetRipper/AssetRipper/files/11098912/Error1.txt)


The GUID error problem is that when all files are loaded, an error will be reported. If these files are loaded separately, everything is normal
[Error1File.zip](https://github.com/AssetRipper/AssetRipper/files/11098813/Error1File.zip)

The second error is that when there is an error in the file itself, AssetRipper will crash instead of an error message！

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11098878/AssetRipper.log)
[Error2File.zip](https://github.com/AssetRipper/AssetRipper/files/11098882/Error2File.zip)

**Comment by ds5678** [comment]
> AssetRipper will crash instead of an error message!

There is no reason to shout.

> System.MissingFieldException: Field not found: 'Avalonia.Controls.Window.WindowStartupLocationProperty'.

[This is an upstream MessageBox.Avalonia bug.](https://github.com/AvaloniaCommunity/MessageBox.Avalonia/issues/129) I may have to downgrade Avalonia if a release is not posted soon.

> [Error] : System.Exception: Incorrect number of bytes written. -1 instead of 131072

Is this behavior different on any other versions of AssetRipper? Normally, I tell users this is caused by file encryption.

> [Error] : System.Collections.Generic.KeyNotFoundException: Key not found: 41e7cf2354a3046709e8e4d4b9fab636 : 21300000

This is what I was asking to see. I knew this error would still appear, but now it shows the guid value. I needed to confirm that the guid was not the Unity missing guid.

**Comment by ds5678** [comment]
I resolved the Avalonia issue.
