### ISSUE TITLE
[Enhancement]: Hope to add the ability to repackage assets

### ISSUE THREAD

**Issue by nijinekoyo** [AssetRipper/AssetRipper#784]
### Describe the new feature or enhancement

Hope to add the ability to repackage assets

**Comment by ds5678** [comment]
This is a major request and is unlikely to happen unless I'm given a strong financial incentive.

**Comment by nijinekoyo** [comment]
Too bad I don't have that much money to support you

**Comment by nijinekoyo** [comment]
that's too regretful
