### ISSUE TITLE
[Other]: Annoying, Hard to see text becuase of frost glass window (windows 11)

### ISSUE THREAD

**Issue by MadMincraftr** [AssetRipper/AssetRipper#797]
### Describe the issue

Depending on the window behind asset rippper, the text is annoying to read at times.
![image](https://user-images.githubusercontent.com/37884292/231879892-48601b39-ed0e-4581-a44e-3d0ac8bfb8b5.png)

**Comment by C0mputery** [comment]
If you would like to change this for yourself, fork asset ripper and change line 11 and line 13 in the Background.axaml file.

**Comment by ds5678** [comment]
That's weird. It looks completely different on Windows 10. Avalonia is supposed to be pixel perfect, but apparently it's not.

In any case, I've been working on a new GUI using imgui instead of Avalonia.

**Comment by jafernv** [comment]
> That's weird. It looks completely different on Windows 10. Avalonia is supposed to be pixel perfect, but apparently it's not.
> 
> In any case, I've been working on a new GUI using imgui instead of Avalonia.

I have the same problem in windows 10. The last version of windows 10

**Comment by ds5678** [comment]
I'll double check sometime this weekend.

**Comment by DarkEyeDragon** [comment]
Can confirm i also have this issue.
![image](https://user-images.githubusercontent.com/6131099/232245770-104ab84a-9c0a-4d21-a18a-a5450f65646a.png)

Maybe something with default windows mode being light mode?

**Comment by MadMincraftr** [comment]
> 
Nah I'm on dark mode lol

**Comment by ds5678** [comment]
> I'll double check sometime this weekend.

Still looks completely normal on my end.

**Comment by DarkEyeDragon** [comment]
Tried on my work computer W11 and on my home machine W10. Both have this issue.

**Comment by codengine** [comment]
Happens to me, too. Windows 10 22H2 with Dark Mode.

**Comment by Prosopho** [comment]
Seems to happen on linux mint too

**Comment by ds5678** [comment]
For #801, I discovered that preview 6 of Avalonia 11 was causing the issue. It is possible that a similar problem is occurring here. However, I cannot bump to preview 7 yet because I'm waiting on a MessageBox.Avalonia release.

**Comment by ds5678** [comment]
Check out the latest commit and see if the issue still occurs.

**Comment by Prosopho** [comment]
> Check out the latest commit and see if the issue still occurs.

Still happens on light theme at least.

**Comment by UlyssesZh** [comment]
Confirms on Linux version on light theme.

**Comment by SwingCosmic** [comment]
Same problem on win10 22H2 light mode (custom primary color)

**Comment by ds5678** [comment]
I am working on a new UI. Until it's done, either switch to dark mode or be patient.
