### ISSUE TITLE
[Bug]: Language menu can't show text

### ISSUE THREAD

**Issue by czxinc** [AssetRipper/AssetRipper#801]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

none

### Which Unity version did this occur on?

none

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Language menu won't show text correctly.
Bug on AssetRipper Version: 0.3.1.0.

![1](https://user-images.githubusercontent.com/25028929/233557721-54c6aeee-5e04-4ddb-a9e6-19d1edf669b4.PNG)

**Comment by ds5678** [comment]
I discovered that this is caused by an Avalonia bug and has been resolved in preview 7. However, I'm waiting on a release from MessageBox.Avalonia.

**Comment by MARK2580** [comment]
By the way, I have the same problem on Win10, I hope you fix it (although the menu itself works)

**Comment by ds5678** [comment]
This should be fixed automatically when I bump the Avalonia version.
