### ISSUE TITLE
[Bug]: Animation is "Shakey"

### ISSUE THREAD

**Issue by JohnCorby** [AssetRipper/AssetRipper#815]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Outer Wilds

### Which Unity version did this occur on?

2019.4.39f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Maybe due to floating point errors? idk

https://user-images.githubusercontent.com/26337121/235290753-9fa9a09b-2840-4439-8c47-ad2f9404939a.mp4

**Comment by ds5678** [comment]
Animation recovery is very complex, and I wrote almost none of it. I would be surprised if bugs didn't exist.

**Comment by ds5678** [comment]
#1210 made some changes which might have resolved your issue. Can you re-rip your project with the latest continuous integration build and verify that the issue is indeed resolved?

**Comment by ds5678** [comment]
Closed because of inactivity. Feel free to reopen the issue if your problem persists.
