### ISSUE TITLE
[Enhancement]: Decompilation w/ only Public Fields

### ISSUE THREAD

**Issue by TheStickyFox** [AssetRipper/AssetRipper#823]
### Describe the new feature or enhancement

Before this, I used to use uTinyRipper. It had a feature where it didn't completely decompile a class, but only left in the public fields so that Unity could recognize the parameters that script had. This would really help with datamining certain games where some kind of "answer" can just be found with the MonoBehaviour. Plus avoiding compiler errors which make the script refuse to even load

**Comment by ds5678** [comment]
Not happening. That decompiler was unmaintainable and had lots of bugs.
