### ISSUE TITLE
[Bug]: Extracting game read violation at adress 000000 when loading the main scene

### ISSUE THREAD

**Issue by hl2jeep** [AssetRipper/AssetRipper#825]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://www.indiedb.com/games/beware/downloads/beware-demo-v001

### Which Unity version did this occur on?

5.4.4p4

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

after extracting the game using asset ripper i had this issue with the read violation, i removed the scripts and it was able to load the project, however it had the same error afterwards when trying to load the main scene, i have not been able to fix this.

### Relevant log output

i do not have a log at the moment, im not at my main pc.

**Comment by ds5678** [comment]
Log?

**Comment by hl2jeep** [comment]
> Log?

**Comment by hl2jeep** [comment]
> Log?

I'm not at my pc right now so I'll try to get a log later, however the long only really has a hex dump, no other useful info

**Comment by ds5678** [comment]
Might be a duplicate of #811

**Comment by hl2jeep** [comment]
I

> Might be a duplicate of #811

Due to me having exams ATM, I probably will be unable to give a log until September (I won't have my pc over the summer as I'm abroad) so I will close this issue for now
