### ISSUE TITLE
[Other]: Increase version on alpha builds

### ISSUE THREAD

**Issue by DarkEyeDragon** [AssetRipper/AssetRipper#836]
### Describe the issue

Currently `alpha` builds have the exact same versioning as releases making them indestinguisable from each other. As a result I thought i had the exact same version required for some features added in an alpha release. However came to the conclusion that the release was not the same as the alpha despite having the exact same numbering.

Use the build number/commit hash in the versioning to avoid such confusion in the future.

**Comment by ds5678** [comment]
There's a compile time in the log.
