### ISSUE TITLE
[Bug]: Stubbed property paths are exported in several animation clips in Bug Fables

### ISSUE THREAD

**Issue by aldelaro5** [AssetRipper/AssetRipper#853]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Linux x64

### Which game did this occur on?

Bug Fables: The Everlasting Sapling

Steamdb: https://steamdb.info/app/1082710/

### Which Unity version did this occur on?

2018.4.12f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

When I do an export of the game, all animations clips from the game except those used in a specific controller do not have correct property paths.

Specifically, if I check in the Assets/Ressources/animationcontrollers/bee directory after export, every .anim in there messes with the m_Sprite of the Rotater/Sprite path. This is expected and most clips of most controllers under the animationcontrollers are expected to do this given what I know of the game's infrastructure.

However, if I check any other .anim files under that animationcontrollers folder, none of them features this path, but I am seeing the string "path_904830837" which is notably the same number that appears in ALL the files where this path applies including the good ones.

Here's an example of a bad one:
[100.txt](https://github.com/AssetRipper/AssetRipper/files/11715894/100.txt)

And here's a good one:
[100.txt](https://github.com/AssetRipper/AssetRipper/files/11715895/100.txt)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11715897/AssetRipper.log)

**Comment by o5zereth** [comment]
yay we resolved #856

**Comment by AnalogFeelings** [comment]
Something similar happens with Night In The Woods, but it outputs "Typetree_" and then a number.
