### ISSUE TITLE
[Bug]: Control Characters in Yaml Strings

### ISSUE THREAD

**Issue by Minileandro** [AssetRipper/AssetRipper#862]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Club Penguin Island (1.13.0)

### Which Unity version did this occur on?

2017.4.12f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Error on console: Unable to parse file Assets/Resources/accountsystemprefabs/CreateAccountPrebab.prefab: [Control characters are not allowed] at line 3188

![image (1)](https://github.com/AssetRipper/AssetRipper/assets/53369145/2408581c-1840-4235-ab63-7c524176051f)

![image](https://github.com/AssetRipper/AssetRipper/assets/53369145/11d01498-ae68-474f-bcf8-99fa684f02aa)

**Comment by ds5678** [comment]
A few notes on this from the Discord discussion:

0x03 is the [end of text character](https://en.wikipedia.org/wiki/End-of-Text_character). It was the final character in the string (of length 2) for a custom MonoBehaviour field.

Control characters might need emitted with a different scalar node type to avoid parsing errors in Unity.
