### ISSUE TITLE
[Bug]: scripts have compiler errors but have nothing wrong in visual studio

### ISSUE THREAD

**Issue by LowPolyBeans** [AssetRipper/AssetRipper#869]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Nano force and most  games. i downloaded an apk through oculusdb and dragged it into asset ripper.

### Which Unity version did this occur on?

2021.3.25f1. the  version asset ripper said to use.

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

unity has errors in the script but opening it in visual studio shows no errors. on scripts attached to objects it shows "the associated script cannot be loaded. Please fix any compiler errors and assaign a valid script." some scripts are missing

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11839375/AssetRipper.log)

**Comment by ds5678** [comment]
About the script errors, they're normal and I can't do much about them.

About Visual Studio, that's unrelated to AssetRipper. Google searches would be more appropriate. There's a VS Unity package. Install the latest version.

**Comment by LowPolyBeans** [comment]
> About the script errors, they're normal and I can't do much about them.
> 
> About Visual Studio, that's unrelated to AssetRipper. Google searches would be more appropriate. There's a VS Unity package. Install the latest version.

i think you misunderstood. unity shows errors that dont belong. the code has no issues.

**Comment by ds5678** [comment]
That doesn't sound like an AssetRipper problem.
