### ISSUE TITLE
[Enhancement]: References when exporting Mesh assets as OBJ

### ISSUE THREAD

**Issue by ds5678** [AssetRipper/AssetRipper#87]
### Describe the new feature or enhancement

Currently, exporting mesh assets in the OBJ format causes broken references in mesh filters and any other component that might reference them. This is because the reference needs to have the file id for the exported OBJ file instead of the generic file id.

**Comment by ds5678** [comment]
Not planned for the foreseeable future. This may be revisited at a later date.

**Comment by ModischFabrications** [comment]
Was about to create an issue to add something similar to "export mesh". I would like to export meshes directly, without an intermediate step of creating, adding, opening, exporting and then deleting a unity project. This is somewhat related to #731

**Comment by ds5678** [comment]
> I would like to export meshes directly

Export as GLB
