### ISSUE TITLE
[Question]: Animmations from Pokémon HOME

### ISSUE THREAD

**Issue by Escope12** [AssetRipper/AssetRipper#870]
### Question

Hi. Is it possible to extract animations from Pokémon HOME with this? I tried to do it with Asset Studio and they were buggy.

**Comment by ds5678** [comment]
I do not have Pokemon Home.

**Comment by Escope12** [comment]
Then can I send some samples from Pokémon HOME?

**Comment by ds5678** [comment]
> Is it possible to extract animations from Pokémon HOME with this?

This is a silly question because it could be answered by you using the software.

**Comment by Escope12** [comment]
I did use it to extract them but it crashed when I did.

**Comment by ds5678** [comment]
> I did use it to extract them but it crashed when I did.

Why didn't you lead with that?

Please be sure you have uploaded your `AssetRipper.log` file. It is in the same folder as the exe file.

**Comment by Escope12** [comment]
I forgot to mention that. Gonna upload it now.

**Comment by ds5678** [comment]
Log?

**Comment by Escope12** [comment]
Hold on. Gonna get it.
