### ISSUE TITLE
[Bug]:  Request for Export Speed Improvement

### ISSUE THREAD

**Issue by AmongUsDev** [AssetRipper/AssetRipper#877]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Among us you can find it on steam

### Which Unity version did this occur on?

2020.3.22f1

(i have in my pc unity 2021 LTS)

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

hey i open Assetriper.exe then i choose Among us directory i take too long to export i start at 12:40 am to right now 

Please fix this issue i cant wait what i need to do right now ???

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11898308/AssetRipper.log)

**Comment by AmongUsDev** [comment]
@ds5678  what i need to do i closed now

**Comment by ds5678** [comment]
From your log, I can't identify anything causing a slowdown. If you gift me the game, I'll do a performance profile. My friend code is 440277283.

**Comment by AmongUsDev** [comment]
what is your discord name

**Comment by ds5678** [comment]
My discord name is also ds5678

**Comment by ds5678** [comment]
Why does Discord matter?

**Comment by AmongUsDev** [comment]
ok i will check

**Comment by AmongUsDev** [comment]
> Why does Discord matter?

to send the account steam (secret)

**Comment by ds5678** [comment]
I'm not going to log into your account. You can gift the game. It's only $5. Once again, my steam friend code is 440277283.

**Comment by AmongUsDev** [comment]
join discord and accept my invite
