### ISSUE TITLE
[Bug]: Unity UI turns black after importing specific shaders

### ISSUE THREAD

**Issue by Virjoinga** [AssetRipper/AssetRipper#888]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

GEARS & GUTS (happens on every game I've tried)

### Which Unity version did this occur on?

2019.4.40f1 (and multiple other versions)

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

This has only started happening recently, not sure when it started but these shaders only appeared on export on 0.3.2.0 and newer (tried 0.3.1.0 but this game causes an error on that version).
Specific shaders cause graphical issues in Unity. In GEARS & GUTS these shaders cause the issues:
[ProblematicShaders.zip](https://github.com/AssetRipper/AssetRipper/files/11947835/ProblematicShaders.zip)
The first shader turns the viewport dark:
![First](https://github.com/AssetRipper/AssetRipper/assets/45245475/6747818f-13bf-47c3-ba0e-68ce8ca1ec7f)
The second shader turns most UI black:
![Second](https://github.com/AssetRipper/AssetRipper/assets/45245475/a0cadcae-f894-43ff-8035-6a034405ac93)
The third shader turns icons black:
![Third](https://github.com/AssetRipper/AssetRipper/assets/45245475/df909786-bfbd-453b-abc4-39143495ba41)
The fourth shader turns the text black:
![Fourth](https://github.com/AssetRipper/AssetRipper/assets/45245475/e790426d-d5cd-4a30-99f6-69f106a50c44)
With all these shaders together, Unity is unusable:
![Fifth](https://github.com/AssetRipper/AssetRipper/assets/45245475/9508ba7f-995b-4387-a31b-a450a47fff1d)

### Relevant log output

0.3.2.1 Alpha (9224f06):
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11947917/AssetRipper.log)
0.3.0.4 Release:
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11948062/AssetRipper.log)

**Comment by ds5678** [comment]
> General : IgnoreEngineAssets: True

This is why. You're telling AssetRipper not to redirect these shaders to their proper references.

**Comment by Virjoinga** [comment]
> proper

Ah okay thanks for the heads-up. The naming is a bit misleading though which is why I made the mistake.
