### ISSUE TITLE
[Bug]: The IL2cpp with ios will not be exported

### ISSUE THREAD

**Issue by 78yh87** [AssetRipper/AssetRipper#897]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

[frame&managed.zip](https://github.com/AssetRipper/AssetRipper/files/11974703/frame.managed.zip)
the framework looks like type of .so file or gameassembly packaged with il2cpp
 it can be extracted succeed by il2dummper 
but the script will not exported at all when export
the game is Dacingline ios version

the full game
https://www.mediafire.com/file/vah1cb8n1yailna/C2B2087B-7773-447B-809A-1FE9B87DA3EC.zip/file

### Which Unity version did this occur on?

<img width="947" alt="AssetRipper_onI1PyUsGU" src="https://github.com/AssetRipper/AssetRipper/assets/136809362/077fb718-a0b0-40f2-9f50-fcca90f54f7f">

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

with assetripper the script will not be exported at all 
i just use assetripper to rip this but when all done 
the script not exported 

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11974815/AssetRipper.log)

**Comment by ds5678** [comment]
Probably a Cpp2IL problem. Have you tried using it directly?

**Comment by ds5678** [comment]
> Import : Mixed game structure has been found at C:\Users\al208\Desktop\爱思导出文件\C2B2087B-7773-447B-809A-1FE9B87DA3EC\DancingLine.app

Your files are not recognized as having an iOS file structure.

**Comment by 78yh87** [comment]
是的，我直接用il2dummper提取它，它有效这个游戏从ios平台导出
除了il2cpp脚本的打包方式外，没有区别
Its binary file is named after unityframework, which is different from the il2 naming (or packaging?) method of the Android platform and the Windows platform. Assetripper can recognize and export the il2 scripts of the Windows and Android platforms, but it does not work on this. I use il2dummper it can correctly extract the script

**Comment by ds5678** [comment]
I don't speak Mandarin.

**Comment by ds5678** [comment]
Cpp2IL and Il2CppDumper are not the same thing.

**Comment by 78yh87** [comment]
i mean this game ‘s script packaged by Cpp2IL and it can be extract with Il2CppDumper 、but assetripper can't seem to recognize this game‘s Cpp2iL packaging method

**Comment by ds5678** [comment]
https://github.com/SamboyCoding/Cpp2IL

**Comment by 78yh87** [comment]
不支持，哎😂

**Comment by 78yh87** [comment]
那是要把问题关了？
