### ISSUE TITLE
[Bug]: Scene exports (file name mapping) appear to be incorrect

### ISSUE THREAD

**Issue by dommrogers** [AssetRipper/AssetRipper#908]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

The Long Dark

### Which Unity version did this occur on?

2021.3.16f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Scene exports appear to be wrong based on their name.

Using AssetRipper artifact from https://github.com/AssetRipper/AssetRipper/actions/runs/5524136916 but also had this on the previous release.

e.g. WhalingStationRegion

WhalingStationRegion_DARKWALKER - Appears to be the base WhalingStationRegion scene
WhalingStationRegion_DEADMANWALKING - Appears to be Darkwalker (given some of the gameobjects in the scene)
WhalingStationRegion_SANDBOX - Appears to be DEADMAN (has a grave gameobject in scene)
WhalingStationRegion - Appears to be the additional SANDBOX scene 
WhalingStationRegion_DLC01 - seems OK

Same with LakeRegion but the mapping issue is inconsitant..

LakeRegion - is actually LakeRegion
LakeRegion_DARKWALKER - is _SANDBOX
LakeRegion_DEADMANWALKING - is _DARKWALKER
LakeRegion_SANDBOX - is _HUNTEDPART2
LakeRegion_HUNTEDPART2 - is _DARKWALKER ?
LakeRegion_DLC01 - is ok

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12050839/AssetRipper.log)

**Comment by ds5678** [comment]
If you would like to investigate this, the relevant code is in `Source/AssetRipper.Processing/Scenes`

**Comment by dommrogers** [comment]
Will do 👍

**Comment by dommrogers** [comment]
From the testing I've managed to do it seems to be a problem when a bundle file contains multiple scenes and more specifically ones where the assets order don't match...

`f3cae45c7277838a1942a9dea7e22b2c.bundle` (not sure why the bundle name != filename...)
![image](https://github.com/AssetRipper/AssetRipper/assets/707295/c9ae6fd7-de0a-414b-bed7-d737287d28a9)


Logged at line https://github.com/AssetRipper/AssetRipper/blob/f34cdfb3cf6895bc150d97d7f05acd99643ce812/Source/AssetRipper.Export.UnityProjects/Project/ProjectAssetContainer.cs#L35C51-L35C51
```
{scene.Name}|{scene.FileName}|{scene.GUID}|{scene.Scene.Name}|{scene.Scene.Path}|{scene.Scene.GUID}
WhalingStationRegion|cab-b2d95fadbf63b35d09d85b5d2ceea30a|2b2d03ccb4bf6584c8f951a3bfb68f10|WhalingStationRegion|Assets/Scenes/_Zones/WhalingStationRegion/WhalingStationRegion|2b2d03ccb4bf6584c8f951a3bfb68f10
WhalingStationRegion_DARKWALKER|cab-cb84eac07aa40afa2e289675341d0d47|325feb238742d6f40b5218d08986b26c|WhalingStationRegion_DARKWALKER|Assets/Scenes/_Zones/WhalingStationRegion/WhalingStationRegion_DARKWALKER|325feb238742d6f40b5218d08986b26c
WhalingStationRegion_DEADMANWALKING|cab-e1e903a7c52db7296a810b689738fb67|7b15abc03e1a2c6489a31565786fb5cc|WhalingStationRegion_DEADMANWALKING|Assets/Scenes/_Zones/WhalingStationRegion/WhalingStationRegion_DEADMANWALKING|7b15abc03e1a2c6489a31565786fb5cc
WhalingStationRegion_SANDBOX|cab-e78d7093c3ce52e60ec7bd23678ac7b0|e3536735529091448a93731f331c9729|WhalingStationRegion_SANDBOX|Assets/Scenes/_Zones/WhalingStationRegion/WhalingStationRegion_SANDBOX|e3536735529091448a93731f331c9729
```

Incorrect cab-* names for the scenes match with the incorrect scenes exports as mentioned above..

Hope this maybe helps shed some light on the issue..

**Comment by ds5678** [comment]
From my perspective, it looks like `IAssetBundle.SceneHashes_C142` has the actual correct order, whereas `IAssetBundle.Container_C142` (what we're currently using) is just an alphabetized list.

**Comment by dommrogers** [comment]
Changing it to use SceneHashes_C142 certainly fixes the export

`foreach (AccessPairBase<Utf8String, Utf8String> pair in assetBundleAsset.SceneHashes_C142)`

Will this be the case for other unity games/versions is the question.

**Comment by ds5678** [comment]
I did a quick investigation on my end.

For my created bundle, the `SceneHashes` dictionary is empty. [scene_bundle.zip](https://github.com/AssetRipper/AssetRipper/files/12061357/scene_bundle.zip)

I think this is the best way to go about solving the issue:
```cs
if (assetBundle.Has_SceneHashes_C142() && assetBundle.SceneHashes_C142.Count == assetBundle.Container_C142.Count)
{
    //Use SceneHashes
}
else
{
    //Use Container
}
```
