### ISSUE TITLE
[Bug]: System.FormatException: Invalid or corrupt metadata (magic number check failed)

### ISSUE THREAD

**Issue by LRobinson18** [AssetRipper/AssetRipper#913]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

One Punch Man: World

### Which Unity version did this occur on?

2019.4.40a0

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Trying to rip all assets from One Punch Man: World mobile game, crashes with error stated in log

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12100817/AssetRipper.log)

**Comment by ds5678** [comment]
Probably a custom Unity engine.
