### ISSUE TITLE
[Bug]: Scene names and original folder name dont get recovered properly anymore in latest Alpha

### ISSUE THREAD

**Issue by githubexplorer2342** [AssetRipper/AssetRipper#914]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

not applicable

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

i decided to try out commit d784083 and noticed that the scene names and folder name dont get recovered anymore.

This is what gets exported now:
![image](https://github.com/AssetRipper/AssetRipper/assets/104936164/62f8dbec-5139-4baa-9113-ba9fe494d43e)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12114564/AssetRipper.log)

**Comment by ds5678** [comment]
I appreciate the speedy report. I took a look at my code changes and accidentally used a less than character instead of greater than. I'll get a fix out when I return to my computer.

**Comment by ds5678** [comment]
Fixed in 9e4c64e60b1e8c0cc5e42ee646ff1ad2f6d59141
