### ISSUE TITLE
[Bug]: Switching to the Unknown scripting backend

### ISSUE THREAD

**Issue by ProbiusPrime** [AssetRipper/AssetRipper#915]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Eternal Return, 
DB link : https://steamdb.info/app/1049590/

### Which Unity version did this occur on?

Unity2022.3.3f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

![console](https://github.com/AssetRipper/AssetRipper/assets/89365323/0809a3c2-1293-4e11-8488-70f492911b8f)

captured console

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12134499/AssetRipper.log)

**Comment by ds5678** [comment]
That's not an AssetRipper bug. It's a Cpp2IL bug. You should report the problem there.

**Comment by ds5678** [comment]
https://github.com/SamboyCoding/Cpp2IL

**Comment by ProbiusPrime** [comment]
So there's no other ways?
i tried to contact SamboyCoding/Cpp2IL, but he has not updated it since 2022/09.

**Comment by ProbiusPrime** [comment]
and I founded GameAssembly. that wasn't mono. i'm sorry

**Comment by ds5678** [comment]
> So there's no other ways?

AssetRipper uses Cpp2IL. If it gets fixed there, it becomes fixed here.

> i tried to contact SamboyCoding/Cpp2IL, but he has not updated it since 2022/09.

I looked on the Cpp2IL repository and didn't see any issue posted from you.

> I founded GameAssembly. that wasn't mono. i'm sorry

No worries. I knew it wasn't Mono.

**Comment by ProbiusPrime** [comment]
I looked on the Cpp2IL repository and didn't see any issue posted from you.
→ To be exact, I stopped writing because I couldn't find the producer's response in other issues... But I just didn't find it. I'll say him later, Because I'm not good at English, so I'm relying on a translator.

Anyway, in the end, there's no solution but to wait.
I'm sorry to bother you.

**Comment by ds5678** [comment]
I know Sam personally. He always looks at posted issues, even if he doesn't respond. In addition, many of the open issues are from me, and there was no reason for him to respond to those ones.

**Comment by ProbiusPrime** [comment]
Still doesn't work...
I expected it after update, but the results are the same.

sad

**Comment by ds5678** [comment]
The Cpp2IL issue is still open though.
