### ISSUE TITLE
Preview Decompiled Scripts

### ISSUE THREAD

**Issue by ds5678** [AssetRipper/AssetRipper#929]
The UI could offer a preview of the decompiled script.

**Comment by Zbuffers** [comment]
Hi, may I add my 2 cents on this ?
I think an option to choose which Assemblies we want decompiled or not would be a SUPER GREAT feature.
for example, I never want rewired dlls to be decompiled, but I want some unity assemblies to be decompiled (textMeshPro or URP assemblies for example, so I can replace scripts easily).

**Comment by ds5678** [comment]
Z, that's completely unrelated. This issue is just about showing the text decompilation of a single MonoScript in the UI, similar to how textures can be viewed in the UI.
