### ISSUE TITLE
Mesh Preview

### ISSUE THREAD

**Issue by ds5678** [AssetRipper/AssetRipper#930]
The UI could show a 3D preview for mesh assets.

**Comment by MehadND** [comment]
Hey @ds5678, I would like to work on this. But I'm having trouble finding the code related to GUI 😭. Would be great if you could point to me somehow where it is and I can have a go at it?

**Comment by ds5678** [comment]
AssetRipper.GUI.Web

**Comment by ds5678** [comment]
@MehadND How's it going?

**Comment by MehadND** [comment]
Hey @ds5678, I am kind off having trouble understanding how the GUI bit works in this project, as I have never really worked with UI in C# or .NET. And also I never worked on something this big so If its okay I would like to take a bit more time to understand and then contribute to it?

Any resources or tips would be appreciated.

**Comment by ds5678** [comment]
AssetRipper deviates from normal .NET UI development and aligns more with Web UI development.

I think BabylonJS is likely the best mesh rendering option for AssetRipper, but I haven't looked into the implementation details.

**Comment by MehadND** [comment]
Great I will look into that. Thanks
