### ISSUE TITLE
[Bug]: Texture error in latest alpha

### ISSUE THREAD

**Issue by githubexplorer2342** [AssetRipper/AssetRipper#940]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://steamdb.info/app/962400/

### Which Unity version did this occur on?

2021.3.11f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

When i try to export game on latest commit, i get this error. It worked before the latest commit happened. (commit a7acd4a)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12164423/AssetRipper.log)

**Comment by ds5678** [comment]
You're awesome. I'll get it fixed.
