### ISSUE TITLE
AnimationClip paths and attributes are random numbers

### ISSUE THREAD

**Issue by Crambone** [AssetRipper/AssetRipper#954]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Naruto Shippuden: Ultimate Ninja Blazing

### Which Unity version did this occur on?

2018.4.14f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

I exported cab files from the cache folder of the game data, and the animationClips have random paths and scripts, such as "attribute: script_891883416", and "path: path_3041412214". They are random on full export and individual files too, though the guids seem to be valid on full export. There were only scale curves and float curves, but that might be because the game used Sprite Studio for animations. I'm not sure, I'm also quite new for github and decompiling, so sorry if I messed up something.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12185535/AssetRipper.log)

**Comment by ds5678** [comment]
They are not random. They are crc32 hashes of the original string, which AssetRipper could not reverse.

**Comment by ds5678** [comment]
That is a complicated question. There are 3 situations:
* The original string is impossible for AssetRipper to determine.
* AssetRipper makes an educated guess about what the original string was. 
* AssetRipper could make an educated guess if it was better.

**Comment by Crambone** [comment]
So do I just give up? Or any other suggestions, like a different software?

**Comment by ds5678** [comment]
AssetRipper is one of a kind. If you're not a programmer, the only thing you can do is be patient.

**Comment by Zbuffers** [comment]
Hi,

Remember this is free....... and most probably the best of its kind (even compared to Paid and expensive software)
I have tested all of the existing similar software (paid, and free), and they ALL have this issue.....
That said, I have managed to make up  stuff to resolve these issues. not simple and cumbersome....

This what I do to resolve these animation issues:

1.0 Identify the culprits paths using a text editor (notepad++):
  - search for : ''path: path_'
1.1 Find the associated animator (if any) using those animations, I STRONGLY recommend using 'Asset Usage Finder' (available in the asset store), or search for the animation guid in animator files...
1.2 . Find the gameobject (scene or prefab) using that animator (or animation).
1.3 Using a custom UnityEditor Script, I print that gameObject hierarchy as a list of full name (root is the gameobject referencing the animator) and crc32 numbers.
1.4. If I find the number in the list, then I use search and replace (notepad++) to replace all in all animations:
   - exemple: replace all 'path: path_4107199140' with 'path: MyGameObject/MySubGameObject' in *.anim
 
This should solve most of the 'path' issues. Now for the attributes...

2.0 Find the culprit attributes:
2.1 search for : 'attribute: typetree_' and 'attribute: script_'  (ex: attribute: script_2033536083)
2.2 Find the associated animator (if any) using those animations
2.3 Find the gameobject (scene or prefab) using that animator (or animation).
2.4 Find the component that has the wrong attribute
2.5 make a new gameobject and that that component, and add an animator with animation to animate a parameter of that component (for example, animate just the red of a color property. save project (needed to save the animation to disk)
2.6 open that animation file in a text editor, and look for the name of the attribute: (ex: 'attribute: Color.r'). then look a few lines down in the 'genericBindings' section, for the line with 'attribute: 2033536083 (matching the previous search ex: 
attribute: script_2033536083
If the number is not there, go back to unity, delete the previous animation parameter and animate another parameter (ex: Green color), save project go back yo notepad++ and do the same...

Eventually, you will find the matching number/parameter and do a search/replace.....

Yeak I know, it's not ideal. but a least it works for me.


Should you want that custom editor script (prone to errors, and very badly coded, but it world for me, just let me know

Z

**Comment by Crambone** [comment]
Hi! Thanks a lot, I will try.

**Comment by Zbuffers** [comment]
;)
here is the script:
Selectect the gameobject with the animator and run (zTools/printCRCHierarchy)
then select the Debug loig entry to vie the while list.

`using System;
using System.Collections.Generic;
using System.Security.Cryptography;
using UnityEngine;
using UnityEditor;
using System.Text;
using System.IO;

namespace ZB
{
	public class PrintCRCHierarchy
	{
		[MenuItem("zTools/Print CRC Hierarchy", false, 10)]
		static void Print(MenuCommand menuCommand)
		{
			GameObject selected = Selection.activeGameObject;
			var children = GameObjectChildrenPaths(selected);

			string str = "";

			foreach (var child in children)
				str += CRC32.Compute(child) + " -> " + child + "\n";

			Debug.Log(str);
		}

		static List<string> GameObjectChildrenPaths(GameObject go)
		{
			Transform root = go.transform;
			List<string> childrenPath = new List<string>();

			if (root != null)
			{
				Transform[] children = root.GetComponentsInChildren<Transform>(true);

				foreach (Transform tr in children)
				{
					if (tr == root) continue;
					
					string path = tr.gameObject.name;
					Transform t = tr;

					while (t.parent != root)
					{
						path = t.parent.name + "/" + path;
						t = t.parent;
					}
					
					childrenPath.Add(path);
				}
			}

			return childrenPath;
		}
	}

	class CRC32 : HashAlgorithm
	{
		internal const uint DefaultPolynomial = 3988292384u;
		internal const uint DefaultSeed = uint.MaxValue;

		private uint hash;
		private uint seed;
		private uint[] table;
		private static uint[] defaultTable;

		internal CRC32()
		{
			table = InitializeTable(DefaultPolynomial);
			seed = DefaultSeed;
			Initialize();
		}

		internal CRC32(uint polynomial, uint seed)
		{
			table = InitializeTable(polynomial);
			this.seed = seed;
			Initialize();
		}

		public override void Initialize() { hash = seed; }

		protected override void HashCore(byte[] buffer, int start, int length) { hash = CalculateHash(table, hash, buffer, start, length); }

		protected override byte[] HashFinal()
		{
			byte[] bytes = UInt32ToBigEndianBytes(~hash);
			HashValue = bytes;
			return bytes;
		}

		public override int HashSize { get { return 32; } }

		internal static uint Compute(byte[] data)
		{
			return ~CalculateHash(InitializeTable(DefaultPolynomial), uint.MaxValue, data, 0, data.Length);
		}

		internal static uint Compute(uint[] values)
		{
			MemoryStream memoryStream = new MemoryStream();
			foreach (uint value in values)
			{
				memoryStream.Write(BitConverter.GetBytes(value), 0, 4);
			}

			byte[] array = memoryStream.ToArray();
			return ~CalculateHash(InitializeTable(0xEDB88320u), uint.MaxValue, array, 0, array.Length);
		}

		internal static uint Compute(string str)
		{
			if (!string.IsNullOrEmpty(str))
				return Compute(Encoding.UTF8.GetBytes(str));
			
			return 0u;
		}

		internal static uint Compute(params string[] str)
		{
			if (str == null)
			{
				return 0u;
			}

			uint num = 0u;
			foreach (string text in str)
			{
				if (!string.IsNullOrEmpty(text))
				{
					num = Compute(~num, Encoding.UTF8.GetBytes(text));
				}
			}

			return num;
		}

		internal static uint Compute(uint polynomial, byte[] buffer)
		{
			return ~CalculateHash(InitializeTable(DefaultPolynomial), polynomial, buffer, 0, buffer.Length);
		}
		
		internal static uint Compute(uint polynomial, uint hash, byte[] buffer)
		{
			return ~CalculateHash(InitializeTable(polynomial), hash, buffer, 0, buffer.Length);
		}

		private static uint[] InitializeTable(uint polynomial)
		{
			if (polynomial == DefaultPolynomial && defaultTable != null)
			{
				return defaultTable;
			}

			uint[] table = new uint[256];
			for (int i = 0; i < 256; i++)
			{
				uint hash = (uint)i;
				for (int j = 0; j < 8; j++)
				{
					if ((hash & 1u) == 1u)
					{
						hash = hash >> 1 ^ polynomial;
					}
					else
					{
						hash >>= 1;
					}
				}

				table[i] = hash;
			}

			if (polynomial == DefaultPolynomial)
			{
				defaultTable = table;
			}

			return table;
		}

		private static uint CalculateHash(uint[] table, uint hash, byte[] buffer, int start, int length)
		{
			uint _hash = hash;
			for (int i = start; i < length; i++)
			{
				_hash = _hash >> 8 ^ table[(int)(buffer[i] ^ _hash & 255u)];
			}

			return _hash;
		}

		private byte[] UInt32ToBigEndianBytes(uint value)
		{
			return new[]
			{
				(byte)(value >> 24 & 255u),
				(byte)(value >> 16 & 255u),
				(byte)(value >> 8 & 255u),
				(byte)(value & 255u)
			};
		}
	}
}
`
Hope this helps a bit ;)
Z

**Comment by Crambone** [comment]
Thank you :] I did manage to find the paths and properties, I'll have to slice the sprite sheets now, because they didn't slice it the unity way, but instead used sprite studio for most of the animation stuff. I feel like I'm close, It's just time consuming, but I'll probably figure out a way to automate the process.

**Comment by epstomai** [comment]
In case someone may need this, I made a script to recover blendshape names based on Zbuffers's code.
Be careful, this script will overwrite your animation clip file, so it's better to make some backups.

![Snipaste_2024-03-26_00-55-23](https://github.com/AssetRipper/AssetRipper/assets/20502421/812d61e9-d5e0-4608-8d29-bead7c382df2)
![Snipaste_2024-03-26_00-54-32](https://github.com/AssetRipper/AssetRipper/assets/20502421/27aeadb9-53f8-4283-950f-dec08852e966)

`
using System;
using System.Collections.Generic;
using System.Security.Cryptography;
using UnityEngine;
using UnityEditor;
using System.Text;
using System.IO;

public class BlendshapeNameRecover : EditorWindow
{
    AnimationClip clip;
    GameObject bsObject;

    [MenuItem("zTools/BlendshapeNameRecover")]
    static void Init()
    {
        BlendshapeNameRecover window = (BlendshapeNameRecover)EditorWindow.GetWindow(typeof(BlendshapeNameRecover));
        window.Show();
    }

    void OnGUI()
    {
        clip = EditorGUILayout.ObjectField("Animation Clip", clip, typeof(AnimationClip), false) as AnimationClip;
        bsObject = EditorGUILayout.ObjectField("GameObject", bsObject, typeof(GameObject), true) as GameObject;
        EditorGUILayout.Space(5);
        if (GUILayout.Button("Modify Animation"))
        {
            if (clip != null && bsObject != null)
            {
                ModifyAnimation(clip, bsObject);
                Debug.Log("Done.");
            }
            else
            {
                Debug.Log("GameObject nor Animation Clip cannot be null.");
            }
        }
    }

    void ModifyAnimation(AnimationClip clip, GameObject selected)
    {
        string path = AssetDatabase.GetAssetPath(clip);
        string animContent = File.ReadAllText(path);

        string[] bsNames = GetBlendShapeNames(selected);
        foreach (var name in bsNames)
        {
            string crcName = Convert.ToString(CRC32.Compute(name));
            animContent = animContent.Replace(crcName, name);
        }
        File.WriteAllText(path, animContent);
    }

    string[] GetBlendShapeNames(GameObject obj)
    {
        SkinnedMeshRenderer renderer = obj.GetComponent<SkinnedMeshRenderer>();
        Mesh mesh = renderer.sharedMesh;
        string[] blendShapes = new string[mesh.blendShapeCount];

        for (int i = 0; i < mesh.blendShapeCount; i++)
        {
            blendShapes[i] = mesh.GetBlendShapeName(i);
        }

        return blendShapes;
    }

    class CRC32 : HashAlgorithm
    {
        internal const uint DefaultPolynomial = 3988292384u;
        internal const uint DefaultSeed = uint.MaxValue;

        private uint hash;
        private uint seed;
        private uint[] table;
        private static uint[] defaultTable;

        internal CRC32()
        {
            table = InitializeTable(DefaultPolynomial);
            seed = DefaultSeed;
            Initialize();
        }

        internal CRC32(uint polynomial, uint seed)
        {
            table = InitializeTable(polynomial);
            this.seed = seed;
            Initialize();
        }

        public override void Initialize() { hash = seed; }

        protected override void HashCore(byte[] buffer, int start, int length) { hash = CalculateHash(table, hash, buffer, start, length); }

        protected override byte[] HashFinal()
        {
            byte[] bytes = UInt32ToBigEndianBytes(~hash);
            HashValue = bytes;
            return bytes;
        }

        public override int HashSize { get { return 32; } }

        internal static uint Compute(byte[] data)
        {
            return ~CalculateHash(InitializeTable(DefaultPolynomial), uint.MaxValue, data, 0, data.Length);
        }

        internal static uint Compute(uint[] values)
        {
            MemoryStream memoryStream = new MemoryStream();
            foreach (uint value in values)
            {
                memoryStream.Write(BitConverter.GetBytes(value), 0, 4);
            }

            byte[] array = memoryStream.ToArray();
            return ~CalculateHash(InitializeTable(0xEDB88320u), uint.MaxValue, array, 0, array.Length);
        }

        internal static uint Compute(string str)
        {
            if (!string.IsNullOrEmpty(str))
                return Compute(Encoding.UTF8.GetBytes(str));

            return 0u;
        }

        internal static uint Compute(params string[] str)
        {
            if (str == null)
            {
                return 0u;
            }

            uint num = 0u;
            foreach (string text in str)
            {
                if (!string.IsNullOrEmpty(text))
                {
                    num = Compute(~num, Encoding.UTF8.GetBytes(text));
                }
            }

            return num;
        }

        internal static uint Compute(uint polynomial, byte[] buffer)
        {
            return ~CalculateHash(InitializeTable(DefaultPolynomial), polynomial, buffer, 0, buffer.Length);
        }

        internal static uint Compute(uint polynomial, uint hash, byte[] buffer)
        {
            return ~CalculateHash(InitializeTable(polynomial), hash, buffer, 0, buffer.Length);
        }

        private static uint[] InitializeTable(uint polynomial)
        {
            if (polynomial == DefaultPolynomial && defaultTable != null)
            {
                return defaultTable;
            }

            uint[] table = new uint[256];
            for (int i = 0; i < 256; i++)
            {
                uint hash = (uint)i;
                for (int j = 0; j < 8; j++)
                {
                    if ((hash & 1u) == 1u)
                    {
                        hash = hash >> 1 ^ polynomial;
                    }
                    else
                    {
                        hash >>= 1;
                    }
                }

                table[i] = hash;
            }

            if (polynomial == DefaultPolynomial)
            {
                defaultTable = table;
            }

            return table;
        }

        private static uint CalculateHash(uint[] table, uint hash, byte[] buffer, int start, int length)
        {
            uint _hash = hash;
            for (int i = start; i < length; i++)
            {
                _hash = _hash >> 8 ^ table[(int)(buffer[i] ^ _hash & 255u)];
            }

            return _hash;
        }

        private byte[] UInt32ToBigEndianBytes(uint value)
        {
            return new[]
            {
                (byte)(value >> 24 & 255u),
                (byte)(value >> 16 & 255u),
                (byte)(value >> 8 & 255u),
                (byte)(value & 255u)
            };
        }
    }
}
`
