### ISSUE TITLE
[Bug]: I’m Getting an Error When Extracting Scenes From the Game

### ISSUE THREAD

**Issue by Xerapht** [AssetRipper/AssetRipper#955]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

[https://steamdb.info/app/1129540/](https://steamdb.info/app/1129540/)

### Which Unity version did this occur on?

2022.1.0.9261453

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

I’m getting an error when extracting scenes from the game.
If you need the files, I can compress the files and send them to you.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12186053/AssetRipper.log)

**Comment by ds5678** [comment]
This has already been fixed.
