### ISSUE TITLE
[Bug]: I Can’t Load the Game Files

### ISSUE THREAD

**Issue by Xerapht** [AssetRipper/AssetRipper#956]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

[https://steamdb.info/app/1129540/](https://steamdb.info/app/1129540/)

### Which Unity version did this occur on?

2022.1.0.9261453

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Sorry to bother you again, but it's still not working.
I'm using the latest version.

### Relevant log output

![assetripper_issue](https://github.com/AssetRipper/AssetRipper/assets/140740805/eac0f5d0-c0d5-4c65-aace-188acc387b22)

**Comment by ds5678** [comment]
The fix has not yet made it into a release. You can either for a release (probably Sunday) or download an alpha build.

**Comment by Xerapht** [comment]
Oh, I understand now. I wish you success for your work, I'll wait patiently. Thank you.
