### ISSUE TITLE
[Bug]: Obfuscated assemblies should not be decompiled

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#958]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Different games

### Which Unity version did this occur on?

2019.4, 2021.3

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Hello,

This probably refers to issue #871...
Using the latest commit as of today

When I choose to export project with scripts as decompiled (note that hybrid works fine, ;)),
I experience a crash when it tries to decompile 'Rewired_Core.dll'
A previous issue (#871) mentions this problem, and is marked it as closed, so i think it it still not resolved...

See attached log with the error

Note: if Using ILSpy version 8.xxx, it decompiles just fine...

Kind regards,
And keep up the GREAT work ;)
Z

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12206777/AssetRipper.log)

**Comment by mattie078** [comment]
Yeah they broke decompiling for obfuscated code in 8.0.0.7313-preview4. If you build the project with NuGet [8.0.0.7246-preview3](https://www.nuget.org/packages/ICSharpCode.Decompiler/8.0.0.7246-preview3) then it works fine.

**Comment by ds5678** [comment]
@mattie078 was that an intentional change? Do you have any links?

**Comment by ds5678** [comment]
I would prefer not to stay on an old version of ILSpy. If this is going to be a persistent problem, it would be good for AssetRipper to detect obfuscated assemblies and refrain from decompiling them.

**Comment by mattie078** [comment]
Honestly I'm not sure, accidently ran into the same bug as the same time as this issue was opened so I don't have the complete details but it seems like it broke when they introduced [support for Visual Basic Yield Return state machine decompilation](https://github.com/icsharpcode/ILSpy/pull/2874#top). 

I'm going to take a better look later today but I'm not sure if it was intended to work [in the first place](https://github.com/icsharpcode/ILSpy/issues/2223).

**Comment by Zbuffers** [comment]
Hi,
Just to be more precise,
the version of ILSpy (standalone) that works for me  is the latest as of today:
8.0.0.7345

**Comment by ds5678** [comment]
So I could have bumped to the latest instead of downgrading to preview 3?

**Comment by mattie078** [comment]
Weird.. I tried to decompile using the same version that was "broken" a few days ago and today and I didn't encounter the crash anymore. Maybe something externally got fixed somehow. No clue...

Anyhow, I've build AssetRipper using the latest ICSharpCode.Decompiler NuGet package and everything works as it should.
So as far as I know you can upgrade the version again to the latest. Sorry for the inconvinience
