### ISSUE TITLE
[Bug]: Incorrect Generic Class Export Path

### ISSUE THREAD

**Issue by cyberangel67** [AssetRipper/AssetRipper#96]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

not sure

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Any generic script as

class Singleton<T> {
}

Is extracted as Singleton~1.cs instead of Singleton.

**Comment by ds5678** [comment]
f5e97ef018d10ad73360bdcb130052e4122d8a3e cleans up some of the pathing
