### ISSUE TITLE
[Bug]: I’m Getting an AnimationClip Error

### ISSUE THREAD

**Issue by Xerapht** [AssetRipper/AssetRipper#961]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

[https://steamdb.info/app/1129540/](https://steamdb.info/app/1129540/)

### Which Unity version did this occur on?

2022.1.0.9261453

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

I found a new error, I'd like to share it with you.
I think the animations are causing problems.

### Relevant log output

![assetripper_issue](https://github.com/AssetRipper/AssetRipper/assets/140740805/71a6d3d8-55a0-4792-bd97-1c25a695e77c)

**Comment by Xerapht** [comment]
Can we export by ignoring animations?

**Comment by ds5678** [comment]
Actual log please

**Comment by ds5678** [comment]
I also think you're using an outdated version.

**Comment by Xerapht** [comment]
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12211247/AssetRipper.log)

**Comment by Xerapht** [comment]
I can compress the files and send them if that helps.

**Comment by ds5678** [comment]
Thank you. That's way easier to read.

I think that's caused by `level3` not being part of the game anymore.

**Comment by ds5678** [comment]
> I think that's caused by `level3` not being part of the game anymore.

See https://steamdb.info/depot/1129541/history/?changeid=M:762733069851296617

**Comment by Xerapht** [comment]
Finally, I prepared the files!
Here are the playable and original game files if you need them:
[https://drive.google.com/file/d/14XQkPG05_U8YSof2ayVlBV4BrkXlRCNy/view?usp=sharing](https://drive.google.com/file/d/14XQkPG05_U8YSof2ayVlBV4BrkXlRCNy/view?usp=sharing)

**Comment by Xerapht** [comment]
I reduced it from 16 GB to about 7 GB.

**Comment by Xerapht** [comment]
Here it is! Playable and original game files if that will help your work:
[https://drive.google.com/file/d/1oOhFa0yZrGKInktUNHS3fmzIvUjzLXJ0/view?usp=sharing](https://drive.google.com/file/d/1oOhFa0yZrGKInktUNHS3fmzIvUjzLXJ0/view?usp=sharing)

**Comment by Xerapht** [comment]
I compressed them from 16 GB to 7 GB

**Comment by ds5678** [comment]
If you delete level3, can you still play the game?

**Comment by Xerapht** [comment]
Yes, I can

**Comment by Xerapht** [comment]
Also, the StreamingAssets folder is 7 GB, but when I delete them too the game still works.

**Comment by Xerapht** [comment]
Also, the `StreamingAssets` folder is 7 GB, but when I delete them too the game still works.

**Comment by ds5678** [comment]
Not an AssetRipper problem then. That extra file is causing the problem.
