### ISSUE TITLE
Unstable Rip Results for ULTRAKILL in new versions of AssetRipper.

### ISSUE THREAD

**Issue by GlitchyF** [AssetRipper/AssetRipper#967]
I've been getting some really unstable rips for the **newer version of Asset Ripper** and I don't know why. A buttload of assets aren't in their respective folders, weird gibberish model files appear outside the assets folder being unreadable by the default 3d viewer, and just a lot of weird things. Now this isn't what is supposed to happen, _I've got more stable rips before_, but I lost the version I used for those and both the release and beta versions of Asset Ripper currently have the same result.

![image](https://github.com/AssetRipper/AssetRipper/assets/121588329/a59c03aa-b318-4ef6-8c68-5d000782d190)
![image](https://github.com/AssetRipper/AssetRipper/assets/121588329/20b7cfe4-4a76-4ee6-9dec-9b340cc8e888)
![image](https://github.com/AssetRipper/AssetRipper/assets/121588329/4a88b897-c6f7-403c-b3c2-14c67c783a46)
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12234936/AssetRipper.log)
****

**Comment by ds5678** [comment]
If I had to guess, I'd speculate that your differing behavior began sometime around `0.3.0.X` when asset processing was implemented. I think the files should be all in the Assets folder on the latest commit. Is that your experience too?

**Comment by Prosopho** [comment]
If you set **Mesh Export Format** to YAML instead of GLB, you should get a more stable result. I got the same results with GLB.
![image](https://github.com/AssetRipper/AssetRipper/assets/109369903/00154933-f23f-4204-8b0c-709d74c16b50)

**Comment by ds5678** [comment]
Is this still an issue on the latest alpha?

**Comment by GlitchyF** [comment]
Sorry for the late response, but it seems like this is still happening in some form in the newest alpha at the moment. Though from this first initial rip it seems like the gibberish files are gone.

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12842323/AssetRipper.log)
![image](https://github.com/AssetRipper/AssetRipper/assets/121588329/d25f7d07-b08f-49a6-8155-8572219ca128)
![image](https://github.com/AssetRipper/AssetRipper/assets/121588329/c40e34e4-2997-44c1-b7b8-e8f8e16130e4)
![image](https://github.com/AssetRipper/AssetRipper/assets/121588329/c6ca8491-bac7-4710-a80b-dad68551bd9c)

**Comment by ds5678** [comment]
So what exactly is wrong? I have no idea what you want me to change.

**Comment by GlitchyF** [comment]
I may have not included this in the images entirely, but a good majority of the files (including the scenes inside of the scenes folder) still are at the very least displaced, and I think some are even missing still.
![image](https://github.com/AssetRipper/AssetRipper/assets/121588329/6521d254-1562-4e5f-81b8-e4f576a0ba45)
![image](https://github.com/AssetRipper/AssetRipper/assets/121588329/9c41d8f8-be1c-4ce4-aec6-708ee2ed76fd)
![image](https://github.com/AssetRipper/AssetRipper/assets/121588329/2344c3b5-b7a6-4042-ac4d-527fe72018da)

**Comment by ds5678** [comment]
6 months ago, ULTRAKILL switched to addressables. That would explain the deviation in file placement.

https://steamdb.info/depot/1229491/history/?changeid=M:6658239261054002710

**Comment by GlitchyF** [comment]
So, do the developers using addressables make it so this type of output is unavoidable from now on?

**Comment by ds5678** [comment]
Yes, their use of addressables permanently changes how the assets are stored in the game.
