### ISSUE TITLE
[Enhancement]: Better naming of Asset Bundles 

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#977]
### Describe the new feature or enhancement

Hi,

When Choosing to export Bundled Assets using the Group By Bundle Name option,
I get a bunch of folders exported to the 'Assets/Asset_Bundles' folder, which is great and works fine.

The naming of those folders (asset bundle name) is ... not user friendly at all...
here is an example of the exported folders (asset bundle names).

```
0ce06dbfe7e644875ed80d9b40c4e245.bundle
10ae97c59d3898376303dacc4de86901.bundle
1262e4c9ea4a9616873f6d613e41e303.bundle
1772173c12d9735a67dc312ac4d8822e.bundle
298199c807f9d57d72ad9f9309214ae0.bundle
...
```

In the game's 'StreamingAssets' folder, bundles names look like this:

```
adventure_assets_all_a0c58381cd0fc26aa4f545fe69912be5.bundle
ancientempire_assets_all_19649f6bd1fe3299fb13f54d6fbbd3a4.bundle
apocalypse_assets_all_a9d654e31cd12b1d25f8d2002098f8d8.bundle
battleroyale_assets_all_e599c04ca4a6f38f979e69a6344f27b8.bundle
city_assets_all_559d2c315d58e7024a7c91e07abd3136.bundle
...
```

There seams to be NO relation between those names.
So a great improvement would be to use part of the 'readable' names (first part of the original bundle (before '_assets_all)

maybe something like:

```
adventure.bundle
ancientempire.bundle
apocalypse.bundle
battleroyale.bundle
city_assets.bundle
```

Not super high priority, but would make dealing with bundles (and adressables) MUCH easier.
Note: this example was using adressables...

Kind regards,
Z

**Comment by ds5678** [comment]
That's the string stored in `IAssetBundle`.

https://github.com/AssetRipper/AssetRipper/blob/a2ba903b98a8781159fc1330ba3c66bdfff750a7/Source/AssetRipper.SourceGenerated.Extensions/AssetBundleExtensions.cs#L19

**Comment by ds5678** [comment]
See also:

https://github.com/AssetRipper/AssetRipper/blob/a2ba903b98a8781159fc1330ba3c66bdfff750a7/Source/AssetRipper.Processing/Editor/OriginalPathHelper.cs#L50-L110

**Comment by Zbuffers** [comment]
Because otherwise a get a whole bunch of files in the root assets folder, witch i don't like ;)

Also, I was playing with 'Pummel party' game... 
It uses a serialized guid system, in conjunction with adressable assets. (serialized guid is the adressable name) 
for an in game editor... (I learned that unity guids are NOT serializable !!!)
Since all guids are modified from the original ones, I wanted to 'redo' the game assets folder structure in order
to remap the bundled assets guids to their serialized guids name in adressable groups.

I hacked the adressable package to extract the catalog.json data, so I can get the serialized guids (no name, ,no path).
then a specific asset in the game lists all assets with serialized guid, folder path, and names.
So I could find each bundle name to rename the folders, then remap guids... 

Also, I found that the name of the asset bundle is taken from the adressable group.
ex: 'battleroyale_assets_all_e599c04ca4a6f38f979e69a6344f27b8.bundle' is in fact the bundle from the 'battleroyale" adressable group.

I'm happy cause now i all works fine, and i learned a bit more about adressables ;)
Z

**Comment by ds5678** [comment]
As per your initial request, I am unlikely to change how this mode functions. I've considered removing the mode entirely, but there's currently no harm in leaving it in.

**Comment by Zbuffers** [comment]
Hmmm, not good news for me ...
But no worries, I'll deal with that myself ;)

And if by any chance, implementing adressables happens a some point, you will want this feature...
Just my 2 cents ;)
Cheers ;)

**Comment by ds5678** [comment]
Is it alright if I close this?

**Comment by Zbuffers** [comment]
of course ;)
