### ISSUE TITLE
[Bug]: Import: Dependency 'library/unity default resources' wasn't found

### ISSUE THREAD

**Issue by BinkanSalaryman** [AssetRipper/AssetRipper#984]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://www.kongregate.com/games/Cael/reactor-incremental

### Which Unity version did this occur on?

Asset ripper creates a Unity 2017.2.0f3 project, UABE did not accept the game files

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

For some reason, asset ripper fails to import the unity default resources library, and thus the script files are blanked out. I would expect special handling for unity default libraries, or do I have to somehow provide this library?

### Relevant log output

```System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.22621.0
System : Operating System: Windows 64 bit
System : AssetRipper Version: 0.3.3.1
System : AssetRipper Build Type: Release Published
System : UTC Current Time: Fri Aug 11 19:39:35 UTC 2023
System : UTC Compile Time: Mon Aug  7 02:10:48 UTC 2023
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : DefaultVersion: 0.0.0a0
General : ExportRootPath: E:\Apps\Applications\Unity AssetRipper\Ripped
General : ExportDependencies: False
General : BundledAssetsExportMode: DirectExport
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Hybrid
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
General : EnablePrefabOutlining: False
General : EnableStaticMeshSeparation: False
General : IgnoreEngineAssets: False
General : Attempting to read files from E:\Build
Import : Game file 'Build' has been found
Import : Mixed game structure has been found at E:\Build
Import : Files use the 'Unknown' scripting backend.
Import [Warning] : Dependency 'library/unity default resources' wasn't found
General : Finished reading files
General : Processing loaded assets...
Processing : Creating Scene Definitions
Processing : Main Asset Pairing
Processing : Lighting Data Assets
Processing : Reconstruct AnimatorController Assets
Processing : Reconstruct AudioMixer Assets
Processing : Editor Format Conversion
General : Finished processing assets
Import [Warning] : Asset collection has versions probably incompatible with each other. Here they are:
Import [Warning] : 2017.2.0f3
Import [Warning] : 2017.2.0b11```

**Comment by ds5678** [comment]
> https://www.kongregate.com/games/Cael/reactor-incremental

I'm not sure how to access the embedded game files.

**Comment by BinkanSalaryman** [comment]
> > https://www.kongregate.com/games/Cael/reactor-incremental
> 
> I'm not sure how to access the embedded game files.

Access your browser's devtools (assuming it's chromium-based), go to the the network tab and reload the page. Filter the list by searching for "Build", and you'll see something like this:
![image](https://github.com/AssetRipper/AssetRipper/assets/6740731/1b84da66-cc54-41f9-8184-2d65876a6e28)

Every file listed there with the exception of UnityLoader.js should be sufficient for a unity web game, from my understanding.

At the time of writing, this is the list of files I get, though the game is being considered abandonded by the developers (and the sequel, Reactor Redux, seems like a step down of the original):
- [Build.json](https://game230582.konggames.com/gamez/0023/0582/live/Build/Build.json)
- [Build.asm.code.unityweb](https://game230582.konggames.com/gamez/0023/0582/live/Build/Build.asm.code.unityweb)
- [Build.asm.memory.unityweb](https://game230582.konggames.com/gamez/0023/0582/live/Build/Build.asm.memory.unityweb)
- [Build.asm.framework.unityweb](https://game230582.konggames.com/gamez/0023/0582/live/Build/Build.asm.framework.unityweb)
- [Build.data.unityweb](https://game230582.konggames.com/gamez/0023/0582/live/Build/Build.data.unityweb)
