### ISSUE TITLE
[Bug]: does not recognize assetbundle from version 2019.4.40f

### ISSUE THREAD

**Issue by leostudiosTM** [AssetRipper/AssetRipper#988]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

saint seiya game not released yet

### Which Unity version did this occur on?

2019.4.40f

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

the tool can't read this file it doesn't crash or anything it just doesn't recognize
[https://cdn.discordapp.com/attachments/1048345920401584188/1140876985665589278/aiolos_cloth_prefab.assetbundle](url)

**Comment by ds5678** [comment]
This file is either encrypted or in a custom format.

**Comment by leostudiosTM** [comment]
dude you didn't even check it i found out that the tool reads the file if i delete that part :/
[https://cdn.discordapp.com/attachments/1048345920401584188/1140877697006968862/image.png](url)

**Comment by ds5678** [comment]
That qualifies as custom.
