### ISSUE TITLE
[Question]: how do i run on linux (not ubuntu)

### ISSUE THREAD

**Issue by dantheman121** [AssetRipper/AssetRipper#993]
### Question

when i download i get a no extension file and i don't know how to run that file
![Screenshot 2023-08-18 12 15 02 PM](https://github.com/AssetRipper/AssetRipper/assets/130871739/02fb4506-19dd-43e3-be2c-311e81fc1820)

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by ds5678** [comment]
https://www.google.com/search?q=how+to+run+an+executable+file+on+linux
